### ISSUE TITLE
Warnings: Unable to ensure uniqueness for usernames

### ISSUE THREAD

**Issue by jashsayani** [parse-community/parse-server#2699]
I am writing a server that uses ParseServer (Express + ParseServer), and I see this when I run it:

```
warn: Unable to ensure uniqueness for usernames:  MongoError: not authorized for
query on mydatabase._SCHEMA

warn: Unable to ensure uniqueness for user email addresses:  MongoError: not authorized
for query on mydatabase._SCHEMA
```

I see that Mongo is having issues with querying the schema? Probably an indexing issue?

**Comment by haydenbleasel** [comment]
I get a similar one:

```
warn: Unable to ensure uniqueness for usernames:  MongoError: no valid replicaset members found
warn: Unable to ensure uniqueness for user email addresses:  MongoError: no valid replicaset members found
```

**Comment by bohemima** [comment]
`MongoError: not authorized for query on mydatabase._SCHEMA`

Check your username/password and that that user have the required permissions on the database.

and for @haydenbleasel `MongoError: no valid replicaset members found`

**Comment by haydenbleasel** [comment]
@bohemima What does that mean?

**Comment by bohemima** [comment]
It's not really a question for this forum but I would check the databaseURI and make sure it's correct. Could also be a number of other issues, a search for the error gives you plenty of reading material.

**Comment by haydenbleasel** [comment]
The databaseURI is definitely correct, I have done a massive search and it's not yielding much luck. I believe it might be coupled with #2580 since I get this straight after:

```
/Users/haydenbleasel/Documents/Projects/x/node_modules/parse-server/lib/ParseServer.js:405
            throw err;
            ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/Users/haydenbleasel/Documents/Projects/x/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/Users/haydenbleasel/Documents/Projects/x/node_modules/express/lib/response.js:164:12)
    at done (/Users/haydenbleasel/Documents/Projects/x/node_modules/express/lib/response.js:956:10)
    at Immediate._onImmediate (/Users/haydenbleasel/Documents/Projects/x/node_modules/express-handlebars/lib/utils.js:26:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by flovilmart** [comment]
Are you using version 2.2.19?

**Comment by haydenbleasel** [comment]
@flovilmart Yep as mentioned above 👍

**Comment by flovilmart** [comment]
The headers already sent error should not yield in 2.2.19 as we removed the next() calls on success. You probably have a middleware for handling errors. 

For the databaseURI problem, that's probably related to the issue you mentioned but I don't have that error myself, and can properly connect to the replicaset. Do you have any special chars in your username/password?

**Comment by haydenbleasel** [comment]
My username field is the same as the email field at the moment (so we can log in with email). Perhaps the @ character?

**Comment by flovilmart** [comment]
Yeah... that may interfere with the URL parser as it will see 2 @'s.

@ and : can be problematic for some URL parsers when providing username/pass inline.

Like:

MongoDB://hello@world.com:pass@mydomain.com:port/path

**Comment by haydenbleasel** [comment]
Oh sorry I thought you meant my actual app login haha. No my database user / pass doesn't have any special characters. BTW, this issue just got resolved for me. It works at home but not at the office. Weird.

**Comment by flovilmart** [comment]
that's odd. And from the office, you can connect correctly to the DB from the CLI?

**Comment by haydenbleasel** [comment]
I just got home and everything's working correctly. From the office all day (no code changes since then), I've had the two errors mentioned above (MongoError and Can't Set Headers). The DB connection from CLI is kinda sketchy - their firewall is pretty intense though (university).

**Comment by flovilmart** [comment]
So, get yourself a VPN or a remote server when working from the uni :)

**Comment by haydenbleasel** [comment]
Yep my bad haha, problem solved.

**Comment by flovilmart** [comment]
Glad you found the solution! Closing

**Comment by flovilmart** [comment]
Is there any logs that mongo would provide so you can drill down that issue? That is highly unlikely to be an issue with parse-server itself, but probably with your authentication mechanism with mongo.

**Comment by sitemart** [comment]
Usually happens behind a proxy or if you are working locally without an active internet connection which is somehow weird to me.

**Comment by jashsayani** [comment]
I am still seeing this error - password has some special characters like `}{` and `a^` and `\1`, etc.

**Comment by flovilmart** [comment]
@jashsayani can you update your password without special chars?

**Comment by jashsayani** [comment]
> @jashsayani can you update your password without special chars?

I am not sure if removing special characters from the password is a move in the right direction. Its generated by mLab and used by the hosted Parse solution for writing data thats sent to `api.parse.com`, and not having special characters in the password is a bad move.

**Comment by flovilmart** [comment]
I'm asking that to see if there is an encoding problem with the mondo DB URL. We pass that URL directly to the MongoDB node module and should not apply any transformation. Can you connect to the database with the same URL with the MongoDB node module?

**Comment by jashsayani** [comment]
Seems to be working with: https://github.com/rsercano/mongoclient

I believe it uses the Mongo node module.

**Comment by flovilmart** [comment]
Not the same version though, the module you suggest is using 2.1.18, we're at 2.2.10.

**Comment by bartonhammond** [comment]
I'm getting same error when starting server locally.  
It runs on Heroku just fine w/ the same MongoDB URI.
Not sure what to do

here's my error:

```
~/projects/snowflakework/snowflake-parse-heroku (master)$ npm start

> snowflake-parse-heroku@0.0.1 start /Users/barton/projects/snowflakework/snowflake-parse-heroku
> node index.js

verbose: Support key pairs Map {}
parse-server-example running on port 1337.
info: Parse LiveQuery Server starts running
warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [ds137267.mlab.com:27017] on first connect
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [ds137267.mlab.com:27017] on first connect
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/barton/projects/snowflakework/snowflake-parse-heroku/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
```

**Comment by gorockymin** [comment]
Recently, I updated parse server to 2.2.25 and set mongoDB with replication set.
In databaseURI configuration, I set the following link:

mongodb://username:pwd@ip1:port,ip2:port,ip3:port/db?replicaSet=rs-db

It's same as the Parse.com migration setup. Parse.com have no problem.
However, it doesn't work in the parse-server open source.

The error message is 
warn: Unable to ensure uniqueness for usernames:  domain=null

**Comment by flovilmart** [comment]
Closing due to lack of activity, please update to latest parse-server version and open a new issue if the issue persist.

Don't forget to include your current:
- node version
- npm version
- parse-server version
- any relevant logs (VERBOSE=1 will enable verbose logging)
