### ISSUE TITLE
Objects not updated with correct data after modification in beforeSave function

### ISSUE THREAD

**Issue by talkaboutdesign** [parse-community/parse-server#2829]
Describe your issue in as much detail as possible.

I am performing some functions in Cloud Code on beforeSave and modifying some of the object properties. In my particular case I am updating image width and height properties before the record will be created. I then set the new value using this code: 

```
request.object.set("imageWidth", 800);
request.object.set("imageHeight", 600);
```

I then call Success in code in order to save the object like so: 

`response.success();`

Problem is that this is unreliable. Yesterday this was working fine, today it's not updating the records in the database with new values. Is anyone else experiencing this issue?
#### Expected Results

Object should be saved to the database with updated fields.
#### Actual Outcome

Object is saved to the database with unchanged values.
### Environment Setup

Latest version of Parse Sever

**Comment by flovilmart** [comment]
Are you running parse-server or on parse.com?

**Comment by talkaboutdesign** [comment]
I am running parse-server

**Comment by flovilmart** [comment]
Did you update Parse-server in the meantime? can you provide the logs when running with VERBOSE=1?

**Comment by talkaboutdesign** [comment]
Server is updated to the latest version. I see this in logs not sure if it's related: 

`{"className":"Posts","triggerType":"beforeSave","error":{"code":141,"message":"Object is not saved"},"level":"error","message":"beforeSave failed for Posts for user undefined:\n  Input: {\"submittedBy\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"kC4EoOYFHc\"}}\n  Error: {\"code\":141,\"message\":\"Object is not saved\"}","timestamp":"2016-10-04T19:20:57.271Z"}`

**Comment by talkaboutdesign** [comment]
I have this set in new ParseServer function 

`logLevel: 'VERBOSE'`

Is this correct?

**Comment by talkaboutdesign** [comment]
Verbose log when performing Cloud Code function: 

```
verbose: REQUEST for [GET] /parse/classes/Posts: {
  "where": {},
  "limit": 1
} method=GET, url=/parse/classes/Posts, user-agent=node-XMLHttpRequest, Parse/js1.9.1 (NodeJS 6.7.0), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=188, connection=close, , limit=1
error: Error generating response. { MongoError: failed to connect to server [hidden_forsecurity:27017] on first connect
    at Pool.<anonymous> (/Users/max/Local Server/parse/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/max/Local Server/parse/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/max/Local Server/parse/node_modules/mongodb-core/lib/connection/connection.js:172:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
  name: 'MongoError',
  message: 'failed to connect to server [hidden_forsecurity:27017] on first connect' } name=MongoError, message=failed to connect to server [hidden_forsecurity:27017] on first connect
```

I am running a local parse server on machine and connecting to online Mongo DB.

**Comment by talkaboutdesign** [comment]
The mongo error is fixed but here is the actual log when object is being saved. 

```
verbose: REQUEST for [POST] /parse/classes/Posts: {
  "featuredPick": false,
  "imageWidth": 0,
  "image_url": "https://d13yacurqjgara.cloudfront.net/users/58267/screenshots/3006508/bushwick-tea-wrapper.jpg",
  "badge": "Dribbble",
  "day": {
    "__type": "Date",
    "iso": "2016-10-05T20:00:27.291Z"
  },
  "live": true,
  "source_url": "https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper",
  "submittedBy": {
    "__type": "Pointer",
    "className": "_User",
    "objectId": "kC4EoOYFHc"
  },
  "imageHeight": 0,
  "tagline": "Bushwick Tea Wrapper",
  "short_url": "https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper",
  "name": "Bushwick Tea Wrapper"
} method=POST, url=/parse/classes/Posts, host=localhost:1337, x-parse-client-version=i1.14.2, accept=*/*, x-parse-application-id=IUx8N4zQ272hYJJQCrhx, x-parse-installation-id=a3e361e2-165a-4717-a3b5-b88dee20528a, accept-encoding=gzip, deflate, x-parse-os-version=10.0 (16A323), accept-language=en-us, content-type=application/json; charset=utf-8, content-length=548, user-agent=Design%20Hunt/1 CFNetwork/808.0.2 Darwin/16.0.0, connection=keep-alive, x-parse-app-build-version=1, x-parse-app-display-version=3.0, featuredPick=false, imageWidth=0, image_url=https://d13yacurqjgara.cloudfront.net/users/58267/screenshots/3006508/bushwick-tea-wrapper.jpg, badge=Dribbble, __type=Date, iso=2016-10-05T20:00:27.291Z, live=true, source_url=https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper, __type=Pointer, className=_User, objectId=kC4EoOYFHc, imageHeight=0, tagline=Bushwick Tea Wrapper, short_url=https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper, name=Bushwick Tea Wrapper
Before Save is called
<Buffer ff d8 ff ec 00 11 44 75 63 6b 79 00 01 00 04 00 00 00 50 00 00 ff ee 00 0e 41 64 6f 62 65 00 64 c0 00 00 00 01 ff db 00 84 00 02 02 02 02 02 02 02 02 ... >
Image is 800x600.
[ '#e7e1e2', '#2b3239', '#aa6d67', '#868da0', '#929ca9' ]
object
info: beforeSave triggered for Posts for user undefined:
  Input: {"featuredPick":false,"imageWidth":800,"image_url":"https://d13yacurqjgara.cloudfront.net/users/58267/screenshots/3006508/bushwick-tea-wrapper.jpg","badge":"Dribbble","day":{"__type":"Date","iso":"2016-10-05T20:00:27.291Z"},"live":true,"source_url":"https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper","submittedBy":{"__type":"Pointer","className":"_User","objectId":"kC4EoOYFHc"},"imageHeight":600,"tagline":"Bushwick Tea Wrapper","short_url":"https://dribbble.com/shots/3006508-Bushwick-Tea-Wrapper","name":"Bushwick Tea Wrapper","colors":["#e7e1e2","#2b3239","#aa6d67","#868da0","#929ca9"]}
  Result: "Object Saved" className=Posts, triggerType=beforeSave, user=undefined

After Save Called
```

I am setting image width, height, and colors from the image. Notice they are all there in the object log but the database entry is missing them.

**Comment by jtanori** [comment]
Could you provide a code snippet?

**Comment by zingano** [comment]
I am seeing this on 2.2.24. The function below is executed and the reference string is correct, but the job does not have the referenceString or version set after the function is called.

```
Parse.Cloud.beforeSave("Job", function(request, response) {

    if (!request.object.isNew()) {
        response.success({});
        return;
    }

    var theJob = request.object;

    if (!theJob.has("account")) {
        response.error("You may not save a job without setting its owning account");
        return;
    }

    var theAccount = theJob.get("account");
    var theCustomer;
    // Note do need to fetch Account here to access its customer
    return theAccount.fetch({useMasterKey: true}).then(function(account) {

        theCustomer = account.get("customer");
        return theCustomer.fetch({useMasterKey: true});

     }).then(function() {

        theCustomer.increment('lifetimeJobCount',1);
        return theCustomer.save(null,{useMasterKey: true});

    }).then(function() {

        var refString = theCustomer.get("referenceString") + "/" + theCustomer.get("lifetimeJobCount")
        console.log('DEBUG got ref string ' + refString);
        theJob.set("referenceString",refString);
        theJob.set('version',2);

        var AdminApp = Parse.Object.extend("AdminApp");
        var query = new Parse.Query(AdminApp);

        return query.first({useMasterKey: true});

    }).then(function(adminApp) {

            adminApp.increment('numberOfJobs',1);
            return adminApp.save(null,{useMasterKey: true});

    }).then(function() {

        response.success({});

    },function(error){

        logger.log("beforeSave Job: FAIL" + JSON.stringify(error));
        response.error(error);
    });
});
```

**Comment by zingano** [comment]
Found it - returning {} in response.success was blatting the values.
