### ISSUE TITLE
Enhance query capabilities when using Postgres

### ISSUE THREAD

**Issue by kulshekhar** [parse-community/parse-server#2877]
Postgres allows additional types of queries that aren't currently exposed by the database adapter (for example - getting distinct values, executing a transaction, setting a per transaction consistency level and a whole lot more)

It would be great if Parse Server can allow users to execute queries such as these when used with Postgres.

**Comment by kulshekhar** [comment]
I'm willing to start working on this but I'm not that well acquainted with the entire codebase. 

If someone can provide pointers on where to start, what gotchas to be aware of and how not to break the Mongo side of things, it would be very helpful

**Comment by flovilmart** [comment]
I'm not sure we want to focus on having different interfaces depending on the storage engine. Transactions would be nice to ensure consistency during the writes, the distinct value would also work in mongo db through an aggregation.

**Comment by kulshekhar** [comment]
Is it currently possible to extend the routes handled by parse server in a manner that would allow the new handlers to use the existing mechanism for authenticating and sanitizing requests?

**Comment by flovilmart** [comment]
That would require to add some 'feature support' mechanisms into the adapters, in order to abstract the support in both adapters. 

Before going to far ahead with Postgres, I believe we should also solidify the existant code. Some tests are failing in the CI, others are disabled etc...

**Comment by kulshekhar** [comment]
In that case, if someone can guide me in implementing one test case, I would hopefully be able to help bring the existing Postgres related code base up to scratch.

**Comment by lsxredrain** [comment]
name: 'error',
  length: 108,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '33',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3090',
  routine: 'errorMissingColumn' } error: column "password" does not exist
    at Connection.parseE (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js:                                                              539:11)
    at Connection.parseMessage (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connecti                                                              on.js:366:17)
    at Socket.<anonymous> (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js                                                              :105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
error: column "password" does not exist
    at Connection.parseE (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js:                                                              539:11)
    at Connection.parseMessage (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connecti                                                              on.js:366:17)
    at Socket.<anonymous> (/data/work/psql-parser/parse-server-example/node_modules/pg/lib/connection.js                                                              :105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

**Comment by kulshekhar** [comment]
With the recent improvement in Postgres support, is it a good time to start a discussion on how to extend parse server to fully utilize the capabilities of Postgres?

**Comment by flovilmart** [comment]
There is still 30 tests that are excluded with PG (6 are also excluded with mongo), maybe we can focus on drilling those down before expanding query capabilities?

**Comment by kulshekhar** [comment]
Sure. Are all of these contained in `describe_only_db` blocks?

**Comment by flovilmart** [comment]
and also `it_excludes_db`

**Comment by kulshekhar** [comment]
got it. thanks!

**Comment by flovilmart** [comment]
Some won't probably fix, but others could very well fix 'easily'

**Comment by flovilmart** [comment]
One easy trick ton only run those, is to `return fit` in `it_excludes_db` the `describe_only_db` is supposedly to run tests that we know won't pass on purpose (and therefore don'T need a fix)

**Comment by kulshekhar** [comment]
Thanks for the tip :)
