### ISSUE TITLE
Errors are not thrown. Fails silently with a timeout

### ISSUE THREAD

**Issue by srameshr** [parse-community/parse-server#3417]
Describe your issue in as much detail as possible.

Semantic error are not thrown. Before upgrading to Parse Version 2.3.1 it used to throw for both syntax and semantic errors.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

```
var userQuery = new Parse.Query("User");
userQueryMispelledHa.first().then(success, failure)
```

I am purposefully misspelling the variable and the parse server does not throw any errors. It just stays silent and eventually the request fails with a timeout error on the client.

#### Expected Results

Throw error

#### Actual Outcome

[FILL THIS OUT]

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     Ubuntu on Digital Ocean
  - Hardware:             
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: 3.1
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc):  Digital Ocean / Localhost

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

**Comment by alexandreprado** [comment]
I'm facing the same issue. Is there any workaround? 

Thanks!

**Comment by srameshr** [comment]
@alexandreprado Nope! This bug is mounting my dev and testing time.

**Comment by flovilmart** [comment]
We actually have a test covering that use case [here](https://github.com/parse-community/parse-server/blob/master/spec/CloudCode.spec.js#L61)

And this is what gets printed in the console:
```
ReferenceError: foo is not defined
    at /Users/florent/src/Parse/parse-server/spec/CloudCode.spec.js:64:7
    at /Users/florent/src/Parse/parse-server/src/Routers/FunctionsRouter.js:163:9
    at handleCloudFunction (/Users/florent/src/Parse/parse-server/src/Routers/FunctionsRouter.js:125:14)
    at /Users/florent/src/Parse/parse-server/src/PromiseRouter.js:153:7
    at Layer.handle [as handle_request] (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:281:22
    at param (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:317:13)
    at /Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/index.js:275:10)
    at handleParseHeaders (/Users/florent/src/Parse/parse-server/src/middlewares.js:146:5)
    at Layer.handle [as handle_request] (/Users/florent/src/Parse/parse-server/node_modules/express/lib/router/layer.js:95:5)
```
