### ISSUE TITLE
Error AdaptableController.js

### ISSUE THREAD

**Issue by tru3d3v** [parse-community/parse-server#3715]
Hi,

I got error when i run parse-server with express

/home/APP/test2/myapp/node_modules/parse-server/lib/Controllers/AdaptableController.js:31
var _adapter = Symbol();
               ^
ReferenceError: Symbol is not defined
    at Object.<anonymous> (/home/APP/test2/myapp/node_modules/parse-server/lib/Controllers/AdaptableController.js:31:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/APP/test2/myapp/node_modules/parse-server/lib/Controllers/LoggerController.js:12:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

**Comment by acinader** [comment]
@tru3d3v can you please take a look at the template for opening a bug: https://github.com/parse-community/parse-server#support

We'd love to help, but there is not enough information here.   Likely you are using an unsupported version of Node (i.e. pre Node 4.6).

I'm going to close pending more information, but feel free to re-open with a completed template.
