### ISSUE TITLE
Update Schema with many fields throw TypeError

### ISSUE THREAD

**Issue by paulovitin** [parse-community/parse-server#3737]
### Update Schema with many fields throw a TypeError

When you has a Schema with some fields, and then you try to update the Schema with many fields, the SchemaController throw a TypeError.

### Steps to reproduce

Consider this use case in test. I have a object with single field, then need add another 19 fields, so I resolve use the method updateClass.

```javascript
// Schema.spec.js
it('can update classes without needing an object', done => {
    const levelPermissions = {
      find: { '*': true },
      get: { '*': true },
      create: { '*': true },
      update: { '*': true },
      delete: { '*': true },
      addField: { '*': true },
    };
    config.database.loadSchema()
      .then(schema => {
        schema.validateObject('NewClass', { foo: 2 })
          .then(() => schema.reloadData())
          .then(() => schema.updateClass('NewClass', {
            fooOne: {type: 'Number'},
            fooTwo: {type: 'Array'},
            fooThree: {type: 'Date'},
            fooFour: {type: 'Object'},
            fooFive: {type: 'Relation', targetClass: '_User' },
            fooSix: {type: 'String'},
            fooSeven: {type: 'Object' },
            fooEight: {type: 'String'},
            fooNine: {type: 'String'},
            fooTeen: {type: 'Number' },
            fooEleven: {type: 'String'},
            fooTwelve: {type: 'String'},
            fooThirteen: {type: 'String'},
            fooFourteen: {type: 'String'},
            fooFifteen: {type: 'String'},
            fooSixteen: {type: 'String'},
            fooEighteen: {type: 'String'},
            fooNineteen: {type: 'String'},
          }, levelPermissions, config.database))
          .then(actualSchema => {
            const expectedSchema = {
              className: 'NewClass',
              fields: {
                objectId: { type: 'String' },
                updatedAt: { type: 'Date' },
                createdAt: { type: 'Date' },
                ACL: { type: 'ACL' },
                foo: { type: 'Number' },
                fooOne: {type: 'Number'},
                fooTwo: {type: 'Array'},
                fooThree: {type: 'Date'},
                fooFour: {type: 'Object'},
                fooFive: {type: 'Relation', targetClass: '_User' },
                fooSix: {type: 'String'},
                fooSeven: {type: 'Object' },
                fooEight: {type: 'String'},
                fooNine: {type: 'String'},
                fooTeen: {type: 'Number' },
                fooEleven: {type: 'String'},
                fooTwelve: {type: 'String'},
                fooThirteen: {type: 'String'},
                fooFourteen: {type: 'String'},
                fooFifteen: {type: 'String'},
                fooSixteen: {type: 'String'},
                fooEighteen: {type: 'String'},
                fooNineteen: {type: 'String'},
              },
              classLevelPermissions: { ...levelPermissions },
            };

            expect(dd(actualSchema, expectedSchema)).toEqual(undefined);
            done();
          })
          .catch(error => {
            // output the error
            console.log(error);
            done();
            fail('Error creating class: ' + JSON.stringify(error));
          });
      });
  });
```

#### Expected Results

I expect the schema has change with success.

#### Actual Outcome

The output log: 

```log
TypeError: Cannot read property 'type' of undefined
    at dbTypeMatchesObjectType (/.../parse-server/src/Controllers/SchemaController.js:296:7)
    at /.../parse-server/src/Controllers/SchemaController.js:643:14
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

### Environment Setup

- **Server**
  - parse-server version: 2.3.8
  - Operating System: macOs
  - Localhost or remote server?: Localhost tests

- **Database**
  - PostgreSQL version: 9.6
  - Localhost or remote server?: Localhost tests

**Comment by paulovitin** [comment]
I believe which the problem is Async promises operations, like this https://github.com/parse-community/parse-server/issues/3734 issue

**Comment by flovilmart** [comment]
Yeah most likely, I haven't had the time to fully review the PR but I'll be on it before eow

**Comment by paulovitin** [comment]
@flovilmart thats it. When the field is created, before this the field will be added in the Schema, so in this moment, some other update occurs and override this schema.

I make some tests and I check the field is in database, but no in the schema.

So, I did make some changes in the PostgresAdapter and I believe have the fix for this.

I'm waiting for the tests to run.

**Comment by paulovitin** [comment]
@flovilmart when we will see the new release of parse-server?

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/3740
