### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by asheludchenko** [parse-community/parse-server#3772]
### Issue Description

Everything worked well all the time, had no problems. Now the server is crashing all the time. 

### Environment Setup

- **Server**
  - parse-server version 2.3.8
  - Heroku

- **Database**
  - MongoDB version: 3.2.11
  - mLab

### Logs/Trace

/app/node_modules/parse-server/lib/ParseServer.js:460
2017-05-03T12:47:16.628284+00:00 app[web.1]:             throw err;
2017-05-03T12:47:16.628285+00:00 app[web.1]:             ^
2017-05-03T12:47:16.628285+00:00 app[web.1]: 
2017-05-03T12:47:16.628286+00:00 app[web.1]: Error: certificate has expired: 2017-05-03T11:46:01.000Z
2017-05-03T12:47:16.628287+00:00 app[web.1]:     at validateCredentials (/app/node_modules/apn/lib/credentials/validate.js:12:9)
2017-05-03T12:47:16.628287+00:00 app[web.1]:     at /app/node_modules/apn/lib/connection.js:163:5
2017-05-03T12:47:16.628287+00:00 app[web.1]:     at _fulfilled (/app/node_modules/q/q.js:854:54)
2017-05-03T12:47:16.628290+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/q/q.js:883:30)
2017-05-03T12:47:16.628291+00:00 app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:816:13)
2017-05-03T12:47:16.628291+00:00 app[web.1]:     at /app/node_modules/q/q.js:624:44
2017-05-03T12:47:16.628292+00:00 app[web.1]:     at runSingle (/app/node_modules/q/q.js:137:13)
2017-05-03T12:47:16.628292+00:00 app[web.1]:     at flush (/app/node_modules/q/q.js:125:13)
2017-05-03T12:47:16.628293+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:73:7)
2017-05-03T12:47:16.628293+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-05-03T12:47:16.646352+00:00 app[web.1]: 
2017-05-03T12:47:16.649257+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-05-03T12:47:16.649570+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-05-03T12:47:16.649809+00:00 app[web.1]: npm ERR! node v7.9.0
2017-05-03T12:47:16.650012+00:00 app[web.1]: npm ERR! npm  v4.2.0
2017-05-03T12:47:16.650214+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-05-03T12:47:16.650414+00:00 app[web.1]: npm ERR! errno 7
2017-05-03T12:47:16.650581+00:00 app[web.1]: npm ERR! parse-server-example@1.4.0 start: `node index.js`
2017-05-03T12:47:16.650726+00:00 app[web.1]: npm ERR! Exit status 7
2017-05-03T12:47:16.650896+00:00 app[web.1]: npm ERR! 
2017-05-03T12:47:16.651047+00:00 app[web.1]: npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
2017-05-03T12:47:16.651192+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-05-03T12:47:16.651351+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the parse-server-example package,
2017-05-03T12:47:16.651499+00:00 app[web.1]: npm ERR! not with npm itself.
2017-05-03T12:47:16.651652+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-05-03T12:47:16.651803+00:00 app[web.1]: npm ERR!     node index.js
2017-05-03T12:47:16.651952+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-05-03T12:47:16.652106+00:00 app[web.1]: npm ERR!     npm bugs parse-server-example
2017-05-03T12:47:16.652251+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-05-03T12:47:16.652423+00:00 app[web.1]: npm ERR!     npm owner ls parse-server-example
2017-05-03T12:47:16.652569+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-05-03T12:47:16.686266+00:00 app[web.1]: 
2017-05-03T12:47:16.686538+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-05-03T12:47:16.686682+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-05-03T12_47_16_657Z-debug.log

**Comment by flovilmart** [comment]
You need to renew your certificate APNS: `Error: certificate has expired: 2017-05-03T11:46:01.000Z`.

The [apn](https://www.npmjs.com/package/apn) library validates all certificates on startup, we don't control that, if you feel this is not the intended behaviour, your should open an issue [here](https://github.com/node-apn/node-apn/issues)

**Comment by asheludchenko** [comment]
I'm so sorry for being an idiot! Thank you very much for help!

**Comment by flovilmart** [comment]
No problem :)
