### ISSUE TITLE
Creating a JobSchedule object results in an internal server error

### ISSUE THREAD

**Issue by AmrKafina** [parse-community/parse-server#3968]
### Issue Description

Trying to create a JobSchedule results in an internal server error

### Steps to reproduce

I'm trying to create a JobSchedule object by calling cloude_code/jobs as follows:

request
        .post(serverUrl + "cloud_code/jobs/")
        .set('X-Parse-Application-Id', appId)
        .set('X-Parse-Master-Key', masterKey)
        .set('Accept', 'application/json')
        .send(params)
        .then(successCallback, errorCallback);

with the parameters being:
{ jobName: "myJob" }

#### Expected Results

I would expect this to work correctly, but instead I keep getting an internal server error.

#### Actual Outcome

Looking at my server logs, the issue seems to be with validateJobSchedule in the cloudCodeRouter:

2017-06-28T12:25:09.183025+00:00 app[web.1]: TypeError: Cannot read property 'jobName' of undefined
2017-06-28T12:25:09.183026+00:00 app[web.1]:     at validateJobSchedule (/app/node_modules/parse-server/lib/Routers/CloudCodeRouter.js:42:19)
2017-06-28T12:25:09.183027+00:00 app[web.1]:     at createJob (/app/node_modules/parse-server/lib/Routers/CloudCodeRouter.js:95:7)
2017-06-28T12:25:09.183029+00:00 app[web.1]:     at <anonymous>
2017-06-28T12:25:09.183029+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
2017-06-28T12:25:09.183028+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/PromiseRouter.js:132:22

It looks like the request's isn't routed correctly? Or I am sending the requests incorrectly? I'm using superagent to send requests.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.0
  - Operating System:     mac os
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

2017-06-28T12:25:09.183025+00:00 app[web.1]: TypeError: Cannot read property 'jobName' of undefined
2017-06-28T12:25:09.183026+00:00 app[web.1]:     at validateJobSchedule (/app/node_modules/parse-server/lib/Routers/CloudCodeRouter.js:42:19)
2017-06-28T12:25:09.183027+00:00 app[web.1]:     at createJob (/app/node_modules/parse-server/lib/Routers/CloudCodeRouter.js:95:7)
2017-06-28T12:25:09.183029+00:00 app[web.1]:     at <anonymous>
2017-06-28T12:25:09.183029+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
2017-06-28T12:25:09.183028+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/PromiseRouter.js:132:22

**Comment by flovilmart** [comment]
Your request body is malformed and should be:

{ job_schedule: { jobName: ‘myJob’ } }

note that the schedule isn’t run by Parse server and you need to run them manually. You can check https://github.com/ampme/Parse-server-job-runner for an example

**Comment by AmrKafina** [comment]
Ah I see now, works as expected.Thanks a lot @flovilmart.
