### ISSUE TITLE
Seeing frequent "request aborted at IncomingMessage.onAborted" errors

### ISSUE THREAD

**Issue by woodardj** [parse-community/parse-server#3975]
I'm seeing a lot of these "request aborted" errors, which trigger dyno timeouts on Heroku.

Has anyone else seen these? Any suggestions on where to look to start tracking this down?

```
Error: request aborted at IncomingMessage.onAborted (/app/node_modules/parse-server/node_modules/raw-body/index.js:269:10) at emitNone (events.js:86:13) at IncomingMessage.emit (events.js:185:7) at abortIncoming (_http_server.js:283:11) at Socket.serverSocketCloseListener (_http_server.js:296:5) at emitOne (events.js:101:20) at Socket.emit (events.js:188:7) at TCP._handle.close [as _onclose] (net.js:498:12)
```
I would normally never post something so vague, but since it's in a parse-server dependency, I wanted to hear what others were seeing.

- **Server**
  - parse-server version 2.3.7
  - Heroku

- **Database**
  - MongoDB version: 3.2.11
  - mlab

Often in the logs, these are associated with odd/failed POST request to parse/classes endpoints. Here are a few examples:

```
29 Jun 2017 10:01:06.757 web.3 - - POST /parse/classes/TB_AppSettings - - - - ms
29 Jun 2017 10:01:06.757 web.3 - - Error: request aborted at IncomingMessage.onAborted (/app/node_modules/parse-server/node_modules/raw-body/index.js:269:10) at emitNone (events.js:86:13) at IncomingMessage.emit (events.js:185:7) at abortIncoming (_http_server.js:283:11) at Socket.serverSocketCloseListener (_http_server.js:296:5) at emitOne (events.js:101:20) at Socket.emit (events.js:188:7) at TCP._handle.close [as _onclose] (net.js:498:12)


» 29 Jun 2017 09:54:27.494 web.4 - - POST /parse/classes/TB_ReferenceObjects - - - - ms
» 29 Jun 2017 09:54:27.494 web.4 - - Error: request aborted at IncomingMessage.onAborted (/app/node_modules/parse-server/node_modules/raw-body/index.js:269:10) at emitNone (events.js:86:13) at IncomingMessage.emit (events.js:185:7) at abortIncoming (_http_server.js:283:11) at Socket.serverSocketCloseListener (_http_server.js:296:5) at emitOne (events.js:101:20) at Socket.emit (events.js:188:7) at TCP._handle.close [as _onclose] (net.js:498:12)
```

**Comment by flovilmart** [comment]
Seems that the TCP socket gets closed before the body can be fully parsed, any idea what SDK is yielding it?

**Comment by woodardj** [comment]
We just pushed out app updates with the following SDK versions (though we have clients in the wild with older versions, no doubt. I will update if this issue disappears after most have updated):

ios: 1.14.4, android: 1.13.3

I _suspect_ that it's iOS clients, but I can't prove it at this time.

**Comment by flovilmart** [comment]
Add a first layer in the front of parse that would log the request headers, that may help

**Comment by mtrezza** [comment]
Same issue here, I usually see a long running request before that.
As below with `service=55061ms`:
```
heroku router - - at=warning code=H28 desc="Client Connection Idle" method=POST path="/parse/classes/example" host=example.herokuapp.com request_id=example fwd="example" dyno=web.1 connect=0ms service=55061ms status=499 bytes=0 protocol=https High Response Time
app web.1 - - Error
app web.1 - - at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:269:10)
app web.1 - - at emitNone (events.js:105:13)
app web.1 - - at IncomingMessage.emit (events.js:207:7)
app web.1 - - at abortIncoming (_http_server.js:410:9)
app web.1 - - at socketOnClose (_http_server.js:404:3)
app web.1 - - at emitOne (events.js:120:20)
app web.1 - - at Socket.emit (events.js:210:7)
app web.1 - - at TCP._handle.close [as _onclose] (net.js:549:12)
```

**Comment by domenukk** [comment]
I've got the same issue using the latest Android SDK.

**Comment by tys-bradford** [comment]
Same issue here using only iOS 1.14.4. Any ideas?

**Comment by lxknvlk** [comment]
Same here. Parse server 2.7.4, that has only android clients from android sdk 1.16.7
