### ISSUE TITLE
TypeError: Cannot read property '__type' of null - Postgres Storage Adapter

### ISSUE THREAD

**Issue by bfjfm2** [parse-community/parse-server#4019]
Got following error, when we search User Class of certain usernames
```node.js
var options = {useMasterKey:true};
var emails = ["contact@xyz.com","contact@zyx.com"];    
var query = new Parse.Query(Parse.User);
    query.containedIn("username",emails);
    query.find(options).then(function(objects){
        contacts = objects;
       //Handle success
    },
    function (err){
        console.log("Search Contact Error :" +err);
       //Handle Failure 
        }
    );

Error generating response. TypeError: Cannot read property '__type' of null

    2017-07-16T17:20:52.417Z - Uncaught internal server error. TypeError: Cannot read property '__type' of null
    at transformValue (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:102:90)
    at Array.map (native)
    at buildWhereClause (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:523:19)
    at PostgresStorageAdapter.find (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1239:19)
    at /app/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7) TypeError: Cannot read property '__type' of null
    at transformValue (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:102:90)
    at Array.map (native)
    at buildWhereClause (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:523:19)
    at PostgresStorageAdapter.find (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1239:19)
    at /app/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)

**Comment by dplewis** [comment]
Can you post the logs when running with VERBOSE=1?

**Comment by bfjfm2** [comment]
@dplewis posted and thanks in advance
```node.js
2017-07-16T17:20:52.417Z - Uncaught internal server error. TypeError: Cannot read property '__type' of null
    at transformValue (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:102:90)
    at Array.map (native)
    at buildWhereClause (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:523:19)
    at PostgresStorageAdapter.find (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1239:19)
    at /app/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7) TypeError: Cannot read property '__type' of null
    at transformValue (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:102:90)
    at Array.map (native)
    at buildWhereClause (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:523:19)
    at PostgresStorageAdapter.find (/app/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1239:19)
    at /app/node_modules/parse-server/lib/Controllers/DatabaseController.js:1007:36
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)

**Comment by dplewis** [comment]
Your log should look like this
```
verbose: REQUEST for [GET] /1/classes/_User: {
  "where": {},
  "include": "field",
  "keys": "field"
} method=GET, url=/1/classes/TestObject, user-agent=node-XMLHttpRequest, Parse/js1.10.0 (NodeJS 7.4.0), accept=*/*, content-type=text/plain, host=localhost:8378, content-length=194, connection=close, , include=field, keys=field
verbose: RESPONSE from [GET] /1/classes/TestObject: {
  "response": {
    "results": []
  }
} 
```

Looking at your query I don't know what `emails` or `options` are.

**Comment by bfjfm2** [comment]
@dplewis  I have updated emails and option. Same code working fine for MongoDB.

**Comment by dplewis** [comment]
I wrote a test case and its working fine. Can you run this test case?
https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md

You can put it in spec/ParseQuery.spec.js

And run `PARSE_SERVER_TEST_DB=postgres PARSE_SERVER_LOG_LEVEL=debug npm test spec/ParseQuery.spec.js`

```
it("get emails", (done) => {
    const emails = ["contact@xyz.com", "contact@zyx.com"];
    const options = { useMasterKey: true };
    const user = new Parse.User();
    user.setUsername(emails[0]);
    user.setPassword("asdf");
    user.signUp().then(() => {
      const query = new Parse.Query(Parse.User);
      query.containedIn("username", emails);
      return query.find(options);
    }).then((results) => {
      equal(results.length, 1);
      done();
    }, done.fail);
  });
```

**Comment by bfjfm2** [comment]
@dplewis Thanks, Diamond. But I am not an experienced server-side developer. I will try and reply.

**Comment by bfjfm2** [comment]
@dplewis I am not sure, how to run this test case. It is happening in Postgres DB but not in Mongo DB.

**Comment by dplewis** [comment]
@bfjfm2 Maybe its some other query thats causing the issue. Can you send me that file in an email? findlewis@gmail.com

**Comment by bfjfm2** [comment]
@dplewis Great! Thank you so much for identifying the issue. For now, I will check and skip null values in the email array.
