### ISSUE TITLE
Use utf8mb4

### ISSUE THREAD

**Issue by ggamzzak** [parse-community/parse-server#4032]
I'm using parse-server with utf8. I want to send with a emoji at message, but parse-server output error message and down.

```
warning: error while sending push TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:576:21)
    at fromString (buffer.js:113:26)
    at new Buffer (buffer.js:58:12)
    at new Device (/usr/lib/node_modules/parse-server/node_modules/apn/lib/device.js:13:16)
    at /usr/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/lib/APNS.js:169:23
    at Array.forEach (native)
    at APNS.send (/usr/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/lib/APNS.js:155:11)
    at _loop (/usr/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/lib/ParsePushAdapter.js:114:38)
    at ParsePushAdapter.send (/usr/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/lib/ParsePushAdapter.js:120:9)
```

Is it convert from utf8 to utf8mb4?
Are there another solutions?
Help me plz~

**Comment by ggamzzak** [comment]
solution!

/usr/lib/node_modules/parse-server/node_modules/apn/lib/device.js line:13

this.token = new Buffer(deviceToken.replace(/[^0-9a-f]/gi, ""), "hex");
to
this.token = new Buffer(deviceToken.replace(/[^0-9a-f]/gi, ""), "utf-8");

^^
