### ISSUE TITLE
parse-server-push-adapter 2.0.0 with parse-server 2.5.3 fails to start on AWS

### ISSUE THREAD

**Issue by kagayat** [parse-community/parse-server#4043]
Doing clean install on Amazon EB. Node version is 4.4.6, npm version is 2.15.5

App is supposed to start with "npm install && node index.js".

App fails to start, seeing this in the log:

/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/protocol/endpoint.js:17
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)

No issue whatsoever running the same "npm install && node index.js" on localhost (Mac).

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.5.3
  - Operating System:     Linux 4.4.14-24.50.amzn1.x86_64
  - Hardware:             AWS t2.small instance
  - Localhost or remote server? AWS

- **Database**

### Logs/Trace

/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/protocol/endpoint.js:17
const CLIENT_PRELUDE = Buffer.from("PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n");
                              ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)

npm ERR! Linux 4.4.14-24.50.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/npm" "start"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! doofl-parse-server@1.1.0 start: `npm install && node index.js`
npm ERR! Exit status 1

**Comment by kagayat** [comment]
apn version is 2.1.5

**Comment by montymxb** [comment]
@kagayat it looks like your node version is [too low](https://github.com/parse-community/parse-server/blob/master/package.json#L81). Parse Server requires at least node version **4.6** to run, any lower and you'll start getting syntax errors regarding language features that don't exist yet.

If you're not sure _which_ particular node version to upgrade to, I would recommend jumping up to the **6.X** or **7.X** lines, not only are these newer but they're also what [we test against for each release](https://github.com/parse-community/parse-server/blob/master/.travis.yml#L4).
