### ISSUE TITLE
Customize generation of objectId for a custom class?

### ISSUE THREAD

**Issue by vshy108** [parse-community/parse-server#4363]
Is it possible to modify the way to generate objectId for custom class instead of the auto generate 10 pseudo random 10 character string? Is it possible to have more than 10 characters objectId? thanks

**Comment by flovilmart** [comment]
What would be your use case?

**Comment by milesrichardson** [comment]
I also wanted to increase the length of objectIds. My use case is simply to make brute forcing attempts more difficult.

There is an undocumented config option `objectIdSize` which is set to 10 by default. The only hard coded reference I could find to objectId being 10 is in [SchemaController L140](https://github.com/parse-community/parse-server/blob/4bccf96ae79bad07b0dfbce16a41e76305da7ebc/src/Controllers/SchemaController.js#L140): `const userIdRegex = /^[a-zA-Z0-9]{10}$/;`

I haven't set CLP yet but it looks like this would cause problems with setting CLP to a userID.

@flovilmart Could you comment on why the config option is undocumented, and what side effects we should expect from changing the objectId size? Maybe that `userIdRegex` should be changed to reference the config value instead of hard coding 10?

**Comment by flovilmart** [comment]
That’s an omission, and should be fixed in a subsequent PR.

**Comment by milesrichardson** [comment]
Thanks. But could you please clarify what exactly is the omission? Is it the undocumented config, or the lack of an error when setting CLP with a 40 character userID?

**Comment by flovilmart** [comment]
I would say both, that we have a regex clearly not failing, and not documenting the option.

**Comment by addisonElliott** [comment]
I believe there is a bug with the Postgres storage adapter and objectID's greater than 10.

If you look at [PostgresStorageAdapter#L28](https://github.com/parse-community/parse-server/blob/4bccf96ae79bad07b0dfbce16a41e76305da7ebc/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L28), the `Pointer` postgres type is set to `char(10)`. The 10 is hardcoded for length-10 object IDs but this will need to be dependent on the objectIdSize.

**Comment by montymxb** [comment]
Hmmm, we'll want to open a PR for these issues soon and add some in-depth tests to make sure we don't have any issues with variable objectId field lengths, but in validation _and_ in storage (postgres).

**Comment by johndoehelloworld** [comment]
I tried setting "objectIdSize", but the server crashed with the following error:

`error: Error generating response. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
error: Uncaught internal server error. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
error: Error generating response. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
error: Uncaught internal server error. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
error: Error generating response. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
error: Uncaught internal server error. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
error: Error generating response. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
error: Uncaught internal server error. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
error: Error generating response. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
error: Uncaught internal server error. TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
Parse.Cloud.createGroup(): Error
error: Failed running cloud function createGroup for user x45Zab1wtk with:
  Input: {}
  Error: {"code":141,"message":{"code":1}}
error: Error generating response. ParseError {
  code: 141,
  message: ParseError { code: 1, message: undefined } } code=141, code=1, message=undefined
error: ParseError { code: 1, message: undefined } code=141, code=1, message=undefined
TypeError: size must be a number >= 0
    at randomString (file/path/node_modules/parse-server/lib/cryptoUtils.js:39:41)
    at Object.newObjectId (file/path/node_modules/parse-server/lib/cryptoUtils.js:48:10)
    at RestWrite.setRequiredFieldsIfNeeded (file/path/node_modules/parse-server/lib/RestWrite.js:208:42)
    at Promise.resolve.then.then.then.then.then.then.then.then (file/path/node_modules/parse-server/lib/RestWrite.js:97:17)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

Works fine when I remove the objectIdSize config – thoughts?

**Comment by flovilmart** [comment]
It should be a number; what / how did you set this value?

**Comment by johndoehelloworld** [comment]
As an environment variable just as I add other configuration parameters while starting the server. Set it at 34.

**Comment by flovilmart** [comment]
This is why it’s not properly mapped as a number probably.

**Comment by johndoehelloworld** [comment]
You were right @flovilmart – typecasting worked. Thanks for your prompt response!
