### ISSUE TITLE
Saving PFFile with postgres: error: Invalid schema, expected `mongodb` or `mongodb+srv` Error: Invalid schema, expected `mongodb` or `mongodb+srv`

### ISSUE THREAD

**Issue by mindgrub-jkliphouse** [parse-community/parse-server#4597]
### Issue Description

Using postgres instead of mongodb.  Try to save a PFFile on and get this error:

`error: Invalid schema, expected mongodb or mongodb+srv Error: Invalid schema, expected mongodb or mongodb+srv`

I'm saving an object as such:

`newObject.save({
    photo: new Parse.File('myfile.txt', {base64: image}),
    ...
 }); `

Looking through GridStoreAdapter I see 

> /**
>                                               GridStoreAdapter
>                                               Stores files in Mongo using GridStore
>                                               Requires the database adapter to be based on mongoclient
>                                              
>                                                weak
>                                               */

I don't see a postgres client.  Does this mean we can't save PFFiles if we're using postgres?   I've used mongodb but wanted to try postgres.

### Steps to reproduce

Use postgres and try to save a PFFile.

#### Expected Results

You can save PFFiles using postgres

#### Actual Outcome

I get the above error.

### Environment Setup

- **Server**
  - "^2.7.2",
  - happens locally on mac and on heroku

- **Database**
  - MongoDB version: None
  - Heroku postgres and postgres for mac

### Logs/Trace

error: Invalid schema, expected `mongodb` or `mongodb+srv` Error: Invalid schema, expected `mongodb` or `mongodb+srv`
    at module.exports (/Users/user/node/project-server/node_modules/mongodb/lib/url_parser.js:15:21)
    at connect (/Users/user/node/project-server/node_modules/mongodb/lib/mongo_client.js:867:3)
    at connectOp (/Users/user/node/project-server/node_modules/mongodb/lib/mongo_client.js:253:3)
    at /Users/user/node/project-server/node_modules/mongodb/lib/utils.js:432:15
    at new Promise (<anonymous>)
    at executeOperation (/Users/user/node/project-server/node_modules/mongodb/lib/utils.js:416:10)
    at MongoClient.connect (/Users/user/node/project-server/node_modules/mongodb/lib/mongo_client.js:244:10)
    at Function.MongoClient.connect (/Users/user/node/project-server/node_modules/mongodb/lib/mongo_client.js:472:22)
    at GridStoreAdapter._connect (/Users/user/node/project-server/node_modules/parse-server/lib/Adapters/Files/GridStoreAdapter.js:27:54)
    at GridStoreAdapter.createFile (/Users/user/node/project-server/node_modules/parse-server/lib/Adapters/Files/GridStoreAdapter.js:35:17)
error: Could not store file. code=130, message=Could not store file.

**Comment by bohemima** [comment]
Have a look at https://github.com/parse-community/parse-server-fs-adapter instead of GridFsAdapter (which is default IIRC)

**Comment by mindgrub-jkliphouse** [comment]
Thank you!  That did the trick.
