### ISSUE TITLE
ParseQuery.findInBackground() returning with Internal Server Error exception

### ISSUE THREAD

**Issue by gitjmo** [parse-community/parse-server#4649]
### Issue Description

Running the Parse Server Example deployment via Heroku which I haven't touched in 8 months.  This morning my android application started failing with Internal Server Error exception when trying to connect.

### Steps to reproduce

Basic server example deployment on Heroku and just attempting to look up a mongoDB record.

#### Expected Results

Expecting it to return with parse query results

#### Actual Outcome

Returns with exception error code 1: INTERNAL_SERVER_ERROR

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : latest pull per parse-server-example package.json
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? Heroku

- **Database**
  - MongoDB version: 3.2.15
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? mLab shared cluster

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by bohemima** [comment]
> Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by dplewis** [comment]
@gitjmo This issue has been resolved.

```
T17:21:45.945150+00:00 app[web.1]:     at Connection.messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
2018-03-15T17:21:45.945152+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
2018-03-15T17:21:45.945153+00:00 app[web.1]:     at Socket.emit (events.js:180:13)
2018-03-15T17:21:45.945155+00:00 app[web.1]:     at Socket.emit (domain.js:421:20)
2018-03-15T17:21:45.945157+00:00 app[web.1]:     at addChunk (_stream_readable.js:269:12)
2018-03-15T17:21:45.945159+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:256:11)
2018-03-15T17:21:45.945160+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:213:10)
2018-03-15T17:22:01.996590+00:00 heroku[router]: at=info method=POST path="/parse/classes/DropFilesByClassName" host=grexparse.herokuapp.com request_id=08311040-49e1-426a-807b-5aeb2db9f7da fwd="174.207.1.140" dyno=web.1 connect=1ms service=83ms status=500 bytes=588 protocol=http
2018-03-15T17:22:01.994534+00:00 app[web.1]:  [31merror [39m: Uncaught internal server error. { MongoError: not master and slaveOk=false
2018-03-15T17:22:01.994547+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2018-03-15T17:22:01.994549+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:200:36)
2018-03-15T17:22:01.994551+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
2018-03-15T17:22:01.994553+00:00 app[web.1]:     at Connection.messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
2018-03-15T17:22:01.994555+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
2018-03-15T17:22:01.994557+00:00 app[web.1]:     at Socket.emit (events.js:180:13)
2018-03-15T17:22:01.994559+00:00 app[web.1]:     at Socket.emit (domain.js:421:20)
2018-03-15T17:22:01.994560+00:00 app[web.1]:     at addChunk (_stream_readable.js:269:12)
2018-03-15T17:22:01.994562+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:256:11)
2018-03-15T17:22:01.994564+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:213:10)
2018-03-15T17:22:01.994566+00:00 app[web.1]:   name: 'MongoError',
2018-03-15T17:22:01.994568+00:00 app[web.1]:   message: 'not master and slaveOk=false',
2018-03-15T17:22:01.994570+00:00 app[web.1]:   ok: 0,
2018-03-15T17:22:01.994572+00:00 app[web.1]:   errmsg: 'not master and slaveOk=false',
2018-03-15T17:22:01.994574+00:00 app[web.1]:   code: 13435 } MongoError: not master and slaveOk=false
2018-03-15T17:22:01.994575+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2018-03-15T17:22:01.994577+00:00 app[web.1]:     at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:200:36)
2018-03-15T17:22:01.994579+00:00 app[web.1]:     at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
```

Recommended from MLab

The `not master and slaveOk=false` error message indicates that your application is trying to read/write to a Secondary node instead of the replica set's Primary.

Is your application using a replica set connection that can handle auto-failover (http://docs.mlab.com/connecting/#replica-set-connections)?

As a short-term fix, you can try to connect directly to your replica set's current Primary or initiate a failover (http://docs.mlab.com/ops/#failover).

**Comment by gitjmo** [comment]
Yes, thank you very much for your help and apologies for not closing the issue right away.  This came up the day before I was leaving on vacation.
