### ISSUE TITLE
when parse-server upgrade to 2.7.4 did't work,why?

### ISSUE THREAD

**Issue by dovewi** [parse-community/parse-server#4688]
```
#> parse-server-example@1.4.0 start /home/bae/app
#> node --harmony index.js
#/home/bae/app/.bae/node_modules/parse-server/lib/ParseServer.js:124
# const {
# ^
#SyntaxError: Unexpected token {
# at exports.runInThisContext (vm.js:53:16)
# at Module._compile (module.js:374:25)
# at Object.Module._extensions..js (module.js:417:10)
# at Module.load (module.js:344:32)
# at Function.Module._load (module.js:301:12)
# at Module.require (module.js:354:17)
# at require (internal/module.js:12:17)
# at Object.<anonymous> (/home/bae/app/.bae/node_modules/parse-server/lib/index.js:8:21)
# at Module._compile (module.js:410:26)
# at Object.Module._extensions..js (module.js:417:10)
#npm ERR! Linux 3.10.1-grsec
#npm ERR! argv "/home/admin/runtime/node/bin/node" "/home/admin/runtime/node/bin/npm" "start"
#npm ERR! node v4.2.6
#npm ERR! npm v2.14.12
```

**Comment by flovilmart** [comment]
Please use a more recent version of node JS. 8.11 for example.
