### ISSUE TITLE
query[key].$in.map is not a function

### ISSUE THREAD

**Issue by francocorreasosa** [parse-community/parse-server#4742]
### Issue Description / Steps to reproduce

Query the following from the JS SDK:
```js
export function allUserGroups() {
  const Group = Parse.Object.extend('Group');
  const query = new Parse.Query(Group);
  query.containedIn('users', Parse.User.current());

  return query;
}
```

Where **Group** has a `users` key that represents a `Relation<User>`

#### Expected Results
Users in the group.

#### Actual Outcome
500 Server Error.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.7.4
  - Operating System:    macOS High Sierra 10.13.3 (17D47)
  - Hardware:  MacBook Pro (Retina, 15-inch, Mid 2015)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: v3.4.4-build1
  - Storage engine:  Default / Not relevant
  - Hardware:  MacBook Pro (Retina, 15-inch, Mid 2015)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

#### HTTP Request
```
verbose: REQUEST for [GET] /api/classes/Group: {
  "where": {
    "users": {
      "$in": {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "Ua6YoYelyK"
      }
    }
  }
} method=GET, url=/api/classes/Group, host=localhost:3000, connection=keep-alive, content-length=288, origin=http://localhost:3001, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:3001/, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.9,es-419;q=0.8,es;q=0.7, __type=Pointer, className=_User, objectId=Ua6YoYelyK
error: Error generating response. TypeError: query[key].$in.map is not a function
    at Object.keys.map.constraintKey (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:697:44)
    at Array.map (<anonymous>)
    at Object.keys.map.key (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:691:43)
    at Array.map (<anonymous>)
    at DatabaseController.reduceInRelation (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:683:41)
    at then.then (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:885:194)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
error: Uncaught internal server error. TypeError: query[key].$in.map is not a function
    at Object.keys.map.constraintKey (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:697:44)
    at Array.map (<anonymous>)
    at Object.keys.map.key (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:691:43)
    at Array.map (<anonymous>)
    at DatabaseController.reduceInRelation (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:683:41)
    at then.then (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:885:194)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) TypeError: query[key].$in.map is not a function
    at Object.keys.map.constraintKey (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:697:44)
    at Array.map (<anonymous>)
    at Object.keys.map.key (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:691:43)
    at Array.map (<anonymous>)
    at DatabaseController.reduceInRelation (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:683:41)
    at then.then (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:885:194)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
TypeError: query[key].$in.map is not a function
    at Object.keys.map.constraintKey (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:697:44)
    at Array.map (<anonymous>)
    at Object.keys.map.key (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:691:43)
    at Array.map (<anonymous>)
    at DatabaseController.reduceInRelation (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:683:41)
    at then.then (/Users/franco/Code/parse-server-talk/server/node_modules/parse-server/lib/Controllers/DatabaseController.js:885:194)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by JacobJT** [comment]
`Parse.Query.containedIn` takes an array as the second parameter, you passed a single object. I suspect changing your call to `query.containedIn('users', [Parse.User.current()]);` will at least change the error you're getting. I don't know that `containedIn` is meant to be used with relations.

**Comment by francocorreasosa** [comment]
Ohh, you're right. What query may I use to filter by groups which the user is included in? Thanks a lot

**Comment by flovilmart** [comment]
You can probably just use `equalTo` if the `users` is an array. If it's a query that should also work. THis looks like exactly what is described in the docs: http://docs.parseplatform.org/js/guide/#using-parse-relations

**Comment by francocorreasosa** [comment]
Great, thanks!
