### ISSUE TITLE
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/parse-server#4760]
When I deploy parse server `2.7.4` on heroku I get a build error when installing bcrypt.

I think this might be caused because parse server still uses bcrypt `1.0.3` and it is not compatible with newer node version. Why do you not use bcrypt > `2.0`?

#### Expected Results

parse server does build without bcrypt error.

#### Actual Outcome

I see `node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz` in my build logs.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : `2.7.4`
  - Operating System: Heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

### Logs/Trace

```
-----> Apt app detected
-----> Reusing cache
-----> Updating apt caches
       Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
       Get:2 http://archive.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
       Get:3 http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease [46.4 kB]
       Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
       Get:5 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [625 kB]
       Get:6 http://apt.postgresql.org/pub/repos/apt xenial-pgdg/main amd64 Packages [160 kB]
       Get:7 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [439 kB]
       Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,002 kB]
       Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [807 kB]
       Fetched 3,295 kB in 1s (2,792 kB/s)
       Reading package lists...
-----> Fetching .debs for graphicsmagick
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         libgraphicsmagick-q16-3 libwebp5
       Suggested packages:
         graphicsmagick-dbg
       The following NEW packages will be installed:
         graphicsmagick libgraphicsmagick-q16-3 libwebp5
       0 upgraded, 3 newly installed, 0 to remove and 32 not upgraded.
       Need to get 0 B/1,859 kB of archives.
       After this operation, 8,987 kB of additional disk space will be used.
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
-----> Fetching .debs for libpng-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 32 not upgraded.
       Need to get 0 B/184 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
-----> Fetching .debs for zlib1g-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 32 not upgraded.
       Need to get 0 B/168 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
-----> Installing graphicsmagick_1.3.23-1build1_amd64.deb
-----> Installing libgraphicsmagick-q16-3_1.3.23-1build1_amd64.deb
-----> Installing libpng12-dev_1.2.54-1ubuntu1_amd64.deb
-----> Installing libwebp5_0.4.4-1_amd64.deb
-----> Installing zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4.1_amd64.deb
-----> Writing profile script
-----> Rewrite package-config files
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=false
-----> Installing binaries
       engines.node (package.json):  >=4.6
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=4.6...
       Downloading and installing node 10.1.0...
       Using default npm version: 5.6.0
-----> Restoring cache
       Skipping cache restore (disabled)
-----> Building dependencies
       Installing node modules (package.json)
       
       > parse-image@0.1.1 preinstall /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/parse-image
       > ./install.sh
       
       Found all dependencies
       
       > uws@9.148.0 install /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/uws
       > node-gyp rebuild > build_log.txt 2>&1 || exit 0
       
       
       > bcrypt@1.0.3 install /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt
       > node-pre-gyp install --fallback-to-build
       
       node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-linux-x64.tar.gz
       node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.3 and node@10.1.0 (node-v64 ABI) (falling back to source compile with node-gyp)
       make: Entering directory '/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/build'
       CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
       CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
       CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
       In file included from ../../nan/nan.h:192:0,
       from ../src/bcrypt_node.cc:1:
       ../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
       ../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
       return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
       ^
       In file included from ../src/bcrypt_node.cc:1:0:
       ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
       ../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       v8::Isolate::GetCurrent(), target, func, argc, argv);
       ^
       In file included from ../../nan/nan.h:49:0,
       from ../src/bcrypt_node.cc:1:
       /app/.node-gyp/10.1.0/include/node/node.h:172:50: note: declared here
       NODE_EXTERN v8::Local<v8::Value> MakeCallback(
       ^
       /app/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
       __attribute__((deprecated(message))) declarator
       ^
       In file included from ../src/bcrypt_node.cc:1:0:
       ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
       ../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       v8::Isolate::GetCurrent(), target, symbol, argc, argv);
       ^
       In file included from ../../nan/nan.h:49:0,
       from ../src/bcrypt_node.cc:1:
       /app/.node-gyp/10.1.0/include/node/node.h:165:50: note: declared here
       NODE_EXTERN v8::Local<v8::Value> MakeCallback(
       ^
       /app/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
       __attribute__((deprecated(message))) declarator
       ^
       In file included from ../src/bcrypt_node.cc:1:0:
       ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
       ../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       v8::Isolate::GetCurrent(), target, method, argc, argv);
       ^
       In file included from ../../nan/nan.h:49:0,
       from ../src/bcrypt_node.cc:1:
       /app/.node-gyp/10.1.0/include/node/node.h:158:50: note: declared here
       NODE_EXTERN v8::Local<v8::Value> MakeCallback(
       ^
       /app/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
       __attribute__((deprecated(message))) declarator
       ^
       In file included from ../src/bcrypt_node.cc:1:0:
       ../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
       ../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       ));
       ^
       In file included from ../../nan/nan.h:49:0,
       from ../src/bcrypt_node.cc:1:
       /app/.node-gyp/10.1.0/include/node/node.h:172:50: note: declared here
       NODE_EXTERN v8::Local<v8::Value> MakeCallback(
       ^
       /app/.node-gyp/10.1.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
       __attribute__((deprecated(message))) declarator
       ^
       bcrypt_lib.target.mk:97: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
       make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
       make: Leaving directory '/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/build'
       gyp ERR! build error
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
       gyp ERR! System Linux 4.4.0-1014-aws
       gyp ERR! command "/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/bin/node" "/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding"
       gyp ERR! cwd /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt
       gyp ERR! node -v v10.1.0
       gyp ERR! node-gyp -v v3.6.2
       gyp ERR! not ok
       node-pre-gyp ERR! build error
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/bin/node /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
       node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
       node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
       node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
       node-pre-gyp ERR! System Linux 4.4.0-1014-aws
       node-pre-gyp ERR! command "/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/bin/node" "/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
       node-pre-gyp ERR! cwd /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt
       node-pre-gyp ERR! node -v v10.1.0
       node-pre-gyp ERR! node-pre-gyp -v v0.6.36
       node-pre-gyp ERR! not ok
       Failed to execute '/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/bin/node /tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/tmp/build_e61e3ed6aa02ea3c1d489191d69c2fc3/node_modules/bcrypt/lib/binding' (1)
       added 470 packages in 29.557s
-----> Caching build
       Clearing previous node cache
       Skipping cache save (disabled by config)
-----> Pruning devDependencies
       Skipping because npm 5.6.0 sometimes fails when running 'npm prune' due to a known issue
       https://github.com/npm/npm/issues/19356
       
       You can silence this warning by updating to at least npm 5.7.1 in your package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 40.3M
-----> Launching...

```

**Comment by thewolf** [comment]
try with node 8
