### ISSUE TITLE
Version 2.8.0 Failing to deploy on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by iop280** [parse-community/parse-server#4770]
Since 2.8.0 was deployed, I'm having the following error with my deployments:

```
Application deployment failed at 2018-05-18T16:40:49Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.

...

> parse-server@2.8.0 postinstall /tmp/deployment/application/node_modules/parse-server
> node -p 'require("./postinstall.js")()'

module.js:471
throw err;
^

Error: Cannot find module './postinstall.js'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at [eval]:1:1
at ContextifyScript.Script.runInThisContext (vm.js:25:33)
at Object.runInThisContext (vm.js:97:38)
at Object.<anonymous> ([eval]-wrapper:6:22)
at Module._compile (module.js:570:32)
at evalScript (bootstrap_node.js:347:27)
```

**Comment by flovilmart** [comment]
Just published 2.8.1 should be good now. Let us know if there’s any issue.
