### ISSUE TITLE
Heroku Scheduler and Parse Server (Error : 100 XMLHttpRequest failed)

### ISSUE THREAD

**Issue by AlexisJamin** [parse-community/parse-server#4854]
Hello,

I added a scheduled-job.js file to my Parse Server to use the Heroku Scheduler. It seems I can't use Parse.Query since I have no user logged.  I tried two solutions (running the Query in scheduled-job.js file directly or using a Parse.Could function to run it) and I only get : "100 XMLHttpRequest failed: {}"

It perfectly works with Parse.Object :  

![capture d ecran 2018-06-27 a 14 43 25](https://user-images.githubusercontent.com/28752161/41974632-c6d73bb8-7a18-11e8-9a46-c18a7a6ac5c8.png)

But when I do (I added useMasterKey but does not work either with it) :  

![capture d ecran 2018-06-27 a 14 43 52](https://user-images.githubusercontent.com/28752161/41974691-edbf0512-7a18-11e8-99bf-5f923b14b548.png)

Or run the same function in Parse.Cloud directly : 

![capture d ecran 2018-06-27 a 14 42 44](https://user-images.githubusercontent.com/28752161/41974712-fe1ec334-7a18-11e8-9c9f-7901579b1d27.png)

I get :  
Error: 100 XMLHttpRequest failed: {}
2018-06-27T12:45:19.542497+00:00 app[web.1]: [32minfo[39m: Ran cloud function captureReservations for user undefined with:
2018-06-27T12:45:19.542500+00:00 app[web.1]:   Input: {}
2018-06-27T12:45:19.542502+00:00 app[web.1]:   Result: {"status":"100 XMLHttpRequest failed: {}"} functionName=captureReservations, , user=undefined
2018-06-27T12:45:19.542989+00:00 app[web.1]: [36mverbose[39m: RESPONSE from [POST] /parse/functions/captureReservations: {
2018-06-27T12:45:19.542991+00:00 app[web.1]:   "response": {
2018-06-27T12:45:19.542992+00:00 app[web.1]:     "result": {
2018-06-27T12:45:19.542994+00:00 app[web.1]:       "status": "100 XMLHttpRequest failed: {}"
2018-06-27T12:45:19.542995+00:00 app[web.1]:     }
2018-06-27T12:45:19.542996+00:00 app[web.1]:   }
2018-06-27T12:45:19.542998+00:00 app[web.1]: } status=100 XMLHttpRequest failed: {}

**Comment by AlexisJamin** [comment]
Thanks for your answer @flovilmart ! 

Since I don't have a JSKey, I tried : 

Parse.initialize(appID, masterKey, masterKey);

But it does not work either :/

**Comment by flovilmart** [comment]
You have to put `undefined` If you don’t have a JS key.

**Comment by flovilmart** [comment]
Also, just a note, no need to double post here if you posted on stackoverflow. Stackoverflow is usually the best way to get answers by the community for implementation details.

**Comment by AlexisJamin** [comment]
I know, but this forum is much more active. Did not get any answer on Stack unfortunately.

I tried with undefined, same error. I don't understand why when I do Parse.Object, it works (without useMasterKey!) and when I do a Parse.Query, it does not work with ou without useMasterKey ...

**Comment by flovilmart** [comment]
This is not a forum, this is to report issues with the server itself.

**Comment by AlexisJamin** [comment]
Maybe it's a bug. Can you help ?

**Comment by flovilmart** [comment]
it's unlikely to be a bug, more likely a bug in your code that prevents it to run correctly. In your code, we don't see the cloud function, perhaps there is a typo, or an error that is not correctly handled in your `Parse.Query`. I don't see `moment` defined either, this is perhaps that.

**Comment by AlexisJamin** [comment]
I'm running the exact same function in Parse.Cloud. It does not work with ou without useMasterKey ... 

![capture d ecran 2018-06-27 a 15 51 56](https://user-images.githubusercontent.com/28752161/41978416-1da40544-7a22-11e8-9a0b-1547cb72103a.png)

**Comment by flovilmart** [comment]
What is the further the function goes? Is it getting called at all? Did you try with promises? The backbone style callbacks are not recommended anymore.

```
query.find().then(function(result) {

}, function(error) {

});

**Comment by AlexisJamin** [comment]
Ok I simplified to test. Thanks again for helping me ! :-)

My scheduled-job.js file : 

![capture d ecran 2018-06-27 a 16 04 36](https://user-images.githubusercontent.com/28752161/41979242-e7b409c8-7a23-11e8-9087-48db7fef932d.png)

My Cloud/main.js file :  

![capture d ecran 2018-06-27 a 16 04 50](https://user-images.githubusercontent.com/28752161/41979261-f4323e18-7a23-11e8-9bec-d1e7b69140d3.png)



And I get the same error :  

```
[36mverbose[39m: REQUEST for [POST] /parse/functions/captureReservations: {} method=POST, url=/parse/functions/captureReservations, host=tiebreak.herokuapp.com, connection=close, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 10.5.0), accept=*/*, content-type=text/plain, x-request-id=2a7d873c-088f-49a5-9dbe-e7d8f682dfe1, x-forwarded-for=54.74.231.39, x-forwarded-proto=https, x-forwarded-port=443, via=1.1 vegur, connect-time=0, x-request-start=1530108159716, total-route-time=0, content-length=136, 
    2018-06-27T14:02:39.743488+00:00 app[web.1]: captureReservations
   2018-06-27T14:02:39.757064+00:00 app[web.1]: Error: 100 XMLHttpRequest failed: {}
   2018-06-27T14:02:39.758029+00:00 app[web.1]: [32minfo[39m: Ran cloud function captureReservations for user undefined with:
   2018-06-27T14:02:39.758031+00:00 app[web.1]:   Input: {}
   2018-06-27T14:02:39.758033+00:00 app[web.1]:   Result: {"status":"100 XMLHttpRequest failed: {}"} functionName=captureReservations, , user=undefined
   2018-06-27T14:02:39.758949+00:00 app[web.1]: [36mverbose[39m: RESPONSE from [POST] /parse/functions/captureReservations: {
   2018-06-27T14:02:39.758951+00:00 app[web.1]:   "response": {
   2018-06-27T14:02:39.758952+00:00 app[web.1]:     "result": {
   2018-06-27T14:02:39.758953+00:00 app[web.1]:       "status": "100 XMLHttpRequest failed: {}"
   2018-06-27T14:02:39.758954+00:00 app[web.1]:     }
   2018-06-27T14:02:39.758955+00:00 app[web.1]:   }
   2018-06-27T14:02:39.758956+00:00 app[web.1]: } status=100 XMLHttpRequest failed: {}
```

**Comment by AlexisJamin** [comment]
I changed to console.dir(error) but got the same :  

```
2018-06-27T14:28:13.458096+00:00 heroku[router]: at=info method=POST path="/parse/functions/captureReservations" host=tiebreak.herokuapp.com request_id=6e196009-c8da-4b98-b72a-29c1b3f03097 fwd="54.155.63.174" dyno=web.1 connect=0ms service=53ms status=200 bytes=535 protocol=http
2018-06-27T14:28:13.433589+00:00 app[web.1]: [36mverbose[39m: REQUEST for [POST] /parse/functions/captureReservations: {} method=POST, url=/parse/functions/captureReservations, host=tiebreak.herokuapp.com, connection=close, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 10.5.0), accept=*/*, content-type=text/plain, x-request-id=6e196009-c8da-4b98-b72a-29c1b3f03097, x-forwarded-for=54.155.63.174, x-forwarded-proto=http, x-forwarded-port=80, via=1.1 vegur, connect-time=0, x-request-start=1530109693403, total-route-time=0, content-length=136, 
2018-06-27T14:28:13.435021+00:00 app[web.1]: captureReservations
2018-06-27T14:28:13.456348+00:00 app[web.1]: ParseError { code: 100, message: 'XMLHttpRequest failed: {}' }
2018-06-27T14:28:13.457206+00:00 app[web.1]: [32minfo[39m: Ran cloud function captureReservations for user undefined with:
2018-06-27T14:28:13.457209+00:00 app[web.1]:   Input: {}
2018-06-27T14:28:13.457211+00:00 app[web.1]:   Result: {"status":"100 XMLHttpRequest failed: {}"} functionName=captureReservations, , user=undefined
2018-06-27T14:28:13.458795+00:00 app[web.1]: [36mverbose[39m: RESPONSE from [POST] /parse/functions/captureReservations: {
2018-06-27T14:28:13.458798+00:00 app[web.1]:   "response": {
2018-06-27T14:28:13.458799+00:00 app[web.1]:     "result": {
2018-06-27T14:28:13.458801+00:00 app[web.1]:       "status": "100 XMLHttpRequest failed: {}"
2018-06-27T14:28:13.458802+00:00 app[web.1]:     }
2018-06-27T14:28:13.458804+00:00 app[web.1]:   }
2018-06-27T14:28:13.458805+00:00 app[web.1]: } status=100 XMLHttpRequest failed: {}
`````

I have other Cloud functions which run perfectly with my React Native app. But user is defined contrary to this situation.

**Comment by flovilmart** [comment]
This means that the request has failed, triple check your serverURL, that it's accessible from wherever you're calling. If this is in Cloud Code, you should NEVER call `Parse.initialize()` and set `Parse.serverURL`, this is done for you when initializing parseServer.

**Comment by AlexisJamin** [comment]
Yes I did not `Parse.initialize()` in the Cloud main.js. Since my request works with Parse.Object, I don't understand how my serverURL would not be working. I use the same serverURL with my React Native app to use Parse.Cloud and it works perfectly. But my users are logged. 

Here I'm not logged, since it's a js file running from backend. That's why I get `"Ran cloud function captureReservations for user undefined"`. 

Here is my config, maybe it can help : 

![capture d ecran 2018-06-27 a 16 42 49](https://user-images.githubusercontent.com/28752161/41981449-3c57c992-7a29-11e8-9cdf-ebd331784e66.png)

![capture d ecran 2018-06-27 a 16 43 01](https://user-images.githubusercontent.com/28752161/41981462-42b5c460-7a29-11e8-9433-a88b7199e4a7.png)

**Comment by AlexisJamin** [comment]
I tested a again without changing serverURL with Parse Object in Cloud main.js and it works perfectly. The problem is related to the Parse.Query :  

![capture d ecran 2018-06-27 a 17 02 23](https://user-images.githubusercontent.com/28752161/41982534-fce4eee0-7a2b-11e8-984f-28c86c9888e4.png)



```
2018-06-27T15:01:27.930814+00:00 app[web.1]: [32minfo[39m: Ran cloud function captureReservations for user undefined with:
2018-06-27T15:01:27.930819+00:00 app[web.1]:   Input: {}
2018-06-27T15:01:27.930826+00:00 app[web.1]:   Result: {"type":"lesson","createdAt":"2018-06-27T15:01:27.899Z","updatedAt":"2018-06-27T15:01:27.899Z","objectId":"n2fSvGeI11","__type":"Object","className":"Reservation"} functionName=captureReservations, , user=undefined
2018-06-27T15:01:27.931226+00:00 app[web.1]: [36mverbose[39m: RESPONSE from [POST] /parse/functions/captureReservations: {
2018-06-27T15:01:27.931228+00:00 app[web.1]:   "response": {
2018-06-27T15:01:27.931230+00:00 app[web.1]:     "result": {
2018-06-27T15:01:27.931231+00:00 app[web.1]:       "type": "lesson",
2018-06-27T15:01:27.931233+00:00 app[web.1]:       "createdAt": "2018-06-27T15:01:27.899Z",
2018-06-27T15:01:27.931235+00:00 app[web.1]:       "updatedAt": "2018-06-27T15:01:27.899Z",
2018-06-27T15:01:27.931236+00:00 app[web.1]:       "objectId": "n2fSvGeI11",
2018-06-27T15:01:27.931237+00:00 app[web.1]:       "__type": "Object",
2018-06-27T15:01:27.931239+00:00 app[web.1]:       "className": "Reservation"
2018-06-27T15:01:27.931240+00:00 app[web.1]:     }
2018-06-27T15:01:27.931241+00:00 app[web.1]:   }
2018-06-27T15:01:27.931243+00:00 app[web.1]: } type=lesson, createdAt=2018-06-27T15:01:27.899Z, updatedAt=2018-06-27T15:01:27.899Z, objectId=n2fSvGeI11, __type=Object, className=Reservation
```

**Comment by flovilmart** [comment]
Yes, your cloud code is running but the query is responding with the XMLHTTPRequest error, which indicates that the parse-server may not be able to be reached.

As I mentioned before, we use github for issues with parse-server, for example a query that woudl return bad results etc... and not user code. In your case, I am sorry but I don't see how parse-server would be responsible for this issue. Did you try with a very simple query, and adding back more query parameters after? 

With your verbose logs, there is no indication that the query reached the server either, perhaps in the heroku logs you'll see the call to the server made.

Again, I won't be able to help further as to me, it's clearly not an issue with the server itself.

ALSO, is your query parameters are properly formatted, like the one that looks like a date. the JS SDK takes a **date** parameter, not a moment.

Try running this:

```
var Parse = require('parse/node');
var moment = require('moment');


var today = moment().subtract(1, 'hour')

var query = new Parse.Query('Reservation')
query.lessThan("start", today);
```

This will error with:

```
/Users/florent/src/Parse/parse-server/node_modules/moment/moment.js:807
            mom._d['get' + (mom._isUTC ? 'UTC' : '') + unit]() : NaN;
                                                            ^

TypeError: mom._d[(("get" + (intermediate value)(intermediate value)(intermediate value)) + unit)] is not a function
    at get (/Users/florent/src/Parse/parse-server/node_modules/moment/moment.js:807:61)
    at Object.year (/Users/florent/src/Parse/parse-server/node_modules/moment/moment.js:800:24)
    at Object.inspect (/Users/florent/src/Parse/parse-server/node_modules/moment/moment.js:3342:31)
    at formatValue (util.js:430:38)
    at formatProperty (util.js:831:11)
    at formatObject (util.js:647:17)
    at formatValue (util.js:609:18)
    at formatProperty (util.js:831:11)
    at formatObject (util.js:647:17)
    at formatValue (util.js:609:18)
```

Most probably the issue you're looking for...

**Comment by AlexisJamin** [comment]
OMG it was moment() indeed. Thanks a lot @flovilmart ! You saved me :-)
