### ISSUE TITLE
Cannot find module 'winston/lib/winston/common'

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/parse-server#4856]
### Issue Description

Upgraded Parse Server from 2.7.2 to 2.8.2. Now npm start fails with an error.

### Steps to reproduce

Run the npm start command, server does not start.

Tried deleting node_modules and reinstalling using npm install. Same error occurs when starting.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2
  - Operating System:     Ubuntu 16.04.4
  - Hardware:             Digital Ocean Droplet
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): DO

- **Database**
  - MongoDB version: MongoDB server version: 3.4.14
  - Storage engine:  Default
  - Hardware:        Same box as server
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): DO

### Logs/Trace

$ npm start

> parse-server-example@1.4.0 start /var/parse/parse-server
> node index.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'winston/lib/winston/common'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/parse/parse-server/node_modules/winston-daily-rotate-file/index.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

#### package.json

{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "0.0.24",
    "moment-timezone": "^0.5.21",
    "parse": "~1.8.0",
    "parse-server": "^2.8.2",
    "stripe": "^5.10.0",
    "underscore": "^1.9.1"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

**Comment by flovilmart** [comment]
Did you run ‘`npm install` 2.8.2 require also node 8+

**Comment by Vortec4800** [comment]
I did run `npm install`, part of my troubleshooting was deleting the node_modules and running install again from scratch.

I'm running node v8.11.3 and npm v6.1.0

**Comment by flovilmart** [comment]
And the installation completes properly without warnings?

**Comment by Vortec4800** [comment]
Here's the install log, it seemed okay to me:

$ npm install

> bcrypt@2.0.1 install /var/parse/parse-server/node_modules/parse-server/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/var/parse/parse-server/node_modules/parse-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> kerberos@0.0.24 install /var/parse/parse-server/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/var/parse/parse-server/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
../lib/kerberos.cc: In static member function ‘static void Kerberos::After(uv_work_t*)’:
../lib/kerberos.cc:948:50: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     worker->callback->Call(ARRAY_SIZE(info), info);
                                                  ^
In file included from ../lib/kerberos.h:9:0,
                 from ../lib/kerberos.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../lib/kerberos.cc:972:50: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     worker->callback->Call(ARRAY_SIZE(info), info);
                                                  ^
In file included from ../lib/kerberos.h:9:0,
                 from ../lib/kerberos.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
  CXX(target) Release/obj.target/kerberos/lib/worker.o
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:446:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
  CC(target) Release/obj.target/kerberos/lib/base64.o
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/var/parse/parse-server/node_modules/kerberos/build'

> parse-server@2.8.2 postinstall /var/parse/parse-server/node_modules/parse-server
> node -p 'require("./postinstall.js")()'


                  1111111111
               1111111111111111
            1111111111111111111111
          11111111111111111111111111
        111111111111111       11111111
       1111111111111             111111
      1111111111111   111111111   111111
      111111111111   11111111111   111111
     1111111111111   11111111111   111111
     1111111111111   1111111111    111111
     1111111111111111111111111    1111111
     11111111                    11111111
      111111         1111111111111111111
      11111   11111  111111111111111111
       11111         11111111111111111
        111111     111111111111111111
          11111111111111111111111111
            1111111111111111111111
              111111111111111111
                  11111111111


        Thanks for installing parse 🙏
  Please consider donating to our open collective
      to help us maintain this package.

  👉 https://opencollective.com/parse-server

  [             .....] \ prepare:parse-server-example: info lifecycle parse-servadded 424 packages from 379 contributors and audited 798 packages in 30.67s
found 20 vulnerabilities (5 low, 10 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by flovilmart** [comment]
Uhm yeah, and do you confirm the winston package is properly installed?

**Comment by flovilmart** [comment]
In the node_modules folder. Also, which version of Winston is installed, with `npm ls`

**Comment by Vortec4800** [comment]
Here's an interesting bit. `npm ls` is very long, but here is part that looks important:

│ ├─┬ UNMET PEER DEPENDENCY winston@2.4.1
│ │ ├── async@1.0.0
│ │ ├── colors@1.0.3
│ │ ├── cycle@1.0.3
│ │ ├── eyes@0.1.8
│ │ ├── isstream@0.1.2 deduped
│ │ └── stack-trace@0.0.10
│ ├─┬ winston-daily-rotate-file@1.7.2
│ │ └── mkdirp@0.5.1 deduped

**Comment by Vortec4800** [comment]
At the bottom it says:

npm ERR! peer dep missing: winston@2.x, required by winston-daily-rotate-file@1.7.2

**Comment by flovilmart** [comment]
Ok, so far it looks good that’s very odd. Can you double check wether the Winston folder has the right files also? In node_modules ?

**Comment by Vortec4800** [comment]
$ ls wi*

winston-daily-rotate-file:
index.js  LICENSE  package.json  README.md  test  test.js

**Comment by flovilmart** [comment]
uhm so there're no winston folder in node modules? very very stange... I have the exact same setup here and everything look good

**Comment by Vortec4800** [comment]
That's correct.

**Comment by flovilmart** [comment]
Can you try on a clean new setup / installation?

**Comment by Vortec4800** [comment]
I don't have an easy way to do that, I did wipe out the node_modules dir and install fresh from there.

I rolled back to 2.7.2 for now as I just had to get the server back up and running. I'm not sure what else I can try to fix this, seems like the peer dependency issue is causing it though.

**Comment by flovilmart** [comment]
AH! I was on mobile but didn't see your comment that stated: `UNMET PEER DEPENDENCY winston@2.4.1`

YES! add winston: 2.4.1 in your package.json and it should be good! What's odd is that winston is specified as a real dependency!....

SORRY!

**Comment by Vortec4800** [comment]
Okay, I'm going to try this next week - I can't bring the server down to try it until then. I'll update this thread when I try it and let you know if it worked.

**Comment by flovilmart** [comment]
Thanks!

**Comment by flovilmart** [comment]
And good luck!

**Comment by flovilmart** [comment]
@Vortec4800 any news?

**Comment by JacobJT** [comment]
I would try again this without any modifications to the package.json first - I know I mentioned on another thread but npm itself was having a ton of issues last week. On Friday I couldn't run `npm install` without errors (at the start of my debug process - unexpected missing packages), but on Monday with no changes on my end it started working again.

**Comment by Vortec4800** [comment]
Sorry, I just now had a chance to look into this again.

It may have been an npm issue as was suggested. I updated the server back to 2.8.2 without any other changes (basically the same config when I opened the issue) and ran `npm update` which succeeded, then was able to start the server without any trouble. Seems like it's working now as expected...

**Comment by oallouch** [comment]
Ok, the real issue is that you can't just remove node_modules without removing package-lock.json.

Now, it's closed.
