### ISSUE TITLE
`{useMasterKey:true}` within background job causing crash when it is the first request to the server

### ISSUE THREAD

**Issue by JacobJT** [parse-community/parse-server#4882]
### Issue Description

I am experiencing an entire server crash (whole thing exits, parse-server no longer running) after receiving the error `Cannot use the Master Key, it has not been provided.` when making a query request with the master key from a background job.
- I have verified that the correct master key was passed in.
- I experience this both from the dashboard and from command line curl requests.
- Also of note is that this only seems to happen when the background job is the very first request after starting the server. If I run a cloud code function, then the background job, the background job runs as expected.
- I have added a cloud code function and background job with identical functionality to test this. I will also note that I tried to reproduce this on a separate machine. On both machines, I started by running `rm -rf node_modules/` and `npm install`.  On the other machine, the background job appeared to work as expected. I found that the working machine is running npm v 5.6.0, and the NOT working machine is running npm v 6.1.0 . They are on the same version of node, 8.11.1. 

### Steps to reproduce

Within main.js, I've added the following function and background job. Note: These are identical, even in name, except that `response` is used for the function and `status` is used for the job:

```
Parse.Cloud.define('useMasterKeyTest', (request, response) => {
    let query = new Parse.Query(Parse.User);
    return query.first({useMasterKey:true}).then(
        result => { response.success(result); },
        error => { response.error(error); }
    );
});
```

```
Parse.Cloud.job('useMasterKeyTest', (request, status) => {
    let query = new Parse.Query(Parse.User);
    return query.first({useMasterKey:true}).then(
        result => { response.success(result); },
        error => { status.error(error); }
    );
});
```

To reproduce the error, all I need to do is start the server, and use the following terminal command:
`curl  -H "Content-Type: application/json" -H "X-Parse-Application-Id: <redacted>" -H "X-Parse-Master-Key: <redacted>" -X POST -d '{}' localhost:1337/parse/jobs/useMasterKeyTest`

This will crash the server.  When I restart the server, I can run the following two commands in order, and both work as expected:

`curl  -H "Content-Type: application/json" -H "X-Parse-Application-Id: <redacted>" -H "X-Parse-Master-Key: <redacted>" -X POST -d '{}' localhost:1337/parse/functions/useMasterKeyTest`
`curl  -H "Content-Type: application/json" -H "X-Parse-Application-Id: <redacted>" -H "X-Parse-Master-Key: <redacted>" -X POST -d '{}' localhost:1337/parse/jobs/useMasterKeyTest`
 
### Expected Results

The background job returns a user object

### Actual Outcome

The background job throws a fatal error, entire server crashes, unless another cloud function is run first.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : Initially experienced on 2.7.4, updated to 2.8.2 and still experiencing
  - Operating System:     OSX 10.13.5
  - Hardware:             2015 MBP
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): local host, through command line and debugging through VSCode

- **Database** 
Appears irrelevant, as the error occurs before the connection to the database. I can dig specifics up if needed, but it's remote through mLab.

### Logs/Trace

Log for a crash, where the job is the first thing I try:
```
cd /Users/Me/Code/Project ; env "VERBOSE=true" /Users/Me/n/bin/node --inspect-brk=19377 index         Me@My-MacBook-Pro-2.js
Debugger listening on <redacted>
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
verbose: Support key pairs Map {}
(node:77298) ExperimentalWarning: The http2 module is an experimental API.
Parse-Server running on port 1337
verbose: REQUEST for [POST] /parse/jobs/useMasterKeyTest: {} method=POST, url=/parse/jobs/useMasterKeyTest, host=localhost:1337, user-agent=curl/7.54.0, accept=*/*, content-type=application/json, x-parse-application-id=<redacted>, x-parse-master-key=<redacted>, content-length=2,
verbose: RESPONSE from [POST] /parse/jobs/useMasterKeyTest: {
  "headers": {
    "X-Parse-Job-Status-Id": "<redacted>"
  },
  "response": {}
} X-Parse-Job-Status-Id=<redacted>,
/Users/Me/Code/Project/node_modules/parse-server/lib/ParseServer.js:218
          throw err;
          ^

Error: Cannot use the Master Key, it has not been provided.
    at Object.request (/Users/Me/Code/Project/node_modules/parse/lib/node/RESTController.js:187:15)
    at Object.find (/Users/Me/Code/Project/node_modules/parse/lib/node/ParseQuery.js:1552:27)
    at ParseQuery.value (/Users/Me/Code/Project/node_modules/parse/lib/node/ParseQuery.js:676:25)
    at Parse.Cloud.job (/Users/Me/Code/Project/cloud/main.js:8440:18)
    at process.nextTick (/Users/Me/Code/Project/node_modules/parse-server/lib/Routers/FunctionsRouter.js:87:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
Waiting for the debugger to disconnect...
[1]    77298 killed     env "VERBOSE=true" /Users/Me/n/bin/node --inspect-brk=19377 index.js
```

Logs when I run the cloud function first
```
cd /Users/Me/Code/Project ; env "VERBOSE=true" /Users/Me/n/bin/node --inspect-brk=43810 index.js
Debugger listening on ws://127.0.0.1:43810/d5610927-c870-4401-a74f-42702ebc796e
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
Passing AWS credentials to this adapter is now DEPRECATED and will be removed in a future version See: https://github.com/parse-server-modules/parse-server-s3-adapter#aws-credentials for details
verbose: Support key pairs Map {}
(node:77423) ExperimentalWarning: The http2 module is an experimental API.
Parse-Server running on port 1337
verbose: REQUEST for [POST] /parse/functions/useMasterKeyTest: {} method=POST, url=/parse/functions/useMasterKeyTest, host=localhost:1337, user-agent=curl/7.54.0, accept=*/*, content-type=application/json, x-parse-application-id=<redacted>, x-parse-master-key=<redacted>, content-length=2,
verbose: REQUEST for [GET] /parse/classes/_User: {
  "where": {},
  "limit": 1
} method=GET, url=/parse/classes/_User, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 8.11.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=239, connection=close, , limit=1
verbose: RESPONSE from [GET] /parse/classes/_User: {
  "response": {
    "results": [
      <User Data>
      }
    ]
  }
} results=[<User Data>]
info: Ran cloud function useMasterKeyTest for user undefined with:
  Input: {}
  Result: { <User Data>
 functionName=useMasterKeyTest, , user=undefined
verbose: RESPONSE from [POST] /parse/functions/useMasterKeyTest: {
  "response": {
    "result": {
      <User Data>
    }
  }
} <User Data>
verbose: REQUEST for [POST] /parse/jobs/useMasterKeyTest: {} method=POST, url=/parse/jobs/useMasterKeyTest, host=localhost:1337, user-agent=curl/7.54.0, accept=*/*, content-type=application/json, x-parse-application-id=<redacted>, x-parse-master-key=<redacted>, content-length=2,
verbose: RESPONSE from [POST] /parse/jobs/useMasterKeyTest: {
  "headers": {
    "X-Parse-Job-Status-Id": <redacted>
  },
  "response": {}
} X-Parse-Job-Status-Id=<redacted>,
verbose: REQUEST for [GET] /parse/classes/_User: {
  "where": {},
  "limit": 1
} method=GET, url=/parse/classes/_User, user-agent=node-XMLHttpRequest, Parse/js1.11.1 (NodeJS 8.11.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=239, connection=close, , limit=1
verbose: RESPONSE from [GET] /parse/classes/_User: {
  "response": {
    "results": [
      <Same User Data>
    ]
  }
} results=[<Same User Data>]
```

Please let me know if I can provide any additional details.

**Comment by JacobJT** [comment]
I'll also note that when I changed my request from the function to the job, all I would do is press up within the terminal, then go to the previous call and change `/jobs/` to `/functions/`. So, there were not any weird typo issues. The cloud function and subsequent calls to `/jobs/` definitely received the same exact headers as the initial call to `/jobs/`. 

I'll take a look at adding a PR with this breaking change, though it does seem a requirement is that it is the very first thing that gets run. Will try to track down whatever determines the order of testing.

**Comment by flovilmart** [comment]
The error is thrown by the JS SDK, it’s odd that it would throw an error for jobs and not functions. Do you have any call to Parse.initialize in your Cloud code? Can your double check?

**Comment by JacobJT** [comment]
I have a webhook handler that is hosted on the same server but a separate express endpoint from the server. I.e. parse-server is hosted at /parseEndpoint, and the webhook endpoint is hosted at /webhookEndpoint

Within that webhook handler, I validate requests coming in, then return the response to whoever sent the webhook that I received it, and then call a parse cloud code function to handle any actual functionality that needs to be done with the request. This is used for slack and stripe webhooks exclusively at this time.

So I have in index.js:
```
app.use(mountPath, new ParseServer({ ... }));
app.use('/webhookEndpoint', MyWebhooks());
```

And `Parse.initialize` is called within `MyWebhooks.js`

**Comment by JacobJT** [comment]
@flovilmart 

Swapping the order of those two lines seems to have done the trick. Thanks for the lead. 

Is there a reason I should have known I can't initialize the javascript client on a separate part of my server? Or a better way to trigger cloud functions from my webhook endpoints? Or is this still a bug that ought to be addressed?

**Comment by JacobJT** [comment]
I'll test and see if those endpoints are doing anything wonky after moving the app.use calls.

**Comment by flovilmart** [comment]
> there a reason I should have known I can't initialize the javascript client on a separate part of my server?

Yeah, if you initialize without the masterKey for example, this will lead to this issue.

**Comment by flovilmart** [comment]
There are multiple initialize calls within the parse server, only one should suffice, and you should never call it. In the future we may break and throw an error if you attempt to call initialie

**Comment by JacobJT** [comment]
But this endpoint was separate from the Parse-Server endpoint. I'm not seeing how they are interacting, other than my webhook one happens to be calling the server. I thought I was treating them as two separately contained entities. How does the dashboard, for instance, make these calls? And why does calling a cloud function first somehow circumvent this issue?

A lot of tutorials have you mount the dashboard on the same express app as the server itself. Is that potentially introducing other wonkiness that just happens to be weakly avoided by the dashboard's master key?

Is there something I can do to contain my other instance better so that they don't interfere, or should I move it to a totally separate server to avoid this issue instead?

**Comment by flovilmart** [comment]
There can only be one Parse SDK initialized within one nodejs process. The reason why the function may not have crashed is that another call to Parse.initialize may have been made from within the server. Again, Parse.initialize should never be called within the process that hosts parse server. The dashboard is a client app, where the SDK is initialized in the browser, not the server.

Having the dashboard on the server is on the tutorials, but not recommended by the current documentations.

**Comment by flovilmart** [comment]
In fact you HAVE TO remove the calls to Parse.initialize, if you were to be initializing with another appId than the one on the server, uou’re Break all hell loose. We’ll address this by throwing error in any subsequent call to Parse.initialize.

**Comment by JacobJT** [comment]
I see. It sounds like my long term fix is to separate my dashboard and webhook endpoints to at least be on separate node processes, which I should be able to configure through Elastic Beanstalk, as I'm AWS hosted. Or, for further decoupling, their own EB environments.  

Do you know if there is a quick temporary solution to reference that existing Parse-Server instance from my Webhooks endpoint to ensure there isn't any other unnoticed repercussions of this set up going on in the meantime? 

I imagine something like
```
const myParse = new ParseServer({...});
app.use('/parseEndpoint', myParse);
app.use('/webhookEndpoitnt', MyWebhooks(myParse));
```

And updating the initializer for `MyWebhooks` to take in the Parse server and use that instead of initializing one would work?

**Comment by JacobJT** [comment]
I have confirmed that simply removing the `Parse.initialize` calls from within my webhooks file was enough to avoid the issue. As Flovilmart has pointed out, `Parse.initialize` is called on behalf of the entire node process. 

I do think it may be a little bit hacky that I make the assumption that Parse has been initialized from the webhook endpoint, and I intend to do a larger rework to decouple these servers. However, everything looks to be working great at this point.
