### ISSUE TITLE
PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS is broken on Parse > 2.7.4

### ISSUE THREAD

**Issue by markuswinkler** [parse-community/parse-server#4912]
### Issue Description

When I upgraded to a version > 2.7.4 the experimental direct access is broken.
Request fail with
```
error: Error generating response. ParseError { code: 101, message: 'Object not found.' } code=101, message=Object not found.
error: Object not found. code=101, message=Object not found. 

```
with EXPERIMENTAL_DIRECT_ACCESS disabled everything works after applying the patch from
https://github.com/parse-community/parse-server/issues/4897 

### Steps to reproduce

Run parse on version 2.8.2 and try to make requests with EXPERIMENTAL_DIRECT_ACCESS
 
### Expected Results

That it works

### Actual Outcome

I get an error message and the session breaks

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.2 (latest commit)
  - Operating System:     AWS or mac os
  - Hardware:             AWS - small or mac pro
  - Localhost or remote server? AWS or localhost

- **Database**
  - MongoDB version: 3.4.13
  - Storage engine:  Tiger

**Comment by flovilmart** [comment]
@markuswinkler do you have more informations?

**Comment by markuswinkler** [comment]
@flovilmart sorry for the delay, got swamped at work.  😅

It seems the problem is connected to `Parse.Promise.when`.

the following simple function runs fine on 2.7.4 but not on anything higher than that.
(the function itself doesn't do anything, the important part is the Parse.Promise.when)

```
Parse.Cloud.define("z_debug_Ping", function(request, response) {
	const tStart=Date.now();
	const funcName = "z_debug_TestPerformance";

	let aQuery = [];

	let query;

	query = new Parse.Query(Parse.User);
	query.limit(10);
	query.find({useMasterKey: true});
	aQuery.push(query);

	query = new Parse.Query(Parse.User);
	query.limit(10);
	query.find({useMasterKey: true});
	aQuery.push(query);

	Parse.Promise.when(aQuery).then(function() {
			response.success("PONG. request: "+JSON.stringify(request));
		},
		function(error) {
			Raven.setContext({user: {email: request.user.get("email"), id: request.user.id}, tags: {func:funcName, type:"server"}, extra:{func:funcName, type:"server"}});
			if(process.env.ENVIRONMENT !== "DEBUG") Raven.captureException(error);
			reportError(funcName, error, request.user, Date.now()-tStart);
			response.error({code:141, message:error.stack})
		}
	);
});

```

results in the following error on > 2.7.4:

```
verbose: REQUEST for [POST] /parse/functions/z_debug_Ping: {} method=POST, url=/parse/functions/z_debug_Ping, host=devserver.int:1337, accept=*/*, x-parse-session-token=r:xxx, x-parse-application-id=xxx, x-parse-client-key=xxx, x-parse-installation-id=xxx, accept-encoding=gzip, deflate, x-parse-os-version=11.4.1 (15G77), accept-language=en-us, x-parse-client-version=i1.17.1, content-length=0, user-agent=Pretzel/4 CFNetwork/902.2 Darwin/17.7.0, connection=keep-alive, x-parse-app-build-version=4, x-parse-app-display-version=1.4.0, 
error: Error generating response. TypeError: Cannot read property 'when' of undefined
    at /.../cloud/main.js:8382:16
    at /.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:179:9
    at new Promise (<anonymous>)
    at new F (/.../node_modules/core-js/library/modules/_export.js:35:28)
    at handleCloudFunction (/.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:147:14)
    at /.../node_modules/parse-server/lib/PromiseRouter.js:169:7
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:281:22
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:354:14)
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:410:3)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:174:3)
    at router (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:317:13)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:335:12)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Promise.resolve.then.then.auth (/.../node_modules/parse-server/lib/middlewares.js:197:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) 
error: Uncaught internal server error. TypeError: Cannot read property 'when' of undefined
    at /.../cloud/main.js:8382:16
    at /.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:179:9
    at new Promise (<anonymous>)
    at new F (/.../node_modules/core-js/library/modules/_export.js:35:28)
    at handleCloudFunction (/.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:147:14)
    at /.../node_modules/parse-server/lib/PromiseRouter.js:169:7
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:281:22
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:354:14)
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:410:3)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:174:3)
    at router (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:317:13)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:335:12)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Promise.resolve.then.then.auth (/.../node_modules/parse-server/lib/middlewares.js:197:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) TypeError: Cannot read property 'when' of undefined
    at /.../cloud/main.js:8382:16
    at /.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:179:9
    at new Promise (<anonymous>)
    at new F (/.../node_modules/core-js/library/modules/_export.js:35:28)
    at handleCloudFunction (/.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:147:14)
    at /.../node_modules/parse-server/lib/PromiseRouter.js:169:7
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:281:22
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:354:14)
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:410:3)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:174:3)
    at router (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:317:13)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:335:12)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Promise.resolve.then.then.auth (/.../node_modules/parse-server/lib/middlewares.js:197:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
TypeError: Cannot read property 'when' of undefined
    at /.../cloud/main.js:8382:16
    at /.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:179:9
    at new Promise (<anonymous>)
    at new F (/.../node_modules/core-js/library/modules/_export.js:35:28)
    at handleCloudFunction (/.../node_modules/parse-server/lib/Routers/FunctionsRouter.js:147:14)
    at /.../node_modules/parse-server/lib/PromiseRouter.js:169:7
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/.../node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:281:22
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:354:14)
    at param (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:410:3)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:174:3)
    at router (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/.../node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:317:13)
    at /.../node_modules/parse-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:335:12)
    at next (/.../node_modules/parse-server/node_modules/express/lib/router/index.js:275:10)
    at Promise.resolve.then.then.auth (/.../node_modules/parse-server/lib/middlewares.js:197:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

**Comment by flovilmart** [comment]
How is it related to PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS. I fail to see the connection here. 

Can you try using `Promise.all` instead? We'll be deprecating Parse.Promise in the next release.

**Comment by markuswinkler** [comment]
Ah, my bad. Forgot to mention, with PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS disabled the above example works in the new version.

I will switch to Promise.all and see if I still have the same problem.

**Comment by flovilmart** [comment]
What version of the server are you running? Are you off master?

**Comment by markuswinkler** [comment]
I installed the latest version. (`"parse-server": "> 2.7.4"`), no special branch.

**Comment by flovilmart** [comment]
I just tried with a unit test, on the 2.8.2 tag and it's working perfectly. 

From the stacktrace it looks like Parse.Promise doesn't exist which is the situation since the SDK JS 2.0. I'm not sure why you'd want to run the SDK at this version, because it has many breaking changes including this one.

**Comment by markuswinkler** [comment]
Even more odd since the call runs fine with direct access disabled.
I will change to Promise.all in the evening and report back.
Thanks for investigating!

**Comment by markuswinkler** [comment]
On a side note, is there a list of breaking changes? Anything else obvious I need to look out for?

**Comment by flovilmart** [comment]
There's no breaking change, What I see here in your code is that you,re using the SDK v2.0, which has just been released OR that for some reason, `Parse.Promise` is undefined. From there I can't really say what's wrong.

**Comment by flovilmart** [comment]
what's the result of `npm ls parse-server` and ` npm ls parse`

**Comment by markuswinkler** [comment]
Ok, this is really weird. I just came home, rebooted the machine and it works now. Maybe it was a package cache or a combination of 2.8.3 and 1.11.1 (now it's 2.8.3 and 2.0.0).
Sorry for the false alarm!
All Parse.Promise calls are changed too (according to the migration guide).

**Comment by flovilmart** [comment]
Ok so ir’w All good we can close?

**Comment by markuswinkler** [comment]
Yes, thank you.
