### ISSUE TITLE
Cannot find module 'parse-server'

### ISSUE THREAD

**Issue by pastordee** [parse-community/parse-server#4928]
module.js:471
    throw err;
    ^

Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/bitnami/apps/parse/htdocs/server.js:3:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error: Forever detected script exited with code: 1

**Comment by flovilmart** [comment]
Fill the issue template completely and reopen the issue.

**Comment by pastordee** [comment]
How do I do that please

**Comment by flovilmart** [comment]
when you open a new issue you’re promoted with a template, you should answer the questions that are asked before opening the issue.

**Comment by KevinHu2014** [comment]
same issue
