### ISSUE TITLE
Error: Cannot find module 'http2' AND TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by seza443** [parse-community/parse-server#4976]
### Issue Description

Starting `parse-server@2.8.4` with `Node 8.1.4` ([latest version supported by AWS Elastic Beanstalk](https://aws.amazon.com/releasenotes/release-aws-elastic-beanstalk-node-js-platform-update-on-july-15-2017/)) causes the error below:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/app/parse/node_modules/apn/index.js:15:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

Trying to install *http2* myself with `npm install --save http2` and then starting parse-server causes error below:

```
/home/app/parse/node_modules/apn/lib/client.js:18
  } = http2.constants;
           ^

TypeError: Cannot match against 'undefined' or 'null'.
    at module.exports (/home/app/parse/node_modules/apn/lib/client.js:18:12)
    at Object.<anonymous> (/home/app/parse/node_modules/apn/index.js:17:39)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/app/parse/node_modules/@parse/push-adapter/lib/APNS.js:12:12)
```

### Steps to reproduce

 
See description above.

### Expected Results

parse-server should start just fine.

### Actual Outcome

See errors above.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.8.4
  - Operating System:     Ubuntu 16.04
  - Hardware:             Intel core i7, 16GO RAM
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local with Docker

- **Node.js**
  - node version: 8.1.4

- **Database**
  - MongoDB version: v3.2.19
  - Storage engine:  AWS S3
  - Hardware:        Intel Core i7, 16GO RAM (same)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Local with Docker

**Comment by flovilmart** [comment]
Please use 8.11.3, at the time of writing, it's the latest version. And do not use the `http2` npm pacakge as it's incompatible with parse-server, it is provided by node itself.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs

**Comment by seza443** [comment]
Thanks @flovilmart !
