### ISSUE TITLE
cannot import npm package

### ISSUE THREAD

**Issue by meepeek** [parse-community/parse-server#5137]
# Before opening the issue please ensure that you have:

- [ Y ] [Read the migration guide](https://github.com/parse-community/parse-server/blob/master/3.0.0.md) to parse-server 3.0.0
- [ Y ] [Read the migration guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md) to Parse SDK JS 2.0.0

### Issue Description

import a package in cloud code result in error

### Steps to reproduce

import any package
 
### Expected Results

import success without error

### Actual Outcome

```
/Users/thee/Desktop/parse-base-system/services/data-server/cloud/main.js:1
(function (exports, require, module, __filename, __dirname) { import cuid from 'cuid'
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:73:7)
    at createScript (vm.js:245:10)
    at Object.runInThisContext (vm.js:297:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.0
  - Operating System:     OSX Heigh Sierra
  - Hardware:             MacBook Air 2012
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

**Comment by flovilmart** [comment]
import is not a valid node statement. Use require()
