### ISSUE TITLE
Postgres: Contains doesn't support foreign characters

### ISSUE THREAD

**Issue by maxiundtesa** [parse-community/parse-server#5293]
I am trying to use containsString on a PFQuery with Postgres.
It works fine if i'm using a normal string (e.g. `test`), but it stops working if I use a string with special characters (e.g. `öäüß`).

ExampleCode: 
```swift
let query = PFQuery(className: "Auktion");
query.whereKey("nameLowercase", contains: "autoöo");
query.findObjectsInBackground(block: { (object, error) in
print(object)
});
```
GET-Response: 
```REQUEST for [GET] /classes/Auktion: {
  "where": {
    "nameLowercase": {
     "$regex": "\\Qautoöo\\E"
  }
 }
}
```

Server Error: 
```
{ error: invalid regular expression: invalid escape \ sequence
at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)
at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:379:19)
at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:119:22)
at Socket.emit (events.js:188:13)
at Socket.EventEmitter.emit (domain.js:441:20)
at addChunk (_stream_readable.js:288:12)
at readableAddChunk (_stream_readable.js:269:11)
at Socket.Readable.push (_stream_readable.js:224:10)
at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
name: 'error',
length: 118,
severity: 'ERROR',
code: '2201B',
detail: undefined,
hint: undefined,
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'regexp.c',
line: '208',
routine: 'RE_compile_and_cache' } name=error, length=118, severity=ERROR, code=2201B, detail=undefined, hint=undefined, position=undefined, internalPosition=undefined, internalQuery=undefined, where=undefined, schema=undefined, table=undefined, column=undefined, dataType=undefined, constraint=undefined, file=regexp.c, line=208, routine=RE_compile_and_cache, stack=Error: error: invalid regular expression: invalid escape \ sequence
```

```

Trace: Before 'createLiteralRegex': "\\Qautöo\\E"
    at buildWhereClause (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:718:15)
    at PostgresStorageAdapter.find (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1642:19)
    at then.then.then (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Controllers/DatabaseController.js:1070:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)


Trace: After 'createLiteralRegex': "aut\\öo"
    at buildWhereClause (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:720:15)
    at PostgresStorageAdapter.find (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js:1642:19)
    at then.then.then (/Users/maximilian/Documents/Heroku Server/parse-server-node/node_modules/parse-server/lib/Controllers/DatabaseController.js:1070:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The error message is thrown because the backslash occurs twice.
### Environment Setup

- **Server**
  - parse-server version: 3.1.3
  - Localhost or remote server? Heroku

- **Database**
  - postgres version: 10.4
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Heroku

**Comment by maxiundtesa** [comment]
The problem was the regex in `createLiteralRegex`:
```javascript
function createLiteralRegex(remaining) {
  return remaining
    .split('')
    .map(c => {
      if (c.match(/[0-9a-zA-Z]/) !== null) {
        // don't escape alphanumeric characters
        return c;
      }
      // escape everything else (single quotes with single quotes, everything else with a backslash)
      return c === `'` ? `''` : `\\${c}`;
    })
    .join('');
}
```

It only supports "normal" letters, otherwise it will escape the char.

**Solution: To fix this** and support foreign letters like äößùüâæç..., **I used XRegExp** (already a dependency of Parse Server).

 ```javascript
import {XRegExp} from "xregexp";

function createLiteralRegex(remaining) {
  return remaining
    .split('')
    .map(c => {
      const regex = XRegExp('[0-9 ]|\\p{L}'); // Support all unicode letter chars
      if (c.match(regex) !== null) {
        // don't escape alphanumeric characters
        return c;
      }
      // escape everything else (single quotes with single quotes, everything else with a backslash)
      return c === `'` ? `''` : `\\${c}`;
    })
    .join('');
}
```

**Comment by dplewis** [comment]
@maxiundtesa Would you like to open a PR?

**Comment by JeffGuKang** [comment]
@maxiundtesa 
In local, my mac, it works well with Korean language. But there is the same error AWS EB environment with Postgres RDS. 

Thanks for sharing this. It will be better to open a PR.

**Comment by JeffGuKang** [comment]
I made PR using @maxiundtesa's solution.
