### ISSUE TITLE
PostgreSQL adapter: cannot pass more than 100 arguments to a function

### ISSUE THREAD

**Issue by lukyanov** [parse-community/parse-server#5355]
### Issue Description

There is quite an issue introduced in here: 631b1684
You can't save more than 100 elements in an array type field anymore when using PostgreSQL.
The error appears when calling `json_build_array()`.

### Steps to reproduce

1. Create a field of type 'Array'.
2. Try to save more than 100 elements into it.
 
### Expected Results

The array is saved successfully.

### Actual Outcome

The following error occurs:

```
error: Uncaught internal server error. { error: cannot pass more than 100 arguments to a function
    at Connection.parseE (/parse-server/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/parse-server/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/parse-server/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 119,
  severity: 'ERROR',
  code: '54023',
  detail: undefined,
  hint: undefined,
  position: '34',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_func.c',
  line: '119',
  routine: 'ParseFuncOrColumn' } error: cannot pass more than 100 arguments to a function
    at Connection.parseE (/parse-server/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/parse-server/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/parse-server/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
error: cannot pass more than 100 arguments to a function
    at Connection.parseE (/parse-server/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/parse-server/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/parse-server/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Environment Setup

- **Server**
  - parse-server version: master on 4d07f0274a813a56532b52bfaf4e8dfa25e906e8

- **Database**
  - PostgreSQL version: 9.6.10

**Comment by dplewis** [comment]
Try https://www.postgresql.org/docs/9.1/runtime-config-preset.html

There is a `max_function_args` option that defaults to 100

**Comment by lukyanov** [comment]
> Try https://www.postgresql.org/docs/9.1/runtime-config-preset.html
> 
> There is a `max_function_args` option that defaults to 100

Yep, I know about this limitation. I just don't think this is a good solution to the problem.

The thing is that I just want to store an array of json objects to a Parse object field. That's it. PosgreSQL (and Mongo as well) supports this out of the box. I don't call database functions or anything like that. There is a value and there is a field. I put the correctly shaped value to the field. Why Parse Server prevents me from doing that? Moreover, it does that just to check the correctness of the value if I'm not mistaken. And by doing this very action it breaks the flow. Why?

**Comment by lukyanov** [comment]
Let me try to express my point in other words.

If such an error occurred due to a limitation in the storing flow of the backend database (PostgreSQL in this case), everything would be completely fine. For example, imagine that PostgreSQL has the limit of how many items can be stored in an array (it does, by the way, but in terms of a total size of the field). Now when I store an array of some out-of-the-limit size, I get the error message, somtning like "the array is too big". That's fine. The type of storage I use does not support this. No questions to Parse Server.

Now we have a different story. PostgreSQL _does_ support storing more that 100 items in a jsonb field. But I can't do this. Some itermediate synthetic procedure within the Parse Server does not allow me to get through it.

**Comment by dplewis** [comment]
Possible solution:

The old method takes one parameter (which is why you can store more than 100 objects) but it doesn't allow for mixed values

`array_to_json('{}'::${type}[])::jsonb`

The new method allows for mixed values but as the issue you mentioned doesn't allow for more than 100 arguments

`json_build_array(1, '2', [1,2,3])`

A possible fix would be to use the first method if they are all the same type and impose a 100 limit for mixed values.

What do you think?

**Comment by CoderickLamar** [comment]
Any progress on this? Just came across this one myself

**Comment by dplewis** [comment]
I can look into it
