### ISSUE TITLE
Login with FB causing error 500

### ISSUE THREAD

**Issue by oproulx** [parse-community/parse-server#5358]
Login with Facebook was previously working, but I'm now seeing the following error:

> BadRequestError: request aborted
>     at IncomingMessage.onAborted (D:\home\site\wwwroot\node_modules\parse-server\node_modules\raw-body\index.js:231:10)
>     at emitNone (events.js:105:13)
>     at IncomingMessage.emit (events.js:207:7)
>     at abortIncoming (_http_server.js:410:9)
>     at socketOnClose (_http_server.js:404:3)
>     at emitOne (events.js:120:20)
>     at Socket.emit (events.js:210:7)
>     at Pipe._handle.close [as _onclose] (net.js:545:12)

### Environment Setup

- **Server**
  - parse-server version:  2.7.4 (but tried with 2.7.2, 2.7.0, 2.6.5, 2.2.9)
  - Operating System:  IIS
  - Remote server? : Azure Web App

Is this perhaps related to:
https://github.com/parse-community/Parse-SDK-JS/issues/726

**Comment by oproulx** [comment]
We seem to have resolved this by adding the following pods on iOS:

```
	pod 'FBSDKCoreKit', '~> 4.38.0'
	pod 'FBSDKLoginKit', '~> 4.38.0'

```
