### ISSUE TITLE
How to use $ geoNear with aggregate؟

### ISSUE THREAD

**Issue by eslam2010011** [parse-community/parse-server#5384]
Uncaught internal server error. { MongoError: geoNear command failed: { ok: 0.0, errmsg: "'near' field must be point", code: 17304, codeName: "Location17304" }
    at queryCallback (/root/parse-server-example/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /root/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
  ok: 0,
  errmsg: 'geoNear command failed: { ok: 0.0, errmsg: "\'near\' field must be point", code: 17304, codeName: "Location17304" }',
  code: 16604,
  codeName: 'Location16604',
  name: 'MongoError',

my code 
![image](https://user-images.githubusercontent.com/21963428/53247711-c21ddf80-36bc-11e9-859c-c88d5a409d90.png)

**Comment by acinader** [comment]
our github issues are for bugs and feature requests.

If you'd like help, [StackOverflow](https://stackoverflow.com/questions/tagged/parse-server?sort=newest&pageSize=30) is a good resource.
