### ISSUE TITLE
Silence test output

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-server#5798]
Current test output is noisy, even when all tests are passing.  Would be nice if stdout and err were silent, but could be turned back on with an env var like TEST_OUTPUT=1 or something

```
Passing AWS credentials to this adapter is now DEPRECATED and will be removed in a future version See: https://github.com/parse-server-modules/parse-server-s3-adapter#aws-credentials for details
................Error: unauthorized: master key is required
    at promiseEnforceMasterKeyAccess (/Users/arthur/code/parse-server/lib/middlewares.js:360:19)
    at promise.then (/Users/arthur/code/parse-server/lib/PromiseRouter.js:85:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: unauthorized: master key is required
    at promiseEnforceMasterKeyAccess (/Users/arthur/code/parse-server/lib/middlewares.js:360:19)
    at promise.then (/Users/arthur/code/parse-server/lib/PromiseRouter.js:85:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
.Error: unauthorized: master
```

**Comment by dplewis** [comment]
I agree, if there is an easy way to do it. If not I can silence most of the output manually.

**Comment by acinader** [comment]
there should be a simple direct way to do it.  I vaguely recall that it was once that way :).  I'll take a peek...

**Comment by davimacedo** [comment]
Parse Dashboard has a much cleaner output:

```
 PASS  src/lib/tests/ColumnPreferences.test.js
 PASS  src/lib/tests/extractTime.test.js
 PASS  src/lib/tests/Charting.test.js
 PASS  src/lib/tests/Authentication.test.js
 PASS  src/lib/tests/Button.test.js
 PASS  src/lib/tests/DateUtils.test.js
 PASS  src/lib/tests/Email.test.js
 PASS  src/lib/tests/prettyNumber.test.js
 PASS  src/lib/tests/passwordStrength.test.js
 PASS  src/lib/tests/PlatformCard.test.js
 PASS  src/lib/tests/Tooltip.test.js
 PASS  src/lib/tests/Markdown.test.js
 FAIL  src/lib/tests/e2e/dashboard.e2e.test.js (6.093s)
  ● dashboard e2e › can keep mount path on redirect

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: 

      24 | // TODO: Mount parse-server
      25 | describe('dashboard e2e', () => {
    > 26 |   it('can keep mount path on redirect', async () => {
         |   ^
      27 |     let server;
      28 |     const mount = '/dashboard';
      29 |     const launchApp = new Promise(resolve => {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/lib/tests/e2e/dashboard.e2e.test.js:26:3)
      at Object.<anonymous> (src/lib/tests/e2e/dashboard.e2e.test.js:25:1)

Test Suites: 1 failed, 12 passed, 13 total
Tests:       1 failed, 57 passed, 58 total
Snapshots:   0 total
Time:        9.995s
```

What do you think about using the same setup here?

**Comment by davimacedo** [comment]
It basically prints one line per file + one line per failing test.
