### ISSUE TITLE
LiveQuery Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by GoGross** [parse-community/parse-server#5904]
### Issue Description

Websocket shuts down immediately after opening Error [ERR_STREAM_WRITE_AFTER_END]: write after end

`C:\apps\gross-cloud\node_modules\parse-server\lib\ParseServer.js:231
          throw err;
          ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Receiver.Writable.write (_stream_writable.js:291:5)
    at TLSSocket.socketOnData (C:\apps\gross-cloud\node_modules\parse-server\node_modules\ws\lib\websocket.js:875:35)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

**Comment by dplewis** [comment]
Which version of Parse Server and node version you are using?

Can you provide more info?
