### ISSUE TITLE
Managing Session Issues - Parse error: Invalid session token

### ISSUE THREAD

**Issue by rizzla22** [parse-community/parse-server#6082]
Hosting: locally on OSX running parse server 3.5.0

I am having massive issues with sessions on my cloud infrastructure, when a device tries to make a request with a session that does not exist it cripples the entire server. with the following error 

```
[1] error: Parse error: Invalid session token {"code":209,"stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (.../node_modules/parse-server/lib/Auth.js:114:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

Is there anyway to validate that a session exists before killing the server with an error, been trying to use express middleware but I cant seem to find an entry point to add the following 

```
async function loggedUser(sessionToken: string) {
  const loggedUserSessionQuery = new Parse.Query(Parse.Session);
  loggedUserSessionQuery.equalTo('sessionToken', sessionToken);
  loggedUserSessionQuery.include('user');

  const loggedUserSession = await loggedUserSessionQuery.first({
    sessionToken
  });

  if (!loggedUserSession) {
    throw new Error('Invalid session token.');
  }

  return loggedUserSession.get('user');
}
```

or this 

```
const myMiddleware = function (req, res, next) {
    const json = res.json;
    res.json = function (object) {
        if (object.code == Parse.Error.INVALID_SESSION_TOKEN) {
            // get the session token
            const token = req.headers['x-parse-session-token'];
            // Invalid token, do something
        }
        // Forward the response
        json.call(res, object);
    }
    next()
}
```

**Comment by rizzla22** [comment]
On further investigation I find that even calling Parse.Session.current() will result in an error on the server side, in a cloud environment like Google App Engine this is enough to totally take my instance offline. Can we not just return a simple boolean value rather than a destructive error ?

**Comment by davimacedo** [comment]
@rizzla22 it is really strange behavior. The invalid session token should be logged in Parse Server logs and returned to the client. But it should not break the Parse Server process. Can you please share more details about how you are running Parse Server?

**Comment by mman** [comment]
@rizzla22 the invalid session token message is harmless and can happen for example when a user changes password and all existing session tokens for the user are deleted. An app that talks to the parse server later with expired session token will generate the invalid session token message. It definitely will not kill the server. Please post more logs or backtraces.

**Comment by REPTILEHAUS** [comment]
I experience this. Im not sure what the adverse affects are but I do notice that when this happens in a Google App Engine environment that there is usually an preceeded by a invalid session

**Comment by dplewis** [comment]
@REPTILEHAUS does your server crash?

We should document installationId and what it means.

What info should be included with invalid session that isn’t too sensitive. 

Similar too https://github.com/parse-community/parse-server/issues/4330
