### ISSUE TITLE
MongoError: Failed to determine whether query system can provide a covered projection

### ISSUE THREAD

**Issue by ravikiranp123** [parse-community/parse-server#6527]
### Issue Description

Hello! When I try to do a full text search on a remote parse api, I get the issue mentioned in the title.
Here is the complete log:
`MongoError: Failed to determine whether query system can provide a covered projection :: caused by :: text index required for $text query
    at MessageStream.messageHandler (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:485:12)
    at processIncomingData (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:392:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at MessageStream.Writable.write (_stream_writable.js:314:12)
    at Socket.ondata (_stream_readable.js:708:22)
    at Socket.emit (events.js:315:20)`

Here are some more details:
1. On my local machine running parse, fullText search works just fine.
2. I initially tried with a docker based system (caprover) and had this issue. Thought it could be a forewall issue.
3. Tried on a fresh VPS with mongo db and parse server as well as on heroku. The same issue occurs on both.

So it doesn't seem to be a firewall issue.

### Steps to reproduce

1. Create a basic parse server api and deploy to heroku or any VPS
2. Populate with some data similar to a bunch of blog posts (include title, post etc)
3. On your client, use any operation that uses `Query.fullText("title", "searchTerm");`

 
### Expected Results

Expected to get search results

### Actual Outcome
Get 500 error on client and above mentioned error on server.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.1.0
  - Operating System:     ubuntu 18.04/Heroku
  - Hardware:            1 GB RAM, 2vCore CPU/1 Dyno
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Oracle/Heroku

- **Database**
  - MongoDB version: 4.2.3
  - Storage engine:  wiredTiger
  - Hardware:        1 GB RAM, 2vCore CPU/mlab/atlas
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Oracle/mlab/atlas

### Logs/Trace
`MongoError: Failed to determine whether query system can provide a covered projection :: caused by :: text index required for $text query
    at MessageStream.messageHandler (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:485:12)
    at processIncomingData (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/ubuntu/sdp2-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:392:12)
    at writeOrBuffer (_stream_writable.js:374:5)
    at MessageStream.Writable.write (_stream_writable.js:314:12)
    at Socket.ondata (_stream_readable.js:708:22)
    at Socket.emit (events.js:315:20)`

**Comment by ravikiranp123** [comment]
It's funny how you search for days and get no solutions. Then open an issue and literally the next google search fixes your issue. Anyway, If you have this issue, the solution is here: 

https://docs.mongodb.com/v3.2/core/index-text/

Quick fix: Open up your mongo shell and run this command `db.reviews.createIndex( { comments: "text" } )`

change reviews to your collection name and comments to the item you are going to run a text search on. The term "text" remains the same.
