### ISSUE TITLE
Can’t send verify email and forgot password functionality using rest api of parse server hosted on t2.micro ec2 instance

### ISSUE THREAD

**Issue by utkarshpandey12** [parse-community/parse-server#6553]
I have set up parse server on aws and tried to enable forgot password and email verification features on parse but still i am not able to achieve the results

I did ssh using putty into instance
then

cd apps/parse/htdocs
npm install --save @parse/simple-mailgun-adapter

then vi server.js and
added the code in server.js posted on one of the discussion forum posted by bitnami engineer

**var api = new ParseServer({
    databaseURI: "mongodb://root:5FgWLXgj@127.0.0.1:27017/bitnami_parse",
    cloud: "./node_modules/parse-server/lib/cloud-code/Parse.Cloud.js",
    appId: "d67308a4de01fb6e828608e79864ab5bxxxxxxx",
    masterKey: "2c33303d64628186cb550afd8be43xxxxxxxx",
    fileKey: "5a2422681f9c41749dcdd40bxxxxxxxxxxxx",
    serverURL: 'http://18.222.149.208:80/parse',
    verifyUserEmails: true,
    emailVerifyTokenValidityDuration: 2 * 60 * 60,
    preventLoginWithUnverifiedEmail: false,
    publicServerURL:  'http://18.222.149.208:80/parse',
    appName: 'Parse App',
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            // The address that your emails come from
            fromAddress: 'parse@example.com',
            // Your domain from mailgun.com
            domain: 'sandboxbcbdcdcc.mailgun.org',
            // Your API key from mailgun.com
            apiKey: 'key-mykey',
        }
    }
});**
 
**My package.json also looks fine :
{
  "dependencies": {
    "@parse/simple-mailgun-adapter": "^1.0.3",
    "parse-dashboard": "^2.0.5",
    "parse-server": "^4.1.0"
  }
}**

After this i did signup for one user and passed the same signed up users email into the rest api code of forgot password

The api code 

**import jsonlib,http.client
connection = http.client.HTTPConnection('18.222.149.208', 80)
connection.connect()
connection.request('POST', '/parse/requestPasswordReset', jsonlib.dumps({
       "email": "uxsbhebj@gmail.com"
     }), {
       "X-Parse-Application-Id": "xxxxxxxxxxxxxxxxxxxxcbadbcjhadcasdcidcd",
       "X-Parse-REST-API-Key": "avbs",
       "Content-Type": "application/json"
     })
result = jsonlib.loads(connection.getresponse().read())
print(result)**

the api result returned '

**{'code': 1, 'error': 'An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.'}**

here is my parse.log file 

**error: Error handling request: { Error: An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.
    at UsersRouter._throwOnBadEmailConfig (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Routers/UsersRouter.js:310:15)
    at UsersRouter.handleResetRequest (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Routers/UsersRouter.js:318:10)
    at route.req (/opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/Routers/UsersRouter.js:419:19)
    at /opt/bitnami/apps/parse/htdocs/node_modules/parse-server/lib/PromiseRouter.js:175:7
    at Layer.handle [as handle_request] (/opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/layer.js:95:5)
    at /opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/bitnami/apps/parse/htdocs/node_modules/express/lib/router/index.js:335:12)
  message:
   'An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.',
  code: 1 }** 

However I see all three variables inside my server.js defined properly
I have registered on mailgun and used sandbox default domain and api key from dashboard
I have also configured the same email under sandbox receive list since we need to

I dont know what is going wrong and why does error code says add email adapter , appname and public serverURL even after defining these parameters in server,js
I have also given my systems stack trace and uploaded the same on bitnami support tool page created by bnsupport tool

Please help me in this regard
Thank You

 
### Expected Results

rest api output  = empty json and email received on email id given as parameter

### Actual Outcome

{'code': 1, 'error': 'An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.'}

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.1.0.0
  - Operating System:     linux -ubuntu 16.04 
  - Hardware:             Dont know 
  - Localhost or remote server?  AWS ec2 

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? AWS

**Comment by utkarshpandey12** [comment]
After npm simple-mailgun-adapter and making changes in server.js an instance reboot might be required for the changes to apply
 from instance command line
  Do sudo reboot
and it worked for me
