### ISSUE TITLE
Cloud Code Not Working

### ISSUE THREAD

**Issue by rakshithsj30** [parse-community/parse-server#6615]
I  have installed latest parse version 4.2.0

I have defined a trigger function in cloud.js and included the path in config.json

When i try to run the command `./parse-server config.json `  i am getting following error

`Configuration loaded from /home/iot/parse-upgraded/parse-server-4.2.0/bin/config.json
/home/iot/parse-upgraded/parse-server-4.2.0/lib/cloud-code/Parse.Cloud.js:93
  triggers.addTrigger(triggers.Types.beforeSave, className, handler, Parse.applicationId);
                                     ^

TypeError: Cannot read property 'beforeSave' of undefined
    at Object.ParseCloud.beforeSave (/home/iot/parse-upgraded/parse-server-4.2.0/lib/cloud-code/Parse.Cloud.js:93:38)
    at Object.<anonymous> (/home/iot/parse-upgraded/parse-server-4.2.0/cloud.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at new ParseServer (/home/iot/parse-upgraded/parse-server-4.2.0/lib/ParseServer.js:140:9)`

How to fix this? tried a lot but no luck. Please help me

**Comment by dplewis** [comment]
Did you set your cloud folder? 

https://github.com/parse-community/parse-server-example/blob/master/index.js#L16

**Comment by rakshithsj30** [comment]
Yes. Set in the config.json file

`{
  "apps": [
    {
      "publicServerURL": "http://demourl/parse",
      "appId": "app",
      "masterKey" : "master",
      "restAPIKey" : "rest",
      "clientKey" : "client",
      "liveQuery": {"classNames": ["hourly"]},
      "verbose":true,
      "cloud":"/home/iot/parse-upgraded/parse-server-4.2.0/cloud.js"
    }
  ]
 }
`
In cloud.js, i have

`Parse.Cloud.beforeSave("hourly", (request) => {

console.log("before save triggered");
});
`

**Comment by dplewis** [comment]
Interesting I've never ran it from a config file.

Can you debug here https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L97

Your cloud isn't loaded properly

**Comment by dplewis** [comment]
@rakshithsj30 Did you figure it out?
