### ISSUE TITLE
GraphQL: OR operator is not working

### ISSUE THREAD

**Issue by murshudov** [parse-community/parse-server#6667]
### Issue Description

When using OR operator in GraphQL, the query returns unexpected results

### Steps to reproduce

1. I have `Job` objects in DB:
```json
[
  {
    "id": "Sm9iOnZhVkRHeENJa2I=",
    "objectId": "vaVDGxCIkb"
  },
  {
    "id": "Sm9iOjZSQ3o1RlJuZDQ=",
    "objectId": "6RCz5FRnd4"
  }
]
```

2. I am executing following query:
```gql
query {
  jobs(
    where: {
      OR: {
        id: { equalTo: "Sm9iOnZhVkRHeENJa2I=" }
        objectId: { equalTo: "6RCz5FRnd4" }
      }
    }
  ) {
    count
    edges {
      node {
        id
        objectId
      }
    }
  }
}
```
 
### Expected Results

Query to return
```js
{
  "data": {
    "jobs": {
      "count": 2,
      "edges": [
        {
          "node": {
            "id": "Sm9iOnZhVkRHeENJa2I=",
            "objectId": "vaVDGxCIkb"
          }
        },
        {
          "node": {
            "id": "Sm9iOjZSQ3o1RlJuZDQ=",
            "objectId": "6RCz5FRnd4"
          }
        }
      ]
    }
  }
}
```

### Actual Outcome

Query returns
```js
{
  "data": {
    "jobs": {
      "count": 1,
      "edges": [
        {
          "node": {
            "id": "Sm9iOnZhVkRHeENJa2I=",
            "objectId": "vaVDGxCIkb"
          }
        }
      ]
    }
  }
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [4.2.0]
  - Operating System:     [Official Docker image, Ubuntu 19.04 Host]
  - Hardware:             [8GB RAM]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [VPS]

- **Database**
  - MongoDB version: [4.2.6]
  - Storage engine:  [WiredTiger]
  - Hardware:        [Official Docker image, Ubuntu 19.04 Host]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [VPS]

**Comment by davimacedo** [comment]
Please try the following and let me know:

```graphql
query {
  jobs(
    where: {
      OR: [
        { id: { equalTo: "Sm9iOnZhVkRHeENJa2I=" } }
        { objectId: { equalTo: "6RCz5FRnd4" } }
      ]
    }
  ) {
    count
    edges {
      node {
        id
        objectId
      }
    }
  }
}
```

**Comment by murshudov** [comment]
@davimacedo Thanks! Works like a charm 🥳

**Comment by murshudov** [comment]
But this type of query fails
```gql
query {
  jobs(
    where: {
      expired: { notEqualTo: true }
      OR: [
        { title: { text: { search: { term: "bank" } } } }
        { company: { have: { name: { text: { search: { term: "bank" } } } } } }
      ]
    }
  ) {
    count
    edges {
      node {
        title
        company {
          name
        }
      }
    }
  }
}
```

with result
```json
{
  "errors": [
    {
      "message": "MongoError: error processing query: ns=jobyfy-ci.Job limit=100Tree: $and\n    $or\n        _p_company $in [ \"Company$0CSE4ESsnH\" \"Company$4Raomvcy5j\" \"Company$4h1DawkhTf\" \"Company$682SLiAxPs\" \"Company$7cQxBOrmmh\" \"Company$7qqHWEH30i\" \"Company$8UvuVEENtN\" \"Company$9m814cmgJS\" \"Company$9xK7nECpzZ\" \"Company$BnbGxAleFJ\" \"Company$DAyVfxGW99\" \"Company$DOnH2AwE6x\" \"Company$DOqNyKyC4d\" \"Company$DTBOCTKcVK\" \"Company$E3TveaXl4t\" \"Company$HThCZJcJbE\" \"Company$HwV1aCE91u\" \"Company$IkCJG5k5IO\" \"Company$K4xwKfgCQD\" \"Company$OMr3pz3Wmk\" \"Company$P6c6RAMDSz\" \"Company$R3oODgB1Cj\" \"Company$S92mOwl0pL\" \"Company$UIJ95MDO2u\" \"Company$UaDjJS5ZTu\" \"Company$ZrOBdHjLZq\" \"Company$aBbtHkBqe5\" \"Company$drzWOkuOpq\" \"Company$h9uuVUq6Bo\" \"Company$hK3N7JJQrs\" \"Company$nra8zjlSlo\" \"Company$p3Y2OYofq3\" \"Company$rPzITYdlZ3\" \"Company$uNN7uDegsb\" \"Company$vbxuAfGFQD\" \"Company$wnzLHwPdNq\" ]\n        TEXT : query=bank, language=english, caseSensitive=0, diacriticSensitive=0, tag=NULL\n    $not\n        expired $eq true\nSort: {}\nProj: { title: 1, _p_company: 1, _id: 1, _created_at: 1, _updated_at: 1, _rperm: 1, _wperm: 1 }\n No query solutions",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "jobs"
      ],
      "extensions": {
        "code": 1,
        "exception": {
          "stacktrace": [
            "Error: MongoError: error processing query: ns=jobyfy-ci.Job limit=100Tree: $and",
            "    $or",
            "        _p_company $in [ \"Company$0CSE4ESsnH\" \"Company$4Raomvcy5j\" \"Company$4h1DawkhTf\" \"Company$682SLiAxPs\" \"Company$7cQxBOrmmh\" \"Company$7qqHWEH30i\" \"Company$8UvuVEENtN\" \"Company$9m814cmgJS\" \"Company$9xK7nECpzZ\" \"Company$BnbGxAleFJ\" \"Company$DAyVfxGW99\" \"Company$DOnH2AwE6x\" \"Company$DOqNyKyC4d\" \"Company$DTBOCTKcVK\" \"Company$E3TveaXl4t\" \"Company$HThCZJcJbE\" \"Company$HwV1aCE91u\" \"Company$IkCJG5k5IO\" \"Company$K4xwKfgCQD\" \"Company$OMr3pz3Wmk\" \"Company$P6c6RAMDSz\" \"Company$R3oODgB1Cj\" \"Company$S92mOwl0pL\" \"Company$UIJ95MDO2u\" \"Company$UaDjJS5ZTu\" \"Company$ZrOBdHjLZq\" \"Company$aBbtHkBqe5\" \"Company$drzWOkuOpq\" \"Company$h9uuVUq6Bo\" \"Company$hK3N7JJQrs\" \"Company$nra8zjlSlo\" \"Company$p3Y2OYofq3\" \"Company$rPzITYdlZ3\" \"Company$uNN7uDegsb\" \"Company$vbxuAfGFQD\" \"Company$wnzLHwPdNq\" ]",
            "        TEXT : query=bank, language=english, caseSensitive=0, diacriticSensitive=0, tag=NULL",
            "    $not",
            "        expired $eq true",
            "Sort: {}",
            "Proj: { title: 1, _p_company: 1, _id: 1, _created_at: 1, _updated_at: 1, _rperm: 1, _wperm: 1 }",
            " No query solutions",
            "    at toGraphQLError (/parse-server/lib/GraphQL/parseGraphQLUtils.js:33:10)",
            "    at ParseGraphQLSchema.handleError (/parse-server/lib/GraphQL/ParseGraphQLSchema.js:297:49)",
            "    at resolve (/parse-server/lib/GraphQL/loaders/parseClassQueries.js:140:30)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Basically, what  I want to achieve is a full-text search for the job's title, description text, and company name. Can you give me a direction on how to achieve this? Should a create an index or separate column with all these columns' values combined (it would mean a lot of data and duplication)?

**Comment by Moumouls** [comment]
To use text search in mongo you need to add indexes on your mongo text fields: https://stackoverflow.com/questions/48146146/text-search-with-or-results-in-no-query-solutions

https://docs.mongodb.com/manual/reference/operator/query/text/#behavior

**Comment by murshudov** [comment]
Thanks, @Moumouls! I'll give it a try.

**Comment by aacassandra** [comment]
> Please try the following and let me know:
> 
> ```graphql
> query {
>   jobs(
>     where: {
>       OR: [
>         { id: { equalTo: "Sm9iOnZhVkRHeENJa2I=" } }
>         { objectId: { equalTo: "6RCz5FRnd4" } }
>       ]
>     }
>   ) {
>     count
>     edges {
>       node {
>         id
>         objectId
>       }
>     }
>   }
> }
> ```

Thankyou, work well
