### ISSUE TITLE
Docker + Postgresql

### ISSUE THREAD

**Issue by DevDorrejo** [parse-community/parse-server#6782]
hello i have a instance of postgresql localhost, and what to use docker version with this, because on my distro the npm isnt working and using this system look more simple that using the others one:

`docker run --name sync-server -v cloud-code-vol:/sync-config/cloud -v config-vol:/sync-config/config -p 1337:1337 -d sync-server --appId application001 --masterKey Z/PF9aTlUSVye8/u7M/CuKc9SozlhlYBxCH2o1d1pjg= --databaseURI postgresql://sync:6K4ShIMN/IDgMsfYnhtl3DmBHo3l/RXUAN+O0xZQBro=@localhost --serverURL https://sync.server00.org`

Docker Log:
```
[1] parse-server running on https://sync.server00.org
MongoParseError: Invalid connection string
at parseConnectionString (/parse-server/node_modules/mongodb/lib/core/uri_parser.js:547:21)
at connect (/parse-server/node_modules/mongodb/lib/operations/connect.js:272:3)
at /parse-server/node_modules/mongodb/lib/mongo_client.js:218:5
at maybePromise (/parse-server/node_modules/mongodb/lib/utils.js:719:3)
at MongoClient.connect (/parse-server/node_modules/mongodb/lib/mongo_client.js:214:10)
at Function.MongoClient.connect (/parse-server/node_modules/mongodb/lib/mongo_client.js:432:22)
at MongoStorageAdapter.connect (/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:159:42)
at MongoStorageAdapter._schemaCollection (/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:214:17)
at MongoStorageAdapter.getAllClasses (/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:391:17)
at MongoStorageAdapter.updateSchemaWithIndexes (/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:913:17)
```

how to make the docker use postgres uri?

**Comment by cbaker6** [comment]
You URI should be something like (remove the "ql"):

```
--databaseURI postgres://sync:6K4ShIMN/IDgMsfYnhtl3DmBHo3l/RXUAN+O0xZQBro=@localhost
```

**Comment by DevDorrejo** [comment]
> Your URI should be something like (remove the "ql"):
> 
> ```
> --databaseURI postgres://sync:6K4ShIMN/IDgMsfYnhtl3DmBHo3l/RXUAN+O0xZQBro=@localhost
> ```
> 
> More details are in a PR for the docs. If you are using the latest parse-server from the master branch, you can use all of the options. If you are using 4.2 or below see the limitations in the docs: https://github.com/parse-community/docs/blob/1285886bcfcae47ca8b1850b8a8d45b8450e08fa/_includes/parse-server/database.md

thank you, now have this:

```
Error: getaddrinfo ENOTFOUND sync
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
errno: 'ENOTFOUND',
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'sync'
}
warn: Unable to ensure uniqueness for usernames: getaddrinfo ENOTFOUND sync {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"sync","stack":"Error: getaddrinfo ENOTFOUND sync\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
warn: Unable to create case insensitive username index: getaddrinfo ENOTFOUND sync {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"sync","stack":"Error: getaddrinfo ENOTFOUND sync\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
warn: Unable to ensure uniqueness for user email addresses: getaddrinfo ENOTFOUND sync {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"sync","stack":"Error: getaddrinfo ENOTFOUND sync\n   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
warn: Unable to create case insensitive email index: getaddrinfo ENOTFOUND sync {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"sync","stack":"Error: getaddrinfo ENOTFOUND sync\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
Error: getaddrinfo ENOTFOUND sync
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
errno: 'ENOTFOUND',
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'sync'
}
warn: Unable to ensure uniqueness for role name: getaddrinfo ENOTFOUND sync {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"sync","stack":"Error: getaddrinfo ENOTFOUND sync\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
```

**Comment by cbaker6** [comment]
Did you setup your parse database and credentials correctly in Postgres? Maybe [parse-hipaa](https://github.com/netreconlab/parse-hipaa) can help as the default “docker-compose up” is Postgres. You can modify the [setup-dbs.sh](https://github.com/netreconlab/parse-hipaa/blob/main/postgres/scripts/setup-dbs.sh) to setup your DB. If you need a non-hipaa one, you can use “docker-compose -f docker.compose.no.hipaa.yml up”

**Comment by DevDorrejo** [comment]
> Did you setup your parse database and credentials correctly in Postgres? Maybe [parse-hipaa](https://github.com/netreconlab/parse-hipaa) can help as the default “docker-compose up” is Postgres. You can modify the [setup-dbs.sh](https://github.com/netreconlab/parse-hipaa/blob/main/postgres/scripts/setup-dbs.sh) to setup your DB. If you need a non-hipaa one, you can use “docker-compose -f docker.compose.no.hipaa.yml up”

i can do `psql postgres://sync:123456@localhost/sync-server` from any user and will connect.

![image](https://user-images.githubusercontent.com/7697566/87216202-5c5ee180-c30b-11ea-853a-da4d7abd8e86.png)

**Comment by DevDorrejo** [comment]
i did this:

![image](https://user-images.githubusercontent.com/7697566/87216252-f32b9e00-c30b-11ea-89bb-c1a75cf33af7.png)

the user 
![image](https://user-images.githubusercontent.com/7697566/87216258-06d70480-c30c-11ea-887a-cba7b26d9a19.png)

The DB
![image](https://user-images.githubusercontent.com/7697566/87216275-2ff79500-c30c-11ea-9bf4-3d003ca209b6.png)

Extensions:
![image](https://user-images.githubusercontent.com/7697566/87216289-4867af80-c30c-11ea-9107-0bcbabee8b53.png)

**Comment by cbaker6** [comment]
If those are the only lines you did, I’m sure your Postgres isn’t setup correctly. You should look at the script in the previous post or if your Postgres is a docker also, something similar to [CONTRIBUTING.md](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#run-postgres-setup-for-parse-with-docker) which is running a script as well. Note the if you run the line in CONTRIBUTING parse-server will work with that Postgres image automatically with no changes needed

**Comment by DevDorrejo** [comment]
> If those are the only lines you did, I’m sure your Postgres isn’t setup correctly. You should look at the script in the previous post or if your Postgres is a docker also, something similar to [CONTRIBUTING.md](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#run-postgres-setup-for-parse-with-docker) which is running a script as well. Note the if you run the line in CONTRIBUTING parse-server will work with that Postgres image automatically with no changes needed.
> 
> Or you can modify the script I linked to earlier and run it on your instance of Postgres and then you should be able to connect

No. my only instance on docker is parse-server and with parser-hipaa i am getting the same error, and i want to know what is the config that postgres need to have to work, because i have others docker instance using the same URI and working, and the only program that is giving me problem is parse.

**Comment by cbaker6** [comment]
The configuration is the simple script. I sent links to the same scripts used to test the parse-server repo. If parse-hipaa doesn't run correctly, then it's your Postgres setup that's the issue. Just like the parse-server repo, I use the official postgis image which is derived from the official Postgres image. Even if you don't have postgis setup, parse-server will still work and will only error on location queries.

What version of parse-server are you using? 

Does parse-hipaa work using the Postgres image that comes with it?

**Comment by cbaker6** [comment]
Can you also show the command you use to start your Postgres image? It doesn’t look like you binded your Postgres to localhost:5432 but you are trying to connect your parse-server to it. If you are using a yml file like parse-hipaa you should be connecting to the name of the image, “db” in the case of parse-hipaa, not “localhost”

**Comment by DevDorrejo** [comment]
> Can you also show the command you use to start your Postgres image? It doesn’t look like you binded your Postgres to localhost:5432 but you are trying to connect your parse-server to it. If you are using a yml file like parse-hipaa you should be connecting to the name of the image, “db” in the case of parse-hipaa, not “localhost”

hello the postgres is not on a container, is on the host here come new logs:

**Parse-Hiipa**
```
**docker logs sync-parse_scan_1** 
Sat Jul 11 04:36:40 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Jul 11 04:36:40 2020 -> Limits: Global size limit set to 157286400 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: File size limit set to 31457280 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: Recursion level limit set to 10.
Sat Jul 11 04:36:40 2020 -> Limits: Files limit set to 15000.
Sat Jul 11 04:36:40 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Jul 11 04:36:40 2020 -> Limits: MaxPartitions limit set to 128.
Sat Jul 11 04:36:40 2020 -> Limits: MaxIconsPE limit set to 200.
Sat Jul 11 04:36:40 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Jul 11 04:36:40 2020 -> Limits: PCREMatchLimit limit set to 10000.
Sat Jul 11 04:36:40 2020 -> Limits: PCRERecMatchLimit limit set to 10000.
Sat Jul 11 04:36:40 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Jul 11 04:36:40 2020 -> Archive support enabled.
Sat Jul 11 04:36:40 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Jul 11 04:36:40 2020 -> Heuristic alerts enabled.
Sat Jul 11 04:36:40 2020 -> Portable Executable support enabled.
Sat Jul 11 04:36:40 2020 -> ELF support enabled.
Sat Jul 11 04:36:40 2020 -> Alerting on broken executables enabled.
Sat Jul 11 04:36:40 2020 -> Mail files support enabled.
Sat Jul 11 04:36:40 2020 -> OLE2 support enabled.
Sat Jul 11 04:36:40 2020 -> PDF support enabled.
Sat Jul 11 04:36:40 2020 -> SWF support enabled.
Sat Jul 11 04:36:40 2020 -> HTML support enabled.
Sat Jul 11 04:36:40 2020 -> XMLDOCS support enabled.
Sat Jul 11 04:36:40 2020 -> HWP3 support enabled.
Sat Jul 11 04:36:40 2020 -> Self checking every 600 seconds.
Sat Jul 11 04:36:40 2020 -> Set stacksize to 1048576
Sat Jul 11 04:46:40 2020 -> SelfCheck: Database status OK.
Sat Jul 11 04:53:08 2020 -> Pid file removed.
Sat Jul 11 04:53:08 2020 -> --- Stopped at Sat Jul 11 04:53:08 2020
Sat Jul 11 04:53:08 2020 -> Socket file removed.
Sat Jul 11 04:56:37 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Jul 11 04:56:37 2020 -> Limits: Global size limit set to 157286400 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: File size limit set to 31457280 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: Recursion level limit set to 10.
Sat Jul 11 04:56:37 2020 -> Limits: Files limit set to 15000.
Sat Jul 11 04:56:37 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Jul 11 04:56:37 2020 -> Limits: MaxPartitions limit set to 128.
Sat Jul 11 04:56:37 2020 -> Limits: MaxIconsPE limit set to 200.
Sat Jul 11 04:56:37 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Jul 11 04:56:37 2020 -> Limits: PCREMatchLimit limit set to 10000.
Sat Jul 11 04:56:37 2020 -> Limits: PCRERecMatchLimit limit set to 10000.
Sat Jul 11 04:56:37 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Jul 11 04:56:37 2020 -> Archive support enabled.
Sat Jul 11 04:56:37 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Jul 11 04:56:37 2020 -> Heuristic alerts enabled.
Sat Jul 11 04:56:37 2020 -> Portable Executable support enabled.
Sat Jul 11 04:56:37 2020 -> ELF support enabled.
Sat Jul 11 04:56:37 2020 -> Alerting on broken executables enabled.
Sat Jul 11 04:56:37 2020 -> Mail files support enabled.
Sat Jul 11 04:56:37 2020 -> OLE2 support enabled.
Sat Jul 11 04:56:37 2020 -> PDF support enabled.
Sat Jul 11 04:56:37 2020 -> SWF support enabled.
Sat Jul 11 04:56:37 2020 -> HTML support enabled.
Sat Jul 11 04:56:37 2020 -> XMLDOCS support enabled.
Sat Jul 11 04:56:37 2020 -> HWP3 support enabled.
Sat Jul 11 04:56:37 2020 -> Self checking every 600 seconds.
Sat Jul 11 04:56:37 2020 -> Set stacksize to 1048576
Sat Jul 11 04:57:11 2020 -> Pid file removed.
Sat Jul 11 04:57:11 2020 -> --- Stopped at Sat Jul 11 04:57:11 2020
Sat Jul 11 04:57:11 2020 -> Socket file removed.
Sat Jul 11 04:57:36 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Jul 11 04:57:36 2020 -> Limits: Global size limit set to 157286400 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: File size limit set to 31457280 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: Recursion level limit set to 10.
Sat Jul 11 04:57:36 2020 -> Limits: Files limit set to 15000.
Sat Jul 11 04:57:36 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Jul 11 04:57:36 2020 -> Limits: MaxPartitions limit set to 128.
Sat Jul 11 04:57:36 2020 -> Limits: MaxIconsPE limit set to 200.
Sat Jul 11 04:57:36 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Jul 11 04:57:36 2020 -> Limits: PCREMatchLimit limit set to 10000.
Sat Jul 11 04:57:36 2020 -> Limits: PCRERecMatchLimit limit set to 10000.
Sat Jul 11 04:57:36 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Jul 11 04:57:36 2020 -> Archive support enabled.
Sat Jul 11 04:57:36 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Jul 11 04:57:36 2020 -> Heuristic alerts enabled.
Sat Jul 11 04:57:36 2020 -> Portable Executable support enabled.
Sat Jul 11 04:57:36 2020 -> ELF support enabled.
Sat Jul 11 04:57:36 2020 -> Alerting on broken executables enabled.
Sat Jul 11 04:57:36 2020 -> Mail files support enabled.
Sat Jul 11 04:57:36 2020 -> OLE2 support enabled.
Sat Jul 11 04:57:36 2020 -> PDF support enabled.
Sat Jul 11 04:57:36 2020 -> SWF support enabled.
Sat Jul 11 04:57:36 2020 -> HTML support enabled.
Sat Jul 11 04:57:36 2020 -> XMLDOCS support enabled.
Sat Jul 11 04:57:36 2020 -> HWP3 support enabled.
Sat Jul 11 04:57:36 2020 -> Self checking every 600 seconds.
Sat Jul 11 04:57:36 2020 -> Set stacksize to 1048576
Sat Jul 11 04:58:38 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Jul 11 04:58:38 2020 -> Limits: Global size limit set to 157286400 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: File size limit set to 31457280 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: Recursion level limit set to 10.
Sat Jul 11 04:58:38 2020 -> Limits: Files limit set to 15000.
Sat Jul 11 04:58:38 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Jul 11 04:58:38 2020 -> Limits: MaxPartitions limit set to 128.
Sat Jul 11 04:58:38 2020 -> Limits: MaxIconsPE limit set to 200.
Sat Jul 11 04:58:38 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Jul 11 04:58:38 2020 -> Limits: PCREMatchLimit limit set to 10000.
Sat Jul 11 04:58:38 2020 -> Limits: PCRERecMatchLimit limit set to 10000.
Sat Jul 11 04:58:38 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Jul 11 04:58:38 2020 -> Archive support enabled.
Sat Jul 11 04:58:38 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Jul 11 04:58:38 2020 -> Heuristic alerts enabled.
Sat Jul 11 04:58:38 2020 -> Portable Executable support enabled.
Sat Jul 11 04:58:38 2020 -> ELF support enabled.
Sat Jul 11 04:58:38 2020 -> Alerting on broken executables enabled.
Sat Jul 11 04:58:38 2020 -> Mail files support enabled.
Sat Jul 11 04:58:38 2020 -> OLE2 support enabled.
Sat Jul 11 04:58:38 2020 -> PDF support enabled.
Sat Jul 11 04:58:38 2020 -> SWF support enabled.
Sat Jul 11 04:58:38 2020 -> HTML support enabled.
Sat Jul 11 04:58:38 2020 -> XMLDOCS support enabled.
Sat Jul 11 04:58:38 2020 -> HWP3 support enabled.
Sat Jul 11 04:58:38 2020 -> Self checking every 600 seconds.
Sat Jul 11 04:58:38 2020 -> Set stacksize to 1048576
Sat Jul 11 05:02:22 2020 -> Pid file removed.
Sat Jul 11 05:02:22 2020 -> --- Stopped at Sat Jul 11 05:02:22 2020
Sat Jul 11 05:02:22 2020 -> Socket file removed.
```
```
**docker logs sync-parse_db_1** 

PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-07-11 04:56:20.661 UTC [1] LOG:  pgaudit extension initialized
2020-07-11 04:56:20.661 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-07-11 04:56:20.677 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-07-11 04:56:20.677 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-07-11 04:56:20.919 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-07-11 04:56:21.030 UTC [1] LOG:  redirecting log output to logging collector process
2020-07-11 04:56:21.030 UTC [1] HINT:  Future log output will appear in directory "log".

PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-07-11 04:57:16.462 UTC [1] LOG:  pgaudit extension initialized
2020-07-11 04:57:16.462 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-07-11 04:57:16.462 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-07-11 04:57:16.462 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-07-11 04:57:16.550 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-07-11 04:57:16.669 UTC [1] LOG:  redirecting log output to logging collector process
2020-07-11 04:57:16.669 UTC [1] HINT:  Future log output will appear in directory "log".

PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-07-11 04:58:17.689 UTC [1] LOG:  pgaudit extension initialized
2020-07-11 04:58:17.689 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-07-11 04:58:17.689 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-07-11 04:58:17.690 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-07-11 04:58:17.796 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-07-11 04:58:17.910 UTC [1] LOG:  redirecting log output to logging collector process
2020-07-11 04:58:17.910 UTC [1] HINT:  Future log output will appear in directory "log".
```
```
**docker logs sync-parse_dashboard_1** 
Iconsfolder at path: /src/Parse-Dashboard/icons not found!
The dashboard is now available at http://0.0.0.0:4040/dashboard
server stopped by SIGTERM
Iconsfolder at path: /src/Parse-Dashboard/icons not found!
The dashboard is now available at http://0.0.0.0:4040/dashboard
server stopped by SIGTERM
Iconsfolder at path: /src/Parse-Dashboard/icons not found!
The dashboard is now available at http://0.0.0.0:4040/dashboard
server stopped by SIGTERM
```

**Parse-Server**
```
**docker logs sync-server** 
allowClientClassCreation: true
appId: midori-next
cacheMaxSize: 10000
cacheTTL: 5000
customPages: {}
databaseURI: postgres://sync:f182287e3b208744d5aac021@localhost/sync-server
enableAnonymousUsers: true
expireInactiveSessions: true
graphQLPath: /graphql
host: 0.0.0.0
logsFolder: ./logs
masterKey: ***REDACTED***
masterKeyIps: []
maxUploadSize: 20mb
mountPath: /parse
objectIdSize: 10
playgroundPath: /playground
port: 1337
protectedFields: {"_User":{"*":["email"]}}
revokeSessionOnPasswordReset: true
schemaCacheTTL: 5000
sessionLength: 31536000
allowCustomObjectId: false
collectionPrefix:
directAccess: false
enableExpressErrorHandler: false
enableSingleSchemaCache: false
mountGraphQL: false
mountPlayground: false
preserveFileName: false
preventLoginWithUnverifiedEmail: false
scheduledPush: false
verifyUserEmails: false
jsonLogs: false
verbose: false
level: undefined
serverURL: http://localhost:1337/parse

[1] parse-server running on http://localhost:1337/parse
Error: connect ECONNREFUSED 127.0.0.1:5432
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 5432
}
warn: Unable to ensure uniqueness for usernames: connect ECONNREFUSED 127.0.0.1:5432 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"}
warn: Unable to create case insensitive username index: connect ECONNREFUSED 127.0.0.1:5432 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"}
warn: Unable to ensure uniqueness for user email addresses: connect ECONNREFUSED 127.0.0.1:5432 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"}
warn: Unable to create case insensitive email index: connect ECONNREFUSED 127.0.0.1:5432 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"}
warn: Unable to ensure uniqueness for role name: connect ECONNREFUSED 127.0.0.1:5432 {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"}
Error: connect ECONNREFUSED 127.0.0.1:5432
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
errno: 'ECONNREFUSED',
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 5432
}
```

**Comment by DevDorrejo** [comment]
Solution to connect docker with postgresql, localhost.

first on docker use the param --network=host.

second:
do this config.
![image](https://user-images.githubusercontent.com/7697566/88468091-9eac2500-ceac-11ea-9297-4ed46c22554d.png)

**Comment by chrisk8er** [comment]
hi @DevDorrejo i have same issue. can you give me the details to fix this problem? thanks

**Comment by DevDorrejo** [comment]
> hi @DevDorrejo i have same issue. can you give me the details to fix this problem? thanks

Hello, sorry for the late answer, here is how i have configure the docker and posgresql:

docker run -t  \
           -d  \
           --name parse-server \
           --network parse_net  \
           parseplatform/parse-server \
           --host 127.0.0.1    \
           --appName a_Name \
           --appId a_Id \
           --masterKey m_Key \
           --clientKey c_Key \
           --fileKey f_Key  \
           --javascriptKey js_Key \
           --restAPIKey rest_Key \
           --verbose \
           --databaseURI postgres://user:password@docker_ip (172.17.0.1 (default or look using ip a show docker0):5432/db_name \
           --serverURL http://localhost:1337/parse \
           --publicServerURL http://domain_name/parse

![image](https://user-images.githubusercontent.com/7697566/89130466-14c71200-d4d3-11ea-87e3-efa85b44bb98.png)
Appear 172.18.0.0/16, because i create a network for parse.

![image](https://user-images.githubusercontent.com/7697566/89130477-2f998680-d4d3-11ea-9a8c-66cb0e642bf9.png)
Here will listen all, but i am searching what parameter will be need to work, without using the flag *

for last, you will need to open the port of postgresql to made it work or do the connection.

other way and more simple, is using --network host, you wont need modify nothing about postgresql
