### ISSUE TITLE
query.exclude()  gives error but no additional logs.

### ISSUE THREAD

**Issue by uzaysan** [parse-community/parse-server#6801]
Hi. When I use exclude method in my cloud code, I get this error with no additional logs:

```
{"code":141,"level":"error","stack":"Error\n    at error (/root/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at runMicrotasks (<anon$
{"functionName":"getHomeObjects","error":{"code":141},"params":{},"user":"Tw8o5jj3DJ","level":"error","message":"Failed running cloud function getHomeObjects for u$
```

This is console log:

```
Input: {}
  Error: {"code":141} {"functionName":"getHomeObjects","error":{"code":141},"params":{},"user":"Tw8o5jj3DJ"}
error: Parse error:  {"code":141,"stack":"Error\n    at error (/root/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:121:16)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
error: Failed running cloud function getHomeObjects for user Tw8o5jj3DJ with:
```

This error happens only when I use `exclude` method on queries. I use exclude method to exclude some array list from obbject

For example:
query.exclude("words");

The thing is this happens random. I have other cloud codes which uses same query but on different Class. It works but some other class it doesn't work.

I formatted my server and did a clean install but I still got the error.

My parse server version is 4.2.0
My MongoDB version is also 4.2.0
Database is in localhost.

**Comment by davimacedo** [comment]
Would you be able to create a failing test case and/or send us the steps to reproduce the problem?

**Comment by uzaysan** [comment]
Hi Davi. I observed that this error only happens if class is not created and  using exclude method.

This is an example simple query:
```
const Post = Parse.Object.extend("Post");

const getPosts = new Parse.Query(Post);

getPosts.include("user");
getPosts.exclude("words");

const result = await getPosts.find();
```

Remember, Post class is not exist. When I use exclude method this code throws an error. But If I remove exclude, this code simply returns empty array.


When I create class Post manually, code doesn't throw an error and returns empty array.


İf I call cloud code from rest api, I only get error 141. But I tried running above example query in JS Console in dashboard. This is the error I get:
```
"Error":{3 items
"message":string"Received an error with invalid JSON from Parse: Cannot GET /parse/classes/Post "
"name":string"Error"
"stack":string"Error: Received an error with invalid JSON from Parse: Cannot GET /parse/classes/Post at handleError (http://0.0.0.0:4040/bundles/dashboard.bundle.js:75:674377) at async eval (eval at <anonymous> (http://0.0.0.0:4040/bundles/dashboard.bundle.js:95:1054146), <anonymous>:16:16)"
```

This error propably related to dashboard.
