### ISSUE TITLE
[Heroku][iOS] The data couldn’t be read because it isn’t in the correct format 

### ISSUE THREAD

**Issue by omarojo** [parse-community/parse-server#6860]
### Issue Description
in iOS Im calling `saveInBackground` for a large file (~80mb). 
I get: 
  
```
(lldb) po task.error
▿ Optional<Error>
  - some : Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

(lldb) po task.error?.localizedDescription
▿ Optional<String>
  - some : "The data couldn’t be read because it isn’t in the correct format."
```
I set *VERBOSE=1* env variable in Heroku. 
and all I get printed in Heroku live Log is:

```
2020-08-13T08:46:10.550226+00:00 app[web.1]: BadRequestError: request aborted
2020-08-13T08:46:10.550236+00:00 app[web.1]:     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10)
2020-08-13T08:46:10.550237+00:00 app[web.1]:     at IncomingMessage.emit (events.js:314:20)
2020-08-13T08:46:10.550239+00:00 app[web.1]:     at IncomingMessage.EventEmitter.emit (domain.js:486:12)
2020-08-13T08:46:10.550240+00:00 app[web.1]:     at abortIncoming (_http_server.js:535:9)
2020-08-13T08:46:10.550240+00:00 app[web.1]:     at socketOnClose (_http_server.js:528:3)
2020-08-13T08:46:10.550241+00:00 app[web.1]:     at Socket.emit (events.js:326:22)
2020-08-13T08:46:10.550241+00:00 app[web.1]:     at Socket.EventEmitter.emit (domain.js:486:12)
2020-08-13T08:46:10.550242+00:00 app[web.1]:     at TCP.<anonymous> (net.js:673:12)
2020-08-13T08:46:10.547959+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/parse/files/G8VIDEO.mp4" host=generate-parse-dev.herokuapp.com request_id=84b5949c-9660-4729-afc3-2399b7026935 fwd="45.44.67.73" dyno=web.1 connect=52ms service=60031ms status=503 bytes=0 protocol=https
```

**Everything else works fine. I can upload Images and other small videos just fine, but when I try to upload larger files I get the above**. I did put the proper config settings in the server app: 
```
  maxUploadSize: "100mb",
  filesAdapter: new S3Adapter(
    process.env.S3_ACCESS_KEY,
    process.env.S3_SECRET_KEY,
    process.env.S3_BUCKET,
    { directAccess: true }
  )
```

###  Environment

Server
- Parse version:
```
    "express": "~4.11.x" 
    "parse": "2.11.0",
    "parse-dashboard": "2.1.0",
    "parse-image": "0.3.0",
    "parse-server": "4.2.0"
```
- Operating system: `heroku-18`
- remote host: `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Local or remote host :`MongoDB Atlas`

Client
- SDK `iOS`
- SDK version: `1.18`

**Comment by mtrezza** [comment]
> service=60031ms

Lookin at the logs the upload stops after ~60s which usually points to a timeout. I suggest to inquire with Heroku about a possible POST request timeout.

I'm closing this as it does not seem to be a Parse Server issue.
Feel free to comment if you have any questions and we can re-open this issue.

**Comment by omarojo** [comment]
@mtrezza 
From what I read in [Heroku Documentation regarding Timeouts](https://devcenter.heroku.com/articles/request-timeout)
The timeout is 30s and is not configurable. They really expect you to process everything within that time frame. 
Also because from what I understand, it may block other http requests from other users.

**So... is Parse designed to work that way ? I mean if I understand correctly, we shouldnt upload large files via Parse. 
or pretty much any file that takes more than 30s to upload and process the request. Am I right ?**

Heroku mentions that large files [should be uploaded separately](https://devcenter.heroku.com/articles/request-timeout#uploading-large-files) and directly to AWS.  

And [here](https://devcenter.heroku.com/articles/s3#direct-upload) they talk about **passthrough upload** which I think that's what Parse does. But that sounds like is definitely prompt to fail pretty easily if User has slow internet or the file is too large, that can trigger the timeout, in which case there is nothing we can do.
