### ISSUE TITLE
CI: Facebook auth adapter tests failing with invalid hostname graph.accountkit.com

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server#6867]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
2 tests are failing in `AuthenticationAdapter.spec.js` regarding Facebook auth adapter.

### Steps to reproduce
See tests.

### Actual Outcome
Tests should pass.

### Expected Outcome
Tests fail with error:
```
"Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: graph.accountkit.com. is not in the cert's altnames: DNS:*.facebook.com, DNS:*.facebook.net, DNS:*.fbcdn.net, DNS:*.fbsbx.com, DNS:*.messenger.com, DNS:facebook.com, DNS:messenger.com, DNS:*.m.facebook.com, DNS:*.xx.fbcdn.net, DNS:*.xy.fbcdn.net, DNS:*.xz.fbcdn.net\n    at Object.checkServerIdentity (tls.js:287:12)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1508:27)\n    at TLSSocket.emit (events.js:314:20)\n    at TLSSocket.EventEmitter.emit (domain.js:486:12)\n    at TLSSocket._finishInit (_tls_wrap.js:933:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:707:12)\n    at TLSWrap.topLevelDomainCallback (domain.js:138:15)\n    at TLSWrap.callbackTrampoline (internal/async_hooks.js:121:14)"
```

It seems that the domain `graph.accountkit.com` is not listed as alternative domain in the certificate. This would point to an issue on FB's side, but it is more likely that the domain `graph.accountkit.com` we are using is either invalid or deprecated.

###  Environment
Travis Ci

Server
- Parse Server version: `4.3.0`
- Operating system: `-`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `-`

Database
- System (MongoDB or Postgres): `-`
- Database version: `-`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `-`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `-`
- SDK version: `-`

### Logs
```js
Failures:
3441) AuthenticationProviders should fail to validate Facebook accountkit auth with bad token
345  Message:
346    Expected 'ERR_TLS_CERT_ALTNAME_INVALID' to be 190.
347  Stack:
348    Error: Expected 'ERR_TLS_CERT_ALTNAME_INVALID' to be 190.
349        at <Jasmine>
350        at adapter.validateAuthData.then (/home/travis/build/parse-community/parse-server/spec/AuthenticationAdapters.spec.js:564:24)
351        at process._tickCallback (internal/process/next_tick.js:68:7)
352  Message:
353    Expected undefined to be 'OAuthException'.
354  Stack:
355    Error: Expected undefined to be 'OAuthException'.
356        at <Jasmine>
357        at adapter.validateAuthData.then (/home/travis/build/parse-community/parse-server/spec/AuthenticationAdapters.spec.js:565:24)
358        at process._tickCallback (internal/process/next_tick.js:68:7)
359
3602) AuthenticationProviders should fail to validate Facebook accountkit auth with bad token regardless of app secret proof
361  Message:
362    Expected 'ERR_TLS_CERT_ALTNAME_INVALID' to be 190.
363  Stack:
364    Error: Expected 'ERR_TLS_CERT_ALTNAME_INVALID' to be 190.
365        at <Jasmine>
366        at adapter.validateAuthData.then (/home/travis/build/parse-community/parse-server/spec/AuthenticationAdapters.spec.js:588:26)
367        at process._tickCallback (internal/process/next_tick.js:68:7)
368  Message:
369    Expected undefined to be 'OAuthException'.
370  Stack:
371    Error: Expected undefined to be 'OAuthException'.
372        at <Jasmine>
373        at adapter.validateAuthData.then (/home/travis/build/parse-community/parse-server/spec/AuthenticationAdapters.spec.js:589:26)
374        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dplewis** [comment]
Looks like account kit is no longer available. Can anybody double check this? We can remove it from the project.

https://developers.facebook.com/blog/post/2019/09/09/account-kit-services-no-longer-available-starting-march/
