### ISSUE TITLE
Invalid date iso with beforeSave make server unhandled promise rejection and request hanging 

### ISSUE THREAD

**Issue by sunshineo** [parse-community/parse-server#7192]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).

### Issue Description
Have a class with a column type Date. Try post with empty string as iso. Get proper error back
```
{
    "code": 111,
    "error": "This is not a valid Date"
}
```
Add beforeSave to the class and post again. Request will hang there forever. Server will fail with the following errors
```
(node:63110) UnhandledPromiseRejectionWarning: Error: Tried to encode an invalid date.
    at encode (/Users/gordon/workspace/pipe17/pipe17-group/parse/node_modules/parse/lib/node/encode.js:85:13)
    at _default (/Users/gordon/workspace/pipe17/pipe17-group/parse/node_modules/parse/lib/node/encode.js:132:10)
    at SetOp.toJSON (/Users/gordon/workspace/pipe17/pipe17-group/parse/node_modules/parse/lib/node/ParseOp.js:155:32)
    at ParseObject._getSaveJSON (/Users/gordon/workspace/pipe17/pipe17-group/parse/node_modules/parse/lib/node/ParseObject.js:485:61)
    at success (/Users/gordon/workspace/pipe17/pipe17-group/parse/node_modules/parse-server/lib/triggers.js:385:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
```

- [x] 🤩 I will submit a PR with a fix

###  Environment
Server
- Parse Server version: 4.5.0

**Comment by mtrezza** [comment]
Thanks for reporting.

Can you please add a code example to demonstrate the issue you are referring to?

**Comment by sunshineo** [comment]
Not sure how to provide a code example to setup class with Date and beforeSave and post with invalid date. But anyone read my description should be able to reproduce on their server

**Comment by dplewis** [comment]
How did you save an empty iso date?

**Comment by mtrezza** [comment]
This may he related to https://github.com/parse-community/parse-server/pull/7087, but without a proper code example we'll have to close this issue due to lack of details.

**Comment by sunshineo** [comment]
I still have no time to learn the test system. So I spent half an hour to setup a project to demo the bug
https://github.com/sunshineo/parse-bug-demo
I hope the README.md is enough, but I can answer any questions

**Comment by mtrezza** [comment]
@sunshineo Thanks, this is actually all that was needed:

```
# Valid iso works in both classes
curl --location --request POST 'http://localhost:1337/parse/classes/MyClass1' \
--header 'x-parse-application-id: myAppId' \
--header 'x-parse-master-key: masterKey' \
--header 'Content-Type: application/json' \
--data-raw '{"field":{"__type":"Date", "iso":"2021-02-19T01:18:45.062Z"}}'

curl --location --request POST 'http://localhost:1337/parse/classes/MyClass2' \
--header 'x-parse-application-id: myAppId' \
--header 'x-parse-master-key: masterKey' \
--header 'Content-Type: application/json' \
--data-raw '{"field":{"__type":"Date", "iso":"2021-02-19T01:18:45.062Z"}}'


# Empty iso not working in MyClass1 with proper error
curl --location --request POST 'http://localhost:1337/parse/classes/MyClass1' \
--header 'x-parse-application-id: myAppId' \
--header 'x-parse-master-key: masterKey' \
--header 'Content-Type: application/json' \
--data-raw '{"field":{"__type":"Date", "iso": ""}}'

# Empty iso will stuck forever for MyClass2
curl --location --request POST 'http://localhost:1337/parse/classes/MyClass2' \
--header 'x-parse-application-id: myAppId' \
--header 'x-parse-master-key: masterKey' \
--header 'Content-Type: application/json' \
--data-raw '{"field":{"__type":"Date", "iso": ""}}'
```

**Comment by sunshineo** [comment]
No, MyClass2 has a beforeSave trigger, and that makes it stuck

**Comment by sunshineo** [comment]
```
# Empty iso not working in MyClass1 (returns immediately) with proper error
# Empty iso will stuck forever (until curl client timeout) for MyClass2 (because it has a beforeSave)
```

**Comment by mtrezza** [comment]
I was able to reproduce the error throwing instead of promise rejection in #7217.

**Comment by sunshineo** [comment]
@mtrezza I have a fix. I have a pull request https://github.com/parse-community/parse-server/pull/7193
It's submitted before your test case. So is there a way to re-run the test and see if this fix make the test pass?

**Comment by mtrezza** [comment]
You could simply add the test to your PR.

**Comment by sunshineo** [comment]
Just tried locally. My fix does not pass your test because it gives a different error message

Instead of `111 This is not a valid Date`, it is `142 Tried to encode an invalid date.`. I do not see any strong reason that we have to have 111 instead of 142. So I'll change the expected error message in the test and put it on my PR.

Detail output of the test 
```
Failures:
1) beforeSave hooks rejects saving with invalid iso date and beforeSave hook (#7192)
  Message:
    Expected a promise to be rejected with ParseError: 111 This is not a valid Date but it was rejected with Error: Tried to encode an invalid date..
  Stack:
    Error
        at <Jasmine>
        at UserContext.<anonymous> (/Users/gordon/workspace/forks/parse-server/spec/CloudCode.spec.js:1826:37)
        at <Jasmine>
        at /Users/gordon/workspace/forks/parse-server/spec/helper.js:192:7
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
  Message:
    Expected a promise to be rejected with ParseError: 111 This is not a valid Date but it was rejected with ParseError: 142 Tried to encode an invalid date..
  Stack:
    Error
        at <Jasmine>
        at UserContext.<anonymous> (/Users/gordon/workspace/forks/parse-server/spec/CloudCode.spec.js:1826:37)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
  Message:
    Expected a promise to be rejected with ParseError: 111 This is not a valid Date but it was rejected with ParseError: 142 Tried to encode an invalid date..
  Stack:
    Error
        at <Jasmine>
        at UserContext.<anonymous> (/Users/gordon/workspace/forks/parse-server/spec/CloudCode.spec.js:1826:37)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by sunshineo** [comment]
I have updated my PR

**Comment by mtrezza** [comment]
> I do not see any strong reason that we have to have 111 instead of 142. So I'll change the expected error message in the test and put it on my PR.

Let's discuss the PR in the PR thread.
