### ISSUE TITLE
Cannot read .indexOf undefined on matchesKeyConstraints when attribute missing

### ISSUE THREAD

**Issue by jdposthuma** [parse-community/parse-server#7416]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When an object is missing an expected attribute, an unhandled error occurs. 

### Steps to reproduce
To be honest, I'm not sure how objects are getting malformed.

This issue is causing a crash my `LiveQueryServer` that listens for live queries using `ParseServer.createLiveQueryServer`.

### Actual Outcome
Because it's outside of the context of an Express.js request, the entire node process crashes.

### Expected Outcome
I'm expecting it not to crash

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Debian`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `n/a`

**Comment by mtrezza** [comment]
Thanks for reporting.

Can you add more details, like a code example to reproduce the issue and logs?

**Comment by jdposthuma** [comment]
Logs:
```
TypeError: Cannot read property 'indexOf' of undefined
at matchesKeyConstraints (/app/node_modules/parse-server/src/LiveQuery/QueryTools.js:253:27)
at matchesQuery (/app/node_modules/parse-server/src/LiveQuery/QueryTools.js:129:10)
at ParseLiveQueryServer._matchesSubscription (/app/node_modules/parse-server/src/LiveQuery/ParseLiveQueryServer.js:412:12)
at ParseLiveQueryServer._onAfterSave (/app/node_modules/parse-server/src/LiveQuery/ParseLiveQueryServer.js:211:49)
at RedisClient.<anonymous> (/app/node_modules/parse-server/src/LiveQuery/ParseLiveQueryServer.js:84:14)
at RedisClient.emit (events.js:376:20)
at RedisClient.emit (domain.js:470:12)
at return_pub_sub (/app/node_modules/redis/index.js:714:18)
at RedisClient.return_reply (/app/node_modules/redis/index.js:761:9)
at JavascriptRedisParser.returnReply (/app/node_modules/redis/index.js:137:18)
```

I'm sure which object this is is crashing on as it's in the context of the live query server.

**Comment by mtrezza** [comment]
Can you add a minimal code example to reproduce the issue?

**Comment by jdposthuma** [comment]
@mtrezza - I'm actually not sure which of our parse classes is creating this issue. I've submitted a PR that will perform a truthy check on the attribute to very its existence.

**Comment by mtrezza** [comment]
@jdposthuma Can this issue be closed with the merge of #7421?

**Comment by mtrezza** [comment]
I classified this as bug of low severity due to the missing test case verification.
