### ISSUE TITLE
Invalid Session response after upgrade

### ISSUE THREAD

**Issue by michaelilic** [parse-community/parse-server#7581]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I've updated my parse server JS sdk to the latest versions and I'm quite often getting an invalid session error now. For my setup I am having customers purchase something and I am storing the purchased product, which is a parse object, as a JSON representation with each purchase. This is done so that I have the exact purchased product at the time of the purchase. Additionally, I have FAQs and Tags attached to my product as an array of pointers. These are fetched and also stored with the purchase object.

After updating to the latest parse server and js sdk version, the invalid session token error keeps popping up. In my console output I see that parse always uses an old specific session token that is not valid anymore. It looks like once I query purchases and parse sees my user either in the tags, faqs or somewhere else in the purchase it returns the data with the old session token in there. The client parse js sdk then falsely uses that expired token for its next request which then fails.

### Steps to reproduce

1. Have class like tags with a author field and your userid as a pointer in it. 
2. Use another class called items and link to the tags as an array of pointers. 
3. Create a purchases class and have a field that stores objects.
4. fetch the array of pointers on the item class with include and store the completely fetched object in the purchases class.
5. Delete all sessions and log in again
6. Query the purchases class and display the data
7. Query something else and you get an invalid session token response

### Actual Outcome

Invalid Session error for the next request. Upon reloading the page it works again.
{"message":"Parse error:  Invalid session token","code":209,"level":"error","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (/var/www/vhosts/programmieren-muenchen.de/parse/server/node_modules/parse-server/lib/Auth.js:114:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}

### Expected Outcome

Continue using the session token that was created upon login and is stored in the browser localstorage.

### Environment

Server:
Node v14.17.3
Parse 3.3.0
Parse-Server 4.10.3
Running on an express server with ubuntu 18.04

Client:
Nuxt 2.13.3
Parse 3.2.0

Server
- Parse Server version: 3.3.0
- Operating system: Ubuntu 18.04
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Remote Ubuntu vhost Server

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.4
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Remote Ubuntu vhost Server

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): JavaScript
- SDK version: 3.2.0

### Logs

{"message":"Parse error:  Invalid session token","code":209,"level":"error","stack":"Error: Invalid session token\n    at Object.getAuthForSessionToken (/var/www/vhosts/programmieren-muenchen.de/parse/server/node_modules/parse-server/lib/Auth.js:114:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"}

**Comment by mtrezza** [comment]
Are you saying that parse server returns an expired session token after upgrading? Can you reproduce this reliably?

**Comment by michaelilic** [comment]
> Are you saying that parse server returns an expired session token after upgrading? Can you reproduce this reliably with a failing test in a PR?

Hey there. There seems to be an issue that popped up after upgrading to the latest version. I couldn't find anything in the release notes so I figured I add this here.
My parse client is using an old expired token for the next request to parse server when the old query has an old sessiontoken stored somewhere in an object. What I also find strange that parse adds the sessiontoken to my user object even if I try to remove it like: convert the user object to json with the toJSON() function, then delete the user.sessionToken and add back user.__type = 'Object' and user.className = '_User'. On the client my user object still has the sessiontoken attached again.

I will work on a failing test in PR as soon as I can.

**Comment by michaelilic** [comment]
My understanding of how Parse Server works seems not to be good enough to reproduce my error. I have a Cloud function that fetches all Users that I have, which on my client has the sessionToken set for my user. During testing this is not the case. Can this be the case due to server configuration?

My cloud code is:
`module.exports.fetchAllUsers = function(Parse) {
	return async(request) => {
		if (request.master) {
			// Master Key is set, allow function to run
		} else {
			// Make sure only admin can run this
			if (!request.user) return Promise.reject('Only logged in users can use this.');
			else {
				// Check if user is admin
				const roleQuery = new Parse.Query(Parse.Role);
				roleQuery.equalTo('name', 'admin');
				roleQuery.equalTo('users', request.user);
				const userRole = await roleQuery.first({ useMasterKey: true });
				if (!userRole) {
					return Promise.reject('Not authorized');
				}
				// Function called by user that is admin
			}
		}
		
		const query = new Parse.Query(Parse.User);
		query.limit(100);
		query.descending('createdAt');
		const results = await query.find({ useMasterKey: true });
		
		return results;
	}
}`

This functions outputs this in my production system:
`[{"username":"user1","emailVerified":true,"createdAt":"2021-09-01T15:47:05.998Z","updatedAt":"2021-09-14T09:54:49.179Z","ACL":{"role:admin":{"read":true,"write":true},"uSUfCjWRKq":{"read":true,"write":true}},"objectId":"uSUfCjWRKq"},{"username":"user2","emailVerified":true,"createdAt":"2021-09-01T15:46:48.860Z","updatedAt":"2021-09-01T18:01:27.890Z","ACL":{"role:admin":{"read":true,"write":true},"uV76SYtePM":{"read":true,"write":true}},"objectId":"uV76SYtePM"},
...
{"username":"user3","_email_verify_token":"haPJCwK2SIs9AZTDQ8P8ixFlR","emailVerified":false,"_email_verify_token_expires_at":"2021-09-02T15:43:04.347Z","createdAt":"2021-09-01T15:43:04.254Z","updatedAt":"2021-09-01T15:43:59.333Z","ACL":{"role:admin":{"read":true,"write":true},"95jUCDjVoP":{"read":true,"write":true}},"objectId":"95jUCDjVoP"},{"username":"myuser","emailVerified":true,"createdAt":"2021-01-29T13:01:12.909Z","updatedAt":"2021-09-18T16:46:35.027Z","ACL":{"7CodGbsEsu":{"read":true,"write":true},"role:admin":{"read":true,"write":true}},"sessionToken":"r:02e9a4381747146cfa97f7bbbeeaa31f","objectId":"7CodGbsEsu"}]`

This has a sessionToken present for myuser (last one in the array). Whereas when I run the same cloud function on the local git clone test I just get the user array without a sessionToken for my user added:
`[{"username":"mytestuser","createdAt":"2021-09-19T15:54:10.571Z","updatedAt":"2021-09-19T15:54:10.571Z","ACL":{"*":{"read":true},"4B4djUWZM6":{"read":true,"write":true}},"objectId":"4B4djUWZM6"}]`

I hope someone can help me understand that and I will continue working on reproducing the issue.

**Comment by mtrezza** [comment]
> when I run the same cloud function on the local git clone test I just get the user array without a sessionToken for my user added

Can you check whether the issue occurs on Parse Server 4.10.1 but not on 4.10.0?

**Comment by michaelilic** [comment]
The issue was a sessionToken that was stored with the user object in mongodb. Somehow, querying the database and fetching the user object overwrote the current sessionToken that was in use with the JS SDK. So the next call to the server was done with an old invalid sessionToken and therefore lead to an error. I solved it temporarily by deleting the invalid old sessionToken manually from the database.

The problem is/was present for me on Server 4.10.1  and 4.10.0. I am using the JS SDK 3.3.0, but it was also present in 3.2.0.

I am having a hard time replicating this issue, but I will post an update once I succeed creating a failing test scenario.
