### ISSUE TITLE
LiveQuery pointer comparison does not handle null

### ISSUE THREAD

**Issue by massimilianogalanti** [parse-community/parse-server#7929]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
Current [QueryTools.js](https://github.com/parse-community/parse-server/blob/852bb4782a28ad72a9dcb7b337a8b8876a87cbf1/src/LiveQuery/QueryTools.js#L204) implementation protects itself from undefined objects but not from null objects. By using Parse Dashboard, it happens to create nulls instead of undefineds.

### Feature / Enhancement Description
Checking for undefined and null.
`((typeof obj !== 'undefined') && obj !== null)`

### Example Use Case
Register a livequery with a comparison on a pointer, then put that pointer to null (by code or by dashboard)

### Alternatives / Workarounds
Use unset?

**Comment by mtrezza** [comment]
Is this actually a bug?

**Comment by massimilianogalanti** [comment]
It is unclear to me if putting Pointers to null instead of undefining them is an acceptable practice in parse server. If it is, then probably not protecting against it is a bug.

**Comment by hariprasadiit** [comment]
Yes, I've also faced the same issue. setting pointer to a null value results in exception. If this null is not a valid value for pointers, it'd be helpful if we document it.

**Comment by massimilianogalanti** [comment]
Any news on this?

**Comment by mtrezza** [comment]
What is the exception being thrown?

**Comment by massimilianogalanti** [comment]
```
2|launch-parse  | TypeError: Cannot read properties of null (reading 'className')
2|launch-parse  |     at .../node_modules/parse-server/lib/LiveQuery/QueryTools.js:208:68
2|launch-parse  |     at equalObjectsGeneric (.../node_modules/parse-server/lib/LiveQuery/QueryTools.js:147:10)
2|launch-parse  |     at matchesKeyConstraints (.../node_modules/parse-server/lib/LiveQuery/QueryTools.js:207:14)
2|launch-parse  |     at matchesQuery (...//node_modules/parse-server/lib/LiveQuery/QueryTools.js:132:10)
2|launch-parse  |     at ParseLiveQueryServer._matchesSubscription (.../node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:429:41)
2|launch-parse  |     at ParseLiveQueryServer._onAfterSave (.../node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:236:50)
2|launch-parse  |     at messageRecieved (.../node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:108:14)
2|launch-parse  |     at Subscriber.<anonymous> (.../node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:115:60)
2|launch-parse  |     at Subscriber.emit (node:events:517:28)
2|launch-parse  |     at EventEmitter.handler (.../node_modules/parse-server/lib/Adapters/PubSub/EventEmitterPubSub.js:26:12)
```

**Comment by mtrezza** [comment]
Thanks, could you open a PR with a simple test that demonstrates the issue? There are existing LiveQuery tests in the /spec directory for guidance. Then you could just add the suggested fix in your first comment and we can fix the bug.
