### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by sjxuereb** [parse-community/parse-server#8384]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I am not able to upload "large" [less than 20mb] files. I am using Android SDK.

### Steps to reproduce

I have modified and increased the limit of **100kb to 20mb**  bytes.parse(opts.limit || '20mb') : 
**But it did not work.**

/usr/local/lib/node_modules/parse-server/node_modules/body-parser/lib/types/urlencoded.js
/usr/local/lib/node_modules/parse-server/node_modules/body-parser/lib/types/raw.js

**&**

/usr/local/lib/node_modules/parse-server/node_modules/express/node_modules/body-parser/lib/types/urlencoded.js
/usr/local/lib/node_modules/parse-server/node_modules/express/node_modules/body-parser/lib/types/raw.js

### Actual Outcome

Please see logs below

### Environment

Server

    Parse Server version: 5.4.0
    Operating system: -Ubuntu
    Local

Database
    System (MongoDB or Postgres): MONGODB
    Database version: 6.0.3
    Local POD on same k8 cluster as parseserver

Client
Parse-SDK-Android:parse:4.1.0

### Logs

**PayloadTooLargeError: request entity too large**
    at readStream (/usr/local/lib/node_modules/parse-server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/usr/local/lib/node_modules/parse-server/node_modules/raw-body/index.js:109:12)
    at read (/usr/local/lib/node_modules/parse-server/node_modules/body-parser/lib/read.js:79:3)
    at rawParser (/usr/local/lib/node_modules/parse-server/node_modules/body-parser/lib/types/raw.js:81:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)

**Comment by sjxuereb** [comment]
Resolved by increasing  MAX_UPLOAD_SIZE

maxUploadSize: process.env.MAX_UPLOAD_SIZE || '200mb',
