### ISSUE TITLE
Unable to convert an anonymous user to real user in 6.0.0

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-server#8482]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

After logging in as an anonymous user, this user should be able to be converted to a real user by specifying the user name and password. The same code works fine in parse-server 5.4.2 and below, but throws an error in 6.0.0.

What's even more weird as this call is a `PUT` call, but the error thrown states it as a `POST` which is incorrect.

Because of the change from `PUT` to `POST`, I suspect the error has something to do with the trigger or auth updates that have been made in the latest versions

### Steps to reproduce

1. Login as an anonymous user
2. Set the username and password for this user
3. Sign up the current user to convert it to a real user

The test case below in the test suite replicates the steps above. It's possible, the issue can be related to the updated default settings on the server or something else:

https://github.com/parse-community/parse-server/blob/65e5879e42cefb4b462c9383af3705d027131242/spec/ParseUser.spec.js#L2915-L2986

### Actual Outcome

Error posted in logs below

### Expected Outcome

User should be signed in as a real user with a new session token

### Environment

Server
- Parse Server version: `6.0.0`
- Operating system: `Docker/Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `15`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `REST`
- SDK version: `N/A`

### Logs

```bash
2023-03-15 11:24:25 error: Received an error with invalid JSON from Parse: <!DOCTYPE html>
2023-03-15 11:24:25 <html lang="en">
2023-03-15 11:24:25 <head>
2023-03-15 11:24:25 <meta charset="utf-8">
2023-03-15 11:24:25 <title>Error</title>
2023-03-15 11:24:25 </head>
2023-03-15 11:24:25 <body>
2023-03-15 11:24:25 <pre>Cannot POST /1/classes/_User/dmTnBzViLv0qFfbRCjpXFJLdCIADopzZ</pre>
2023-03-15 11:24:25 </body>
2023-03-15 11:24:25 </html>
2023-03-15 11:24:25  {"code":107,"stack":"Error: Received an error with invalid JSON from Parse: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /1/classes/_User/dmTnBzViLv0qFfbRCjpXFJLdCIADopzZ</pre>\n</body>\n</html>\n\n    at handleError (/parse-server/node_modules/parse/lib/node/RESTController.js:373:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ParseUser.fetch (/parse-server/node_modules/parse/lib/node/ParseUser.js:645:5)\n    at async Object.handleAuthDataValidation (/parse-server/lib/Auth.js:414:5)\n    at async RestWrite.handleAuthData (/parse-server/lib/RestWrite.js:392:9)"}
```

**Comment by cbaker6** [comment]
Issue was a mistake by me, not an issue with the server
