### ISSUE TITLE
Vkontakte Adapter fails authentication.

### ISSUE THREAD

**Issue by MattKirchhof** [parse-community/parse-server#8626]
### New Issue Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [ X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
Vkontakte Adapter fails authentication.

When trying to use Parse to authenticate a vkontakte account holder (via Adapters/Auth/vkontakte.js), we encounter the following error:

"Parse error:  Vk appIds or appSecret is incorrect."

stack trace: 

"Error: Vk appIds or appSecret is incorrect.at /app/node_modules/parse-server/lib/Adapters/Auth/vkontakte.js:20:11
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Promise.all (index 0)"

We have noticed that the vkontakte.js file has not been updated since 2020. We have verified multiple times that our appId and secret are correct and unchanged.

After contacting VK support, they noted an API change as of Oct 2022. See their response:

Reply - "Since October 17, 2022, we have disabled the ability to obtain a service token through the Client Credentials Flow: https://dev.vk.com/reference/roadmap#Disabling_Clien... If you are working with methods in the secure section, you need to use the service key from the application settings."

### Steps to reproduce

Any login via vkontakte results in this error

When performing the request manually via curl (following current vkontakte.js current implementation), we receive an error:

curl -X POST 'https://oauth.vk.com/access_token' \
-d 'grant_type=client_credentials' \
-d 'client_id=0000000' \
-d 'client_secret=XXXXXXXXXXXXXXXXXXXX' \
-d 'v=5.124'

{"error":"invalid_grant","error_description":"Access denied"}

### Actual Outcome

See above stack trace and error

Server
- Parse Server version: 4.10.4 ( we think? most recent vkontakte Adapter is present.)
- Operating system: `Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): AWS

Database
- System (MongoDB or Postgres): PSQL
- Database version: 
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): AWS

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): Any client
- SDK version: 

### Logs

{"code":101,"level":"error","message":"Parse error:  Vk appIds or appSecret is incorrect.","stack":"Error: Vk appIds or appSecret is incorrect.\n    at /app/node_modules/parse-server/lib/Adapters/Auth/vkontakte.js:20:11\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Promise.all (index 0)"}

**Comment by mtrezza** [comment]
Thanks for reporting this; do you want to open a PR to make the API changes?

**Comment by MattKirchhof** [comment]
Sure! I have a fixed version of vkontakte.js ready for review, if you could help me open a PR to do so.

**Comment by mtrezza** [comment]
See our [Contribution Guide](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md) for how to make a pull request, or read our [New Contributor's Guide](https://blog.parseplatform.org/learn/tutorial/community/nodejs/2021/02/14/How-to-start-contributing-to-Parse-Server.html) if this is your first time contributing.
