### ISSUE TITLE
Bug in ParseFile saving in version 6.2.0

### ISSUE THREAD

**Issue by beiguancyc** [parse-community/parse-server#8637]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

In version 6.2.0, if the ParseFile filename does not include an extension, it will result in a save failure.
Based on my testing, the issue with the code occurs in src/Routers/FilesRouter.js at line 164.

```
      let extension = contentType;
      if (filename && filename.includes('.')) {
        extension = filename.split('.')[1];
      } else if (contentType && contentType.includes('/')) {
        extension = contentType.split('/')[1];
      }
      extension = extension.split(' ').join('');

      if (!isValidExtension(extension)) {
        next(
          new Parse.Error(
            Parse.Error.FILE_SAVE_ERROR,
            `File upload of extension ${extension} is disabled.`
          )
        );
        return;
      }
```

**Comment by mtrezza** [comment]
Could you verify that this is an issue with the Parse .NET SDK, and not with Parse Server by using the REST API?

**Comment by beiguancyc** [comment]
> Could you verify that this is an issue with the Parse .NET SDK, and not with Parse Server by using the REST API?

I did not encounter this issue when using version 5.x previously, but it started occurring after upgrading to version 6.2.0.

**Comment by mtrezza** [comment]
Could you try to narrow it down to a specific Parse Server version? I understand you encountered the issue in 6.2.0, does it occur also in 6.0.0?

**Comment by dblythy** [comment]
It would be by `6.2.0`, introduced by the introduction of implicitly defined file types to prevent the HTML phishing vulnerability

**Comment by beiguancyc** [comment]
> I would assume it would be `6.2.0`, introduced by the introduction of implicitly defined file types to prevent the HTML phishing vulnerability. What is the error you are seeing, is it `File upload of extension "" is disabled`? Or is a different line throwing an uncaught error?
> 
> Could you please be more specific with the exact error that is throwing?

I got this
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read properties of undefined (reading 'split')
    at createHandler (c:\Users\Administrator\AppData\Roaming\npm\node_modules\parse-server\lib\Routers\FilesRouter.js:146:29)
    at Layer.handle [as handle_request] (c:\Users\Administrator\AppData\Roaming\npm\node_modules\parse-server\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\Users\Administrator\AppData\Roaming\npm\node_modules\parse-server\node_modules\express\lib\router\route.js:144:13)
    at handleParseSession (c:\Users\Administrator\AppData\Roaming\npm\node_modules\parse-server\lib\middlewares.js:299:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by mtrezza** [comment]
Could you open `node_modules\parse-server\lib\Routers\FilesRouter.js:146:29` and post the line here?

**Comment by dblythy** [comment]
@mtrezza check slack PMs

**Comment by beiguancyc** [comment]
> Could you open `node_modules\parse-server\lib\Routers\FilesRouter.js:146:29` and post the line here?

<img width="1121" alt="image" src="https://github.com/parse-community/parse-server/assets/12932389/879b148f-f729-4e14-80d4-32a730a3c88c">
