### ISSUE TITLE
Errors after setting `enableAnonymousUsers: false`

### ISSUE THREAD

**Issue by hej2010** [parse-community/parse-server#8681]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

I had anonymous users enabled in my server, but after changing `enableAnonymousUsers: true` to `false` I get a lot of errors when querying the _User class/list in the Parse dashboard and from Cloud code.

```
TypeError: Cannot read properties of undefined (reading 'afterFind')
  at /home/parse/node_modules/parse-server/lib/Adapters/Auth/index.js:204:11
  at Array.map (<anonymous>)
  at Object.runAfterFind (/home/parse/node_modules/parse-server/lib/Adapters/Auth/index.js:197:32)
  at /home/parse/node_modules/parse-server/lib/RestQuery.js:698:85
  at Array.map (<anonymous>)
  at RestQuery.handleAuthAdapters (/home/parse/node_modules/parse-server/lib/RestQuery.js:698:43)
  at /home/parse/node_modules/parse-server/lib/RestQuery.js:201:17
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
All anonymous users have been deleted from the database but that did not solve the problem.
All other classes load fine but not the _User class.

### Steps to reproduce

Add anonymous users when `enableAnonymousUsers: true` and convert some of them into real users (with an email).
Set `enableAnonymousUsers: false` and query the _User class.

### Actual Outcome

Server error, no results are returned.

### Expected Outcome

The query to work.

### Environment

Server
- Parse Server version: `6.2.1`
- Operating system: `Ubuntu server 20.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote VPS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.22`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote VPS`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Parse dashboard / Cloud code`
- SDK version: `5.1.0 / 6.2.1`

### Logs

Crashes at line 235 since `adapter` is null.
https://github.com/parse-community/parse-server/blob/a742656a90a3db73b5d2087c4643a144637ae6bb/src/Adapters/Auth/index.js#L213-L235

### Fixed by
I replaced `enableAnonymousUsers: false` with 
```
auth: {
    anonymous: {
      enabled: false
    }
  }
```
and it no longer crashes.

**Comment by mtrezza** [comment]
If there is an `auth.anonymous.enabled` option, maybe the option `enableAnonymousUsers` should be deprecated, since it's now possible to set 2 conflicting options.
