### ISSUE TITLE
File upload of [extension type] is disabled

### ISSUE THREAD

**Issue by andreisucman** [parse-community/parse-server#8750]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

Hello, I get an error saying that file upload for an extension type is disabled.

This is for a .doc document.

` File upload of extension vnd.openxmlformats-officedocument.wordprocessingml.document is disabled.`

And this is for a .txt

`File upload of extension plain is disabled`

Same thing for PDF.

How to enable all types of file uploads?

ChatGPT says this line can be the problem `const regex = new RegExp(fileExtensions);` as `Creating a regex directly from the array will not work as intended`

### Steps to reproduce
Add this to your server config and try to upload a file

```
fileUpload: {
      enableForAnonymousUser: true, // Is true if file upload is enabled for Anonymous Users. Default is false.
      enableForAuthenticatedUser: true, // If true if file upload is enabled for anyone with access to the Parse Server file upload endpoint, regardless of user authentication. Default is false.
      enableForPublic: true, // If true if file upload is enabled for anyone with access to the Parse Server file upload endpoint, regardless of user authentication. Default is false.
    },
```

```
export async function uploadFile({ file }) {
  const parseFile = new Parse.File(nanoid(), file);

  try {
    Parse.initialize(process.env.NEXT_PUBLIC_APP_ID);
    Parse.serverURL = `${process.env.NEXT_PUBLIC_SERVER_URL}/parse`;

    await parseFile.save();
    return parseFile.url();
  } catch (err) {
    switch (err.code) {
      case Parse.Error.INVALID_SESSION_TOKEN:
      case Parse.Error.SESSION_MISSING:
        await Parse.User.logOut();
        window.location.href = `${process.env.NEXT_PUBLIC_SITE_URL}/login`;
        break;
    }
    return err;
  }
}
```

```
<label htmlFor="fileField" className={styles.label}>
          {docFile?.name || "Doc file to upload"}
          <input
            type="file"
            id="fileField"
            name="file"
            accept=".docx,.txt, .pdf"
            hidden
            onChange={(e) => setDocFile(e.target.files[0])}
          />
        </label>
```

### Actual Outcome
`error: File upload of extension plain is disabled. {"code":130,"stack":"Error: File upload of extension plain is disabled.\n    at createHandler (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\parse-server\\lib\\Routers\\FilesRouter.js:148:14)\n    at Layer.handle [as handle_request] (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at handleParseSession (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\parse-server\\lib\\middlewares.js:281:7)\n    at Layer.handle [as handle_request] (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at handleRateLimit (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\parse-server\\lib\\middlewares.js:275:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
error: Invalid function: "ingestInfo" {"code":141,"stack":"Error: Invalid function: \"ingestInfo\"\n    at handleCloudFunction (C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\parse-server\\lib\\Routers\\FunctionsRouter.js:109:13)\n    at C:\\Users\\andrei\\Desktop\\project\\management\\node_modules\\parse-server\\lib\\PromiseRouter.js:74:20\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}`

### Environment
nodejs 18.7.1

Server
- Parse Server version: `6.3.0`
- Operating system: `Win x64`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `6.0.10`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version:`4.2.0`

**Comment by andreisucman** [comment]
The issue was caused by having an additional "functions" folder outside of the "cloud" folder. Not sure how is that related, but renaming the outer "functions" folder and reinstalling node modules and lock fixed the problem.

**Comment by andreisucman** [comment]
The issue was related to having an additional "functions" folder outside of the "cloud" directory. Renaming the outer functions folder and reinstalling node modules and package lock fixed the issue.
