### ISSUE TITLE
Crash when uploading a file without an extension

### ISSUE THREAD

**Issue by chriscborg** [parse-community/parse-server#8778]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When a user attempts to upload a file without a file extension, the app crashes. This started happening the with release of this feature -> #8538 to restrict file upload by type. 

The crash is happening in the `FilesRouter.js:185` in the below line when extension is undefined.
`extension = extension.split(' ').join('');`

### Steps to reproduce

With the Android SDK, this can be achieved like so:
```
ParseFile image = new ParseFile("myImage", bitmapBytes);
try {
    image.save();
} catch (ParseException e) {
    e.printStackTrace();
}
```

### Actual Outcome

The server crashes with the below error:
```
/app/node_modules/parse-server/lib/ParseServer.js:261
   throw err;
TypeError: Cannot read properties of undefined (reading 'split')
   at createHandler (/app/node_modules/parse-server/lib/Routers/FilesRouter.js:185:29)
   at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/app/node_modules/express/lib/router/route.js:144:13)
   at /app/node_modules/parse-server/lib/middlewares.js:281:7
   at runMicrotasks (<anonymous>)
   at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Outcome

Ideally the config should allow for a workaround to allow files without an extension for production environment with this issue already in place. At best, the server should not crash in any case.

### Environment

Server
- Parse Server version: `5.5.5`
- Operating system: `Reproduced on macOS 14.0 and linux based cloud platform`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Both local and Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.25`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local and MongoDB Atlas`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Android`
- SDK version: `4.2.1`

### Logs

Log provided in Actual Outcome

**Comment by mtrezza** [comment]
Thanks for reporting; this may be fixed with https://github.com/parse-community/parse-server/issues/8769, but it doesn't seem to have been backported to Parse Server 5.

**Comment by chriscborg** [comment]
Will try it out as I have never contributed PRs on this project before so it will take me some time. In the meantime is there a workaround to disable this feature somehow as I can't update Parse and benefit from sercurity updates until this is resolved?

**Comment by mtrezza** [comment]
You could go into Parse Server and disable the extension check. But note that you are running a version of Parse Server that is only receiving critical security updates and will receive no updates at all anymore in ~2 months, so maybe this is a good opportunity to upgrade to Parse Server 6.

**Comment by mtrezza** [comment]
@chriscborg I have opened https://github.com/parse-community/parse-server/pull/8779 with a test case and can confirm that the bug also exists in Parse Server 6. I will publish a release in the next hour or so for Parse Server 6 and 5. You could take a look at how the PR is done, in case you come across something like this in the future - it also helps to seep up the bug fixing for us.

Just note that you are running Parse Server 5 which is only receiving critical security updates (on a best effort basis) and will receive no updates at all anymore from Dec 31. We will also begin to prioritize the release preparations for Parse Server 7, so Parse Server 5 will already receive less attention from Nov 1st onwards. Maybe this is a good opportunity to upgrade to Parse Server 6.
