### ISSUE TITLE
Parse Jobs are not firing

### ISSUE THREAD

**Issue by suathh** [parse-community/parse-server#8875]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description
When I try to start a job I get multiple failures.

### Steps to reproduce
1) Define a simple job (Logs "test" etc.)
2) Try to run the job via `/jobs/RankUsers` and you will get `"error": "unauthorized: master key is required"` even masterKey is provided and `masterKeyIPs: ['0.0.0.0/0', '::0']` added.
3) Create a scheduler script to run the job
4) Try to run the job via command line on your local by simply typing something like "node .\ranking.js" 

### Actual Outcome
For Step 2 I already explained
For step 4 

`TypeError: Cannot read properties of undefined (reading 'length')
    at Object.request (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\RESTController.js:204:17)  
    at Object.startJob (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\Cloud.js:140:43)
    at Object.startJob (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\Cloud.js:96:52)
    at Object.<anonymous> (C:\Users\Suat\Documents\GitHub\kale-usta-backend\jobs\ranking.js:9:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47`
    
    I dig the root line for the error and it is Line 203 in RestController.js 
    
`    let url = _CoreManager.default.get('SERVER_URL');`

My server URLs are defined 

### Expected Outcome
Job start success response
### Environment
Tried on both Linux & Windows env.

```
"parse": "^4.3.1",
"parse-server": "^6.4.0",
```

Server
- Parse Server version: `6.4.0`
- Operating system: `Linux/Windows`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local/Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: ``
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local/Heroku`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS SDK`
- SDK version: `4.3.1`

### Logs
Logs from the QA Server

Jan 07 01:40:40 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587223211241473&selected=1680587223211241473) [heroku/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.5855&focus=1680587223211241473&selected=1680587223211241473) Starting process with command `node jobs/ranking.js`
Jan 07 01:40:40 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587225635549185&selected=1680587225635549185) [heroku/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.5855&focus=1680587225635549185&selected=1680587225635549185) State changed from starting to up
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587228961669123&selected=1680587228961669123) [heroku/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.5855&focus=1680587228961669123&selected=1680587228961669123) State changed from up to complete
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229121081349&selected=1680587229121081349) [heroku/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.5855&focus=1680587229121081349&selected=1680587229121081349) Process exited with status 0
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607300&selected=1680587229175607300) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607300&selected=1680587229175607300) ParseError: unauthorized
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607301&selected=1680587229175607301) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607301&selected=1680587229175607301)     at handleError (/app/node_modules/parse/lib/node/RESTController.js:298:17)
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607302&selected=1680587229175607302) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607302&selected=1680587229175607302)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607303&selected=1680587229175607303) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607303&selected=1680587229175607303)     at async Object.startJob (/app/node_modules/parse/lib/node/Cloud.js:140:22) {
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607304&selected=1680587229175607304) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607304&selected=1680587229175607304)   code: undefined
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607305&selected=1680587229175607305) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607305&selected=1680587229175607305) }
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607306&selected=1680587229175607306) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607306&selected=1680587229175607306) ParseError: unauthorized
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607307&selected=1680587229175607307) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607307&selected=1680587229175607307)     at handleError (/app/node_modules/parse/lib/node/RESTController.js:298:17)
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607308&selected=1680587229175607308) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607308&selected=1680587229175607308)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607309&selected=1680587229175607309) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607309&selected=1680587229175607309)     at async Object.startJob (/app/node_modules/parse/lib/node/Cloud.js:140:22) {
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607310&selected=1680587229175607310) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607310&selected=1680587229175607310)   code: undefined
Jan 07 01:40:41 [kale-backend-qa](https://my.papertrailapp.com/systems/kale-backend-qa/events?focus=1680587229175607311&selected=1680587229175607311) [app/scheduler.5855](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.5855&focus=1680587229175607311&selected=1680587229175607311) }

Logs from DEV server when I try to start job by REST API 

2024-01-07T09:38:36.971824+00:00 app[web.1]: Error: unauthorized: master key is required
2024-01-07T09:38:36.971825+00:00 app[web.1]:     at promiseEnforceMasterKeyAccess (/app/node_modules/parse-server/lib/middlewares.js:430:19)
2024-01-07T09:38:36.971826+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/PromiseRouter.js:74:20
2024-01-07T09:38:36.971826+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-07T09:40:11.627556+00:00 app[api]: Starting process with command `node jobs/mediacenter.js` by user scheduler@addons.heroku.com
2024-01-07T09:40:21.941786+00:00 heroku[scheduler.1299]: Starting process with command `node jobs/mediacenter.js`
2024-01-07T09:40:22.522721+00:00 heroku[scheduler.1299]: State changed from starting to up
2024-01-07T09:40:23.285614+00:00 heroku[scheduler.1299]: Process exited with status 1
2024-01-07T09:40:23.202572+00:00 app[scheduler.1299]: /app/node_modules/parse/lib/node/RESTController.js:298
2024-01-07T09:40:23.202579+00:00 app[scheduler.1299]:         error = new _ParseError.default(errorJSON.code, errorJSON.error);
2024-01-07T09:40:23.202579+00:00 app[scheduler.1299]:                 ^
2024-01-07T09:40:23.202580+00:00 app[scheduler.1299]: 
2024-01-07T09:40:23.202580+00:00 app[scheduler.1299]: ParseError: unauthorized
2024-01-07T09:40:23.202581+00:00 app[scheduler.1299]:     at handleError (/app/node_modules/parse/lib/node/RESTController.js:298:17)
2024-01-07T09:40:23.202581+00:00 app[scheduler.1299]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-01-07T09:40:23.202581+00:00 app[scheduler.1299]:   code: undefined
2024-01-07T09:40:23.202581+00:00 app[scheduler.1299]: }
2024-01-07T09:40:23.202581+00:00 app[scheduler.1299]: 
2024-01-07T09:40:23.202582+00:00 app[scheduler.1299]: Node.js v20.10.0

Logs from Local when I try both Rest API or Trigger the Node script

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.request (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\RESTController.js:204:17)
    at Object.startJob (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\Cloud.js:140:43)
    at Object.startJob (C:\Users\Suat\Documents\GitHub\kale-usta-backend\node_modules\parse\lib\node\Cloud.js:96:52)
    at Object.<anonymous> (C:\Users\Suat\Documents\GitHub\kale-usta-backend\jobs\ranking.js:9:13)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at node:internal/main/run_main_module:23:47

**Comment by mtrezza** [comment]
Seems like a duplicate of https://github.com/parse-community/parse-server/issues/8872?

You mention this happens on "Linux/Windows", but the log shows only Windows; can you confirm this happens on Linux as well?

**Comment by suathh** [comment]
Yes it is also happening on Linux. Tested on heroku environment

**Comment by suathh** [comment]
> Seems like a duplicate of https://github.com/parse-community/parse-server/issues/8872?
> 
> 
> 
> You mention this happens on "Linux/Windows", but the log shows only Windows; can you confirm this happens on Linux as well?

One part of it yes, but when you pass masterKey control it still logs the error I explained in the issue

Linux tested on Heroku, same result as windows

**Comment by suathh** [comment]
@mtrezza I have now more confidence and clues to consider this is a duplicate of https://github.com/parse-community/parse-server/issues/8872

**Comment by mtrezza** [comment]
In your description that you are using `masterKeyIPs: ['0.0.0.0/0', '::0']` but to allow "any IPv6 address" it should be `masterKeyIPs: ['0.0.0.0/0', '::/0']`. Could you try that?

**Comment by mtrezza** [comment]
Closing as resolved, see discussion in https://github.com/parse-community/parse-server/issues/8872. If the issue still exists, please comment and we can re-open.
