### ISSUE TITLE
Parse.Cloud.beforeSaveFile, Parse.Cloud.afterSaveFile is not a function, but other triggers work correctly

### ISSUE THREAD

**Issue by BeyondIM** [parse-community/parse-server#9165]
I run parse server with docker according to the document, run the code in the api manual for testing

```
Parse.Cloud.beforeSave(Parse.User, (request) => {
  // code here
})
```

```
parse_server_dating  | TypeError: Parse.Cloud.beforeSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  | Error on ParseServer.startApp:  TypeError: Parse.Cloud.beforeSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  | TypeError: Parse.Cloud.beforeSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

```

```
Parse.Cloud.afterSaveFile(async ({ file, user }) => {
  const fileObject = new Parse.Object('FileObject');
  fileObject.set('metadata', file.metadata());
  fileObject.set('tags', file.tags());
  fileObject.set('name', file.name());
  fileObject.set('createdBy', user);
  await fileObject.save({ sessionToken: user.getSessionToken() });
});
```

```
parse_server_dating  | TypeError: Parse.Cloud.afterSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  | Error on ParseServer.startApp:  TypeError: Parse.Cloud.afterSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  | TypeError: Parse.Cloud.afterSaveFile is not a function
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/triggers/toWebp.js:1:13)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
parse_server_dating  |     at Module.load (node:internal/modules/cjs/loader:1208:32)
parse_server_dating  |     at Module._load (node:internal/modules/cjs/loader:1024:12)
parse_server_dating  |     at Module.require (node:internal/modules/cjs/loader:1233:19)
parse_server_dating  |     at require (node:internal/modules/helpers:179:18)
parse_server_dating  |     at Object.<anonymous> (/parse-server/cloud/main.js:1:1)
parse_server_dating  |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
parse_server_dating  |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

```

**Comment by wagnercsfilho** [comment]
@BeyondIM @mtrezza  any update? same error here

**Comment by beiguancyc** [comment]
Parse.Cloud.afterSave(Parse.File,request => { 
});

**Comment by mtrezza** [comment]
@wagnercsfilho Note that the file trigger syntax has changed in Parse Server 7:

```
Parse.Cloud.afterSave(Parse.File, request => {
});
```

See https://github.com/parse-community/parse-server/pull/8855. It seems the docs still need to be updated. Does anyone want to open a PR?
